### ISSUE TITLE
Séparer le menu administration

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1006]
## Problème

Le menu aujourd'hui est constitué de 2 niveaux, parce qu'il y a trop d'items, et que ces items sont rangé par thématique.

Un des problème est la manipulation supplémentaire que cela demande pour la navigation (alors qu'elle occupe en permanence une partie de l'espace de travail).

L'autre problème est le manque de clarté du rôle admin (qui s'additionne à un rôle lié à un service).

## Solution

Nous pourrions déplacé tout le menu Paramètres dans une autre « page », un peu comme la sectorisation.

L'entrée vers cette page pourrait, comme pour la secto, être accessible dans la page des organisations. Il pourrait y avoir à coté de chaque lien vers une organisation, un lien pour la paramétrer.

Il est sans doute nécessaire d'utiliser un design de bouton ou autre pour distinguer l'accès aux paramètres de l'accès à l'organisation.

**Comment by adipasquale** [comment]
est-ce qu'on est sûrs que ce soit une bonne idée @yaf ? même si je partage le fait que ça ne soit pas super pratique aujourd'hui le sous menu, j'ai peur que cette direction rende l'accès à l'admin plus lent, et il me semble que les gens doivent basculer entre les deux très fréquemment.

**Comment by yaf** [comment]
Je ne partage pas ton analyse sur le fait de basculer de l'un à l'autre. Enfin, je pense qu'on pourrait le vérifier.

Ça pourrait être un très bon scénario de test utilisateur (si nous prenons le temps d'en faire). À défaut, je pourrais questionner les admin.
Sans doute un ticket à renvoyer dans le forum pour en parler.

**Comment by adipasquale** [comment]
je pense en effet que ce ticket n'est pas assez mûr et qu'il mériterait d'être rebasculé sur le forum @yaf

**Comment by yaf** [comment]
https://forum.rdv-solidarites.fr/t/separation-du-menu-parametrage-et-des-menus-de-calendrier/130/2
