### ISSUE TITLE
alerter en cas de chevauchement avec une absence dans le tunnel RDV agent

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1007]
De la même manière que nous avons commencé à mettre en place des alertes sur des colisions de plage d'ouverture, de rendez-vous sur d'autres plages d'ouvertures, nous pourrions ajouter une alertes sur un rendez-vous qui tombent sur une absence.

Fonctionne dans les deux sens ?
- Depuis un rdv (création et modification) vers une absence
- Création d'une absence sur une plage où il y a déjà des rendez-vous 

Dans un premier temps, nous pourrions faire un message d'alerte, et rediriger vers l'agenda sur la période et l'agent concernée.

et/ou proposer la réattribution à un autre agent ou l'annulation ?

**Comment by adipasquale** [comment]
ça me fait me poser une question : si je suis agent et que j'appartiens à plusieurs orgas, et que je veux dire je suis en congé tel jour, pour l'isntant je suis obligé de créer des absences dans chacune des orgas. 

Il n'y a pas le même problème pour les plages d'ouvertures, qui elles sont bien dans le contexte d'une organisation. Tel que c'est modelisé aujourd'hui, les absences sont aussi dans le contexte d'une orga mais je suppose que la grande majorité des absences sont des absences à l'échelle de l'agent, des congés ou indispos. A valider

**Comment by n-b** [comment]
J’ai ajusté le ticket pour grouper avec un sujet très proche: la collision de deux Rdv faits en même temps dans le tunnel de prise de rendez-vous.

**Comment by n-b** [comment]
J’ajoute aussi à ce ticket la gestion des collisions de deux Rdv d’un même usager, même si le Rdv est en train d’être posé par un agent. (Ça pose des questions un peu différentes: si le premier Rdv est dans une autre organisation, on ne peut pas l’afficher à l’agent, donc on doit simplement dire “cet usager à un autre Rdv”, sans plus de détail.)
