### ISSUE TITLE
reparer rendu sur vieux firefox

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1011]
cf mail de christelle leroy du 22 le 26/11 (fwd a contact par adrien le 30/11)

il faut a minima reparer l'apparition de l'ellipsis pour les invitations a droite sinon ils ne peuvent pas renvoyer d'invits

![Screenshot-2020-11-26_RDV_Solidarités](https://user-images.githubusercontent.com/42057/102241782-a458e480-3ef9-11eb-8305-3e8856fafee7.png)

**Comment by yaf** [comment]
@adipasquale dit 
> pas reussi a reproduire, remonté jusqu'à FF 47 🤷‍♀️

**Comment by adipasquale** [comment]
je ferme car on n'arrive pas a reproduire
