### ISSUE TITLE
Permettre l'envoi de SMS depuis Mobimel

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1013]
[MOBIMEL.PDF](https://github.com/betagouv/rdv-solidarites.fr/files/5697147/MOBIMEL.PDF)

**Comment by yaf** [comment]
@guillett 
> Il faudrait demander au département des Côtes d'Armor des identifiants pour tester.

**Comment by yaf** [comment]
@guillett 

> CF email de
Stephane.NORGEOT@cotesdarmor.fr
21/10/2020 à 12:08

Avez-vous un marché existant pour l'envoi de SMS en masse ? contrat avec Mobimel (Adista) sans mise en concurrence préalable

    Si oui, quel est votre prestataire ? Mobimel (adista)
    Avez-vous de la documentation technique pour nous permettre de préparer le connecteur pour l'envoi de SMS ?
    Documentation de l’API en PJ.
    Avez-vous des identifiants de connexion pour nous permettre l'envoi de SMS pour votre compte ?
    Création d’un identifiant possible sur demande
    Si non, nous avons expérimenté et comparé plusieurs fournisseurs de SMS et nous pouvons vous aider à y faire appel.
    Avec qui pourrions-nous échanger sur ce sujet au sein de votre département ? > Guillaume LE PROVOST / guillaume.leprovost@cotesdarmor.fr

**Comment by guillett** [comment]
Il faut vérifier si cela est encore pertinent. Il est possible que les Côtes d'Armor choisissent de ne pas utiliser ce prestataire au profit de NetSize (moins cher).
