### ISSUE TITLE
France Connect

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1024]
Permettre aux usagers de se connecter à partir de France Connect.

Il s'agit de créer une Nouvelle Stratégie OpenID connect (cf devise / omniauth) pour France Connect et de la rattacher au modèle User.

**Comment by yaf** [comment]
@guillett dit

> J'ai créé une autre carte sur un sujet très proche. Expérimenter la connexion avec un gestionnaire d'identité côté Agents
> 
> L'idée est de sortir la complexité associée aux comptes pour plus facilement intégrer diverses fournisseurs d'identités.
>

**Comment by adipasquale** [comment]
en attente d'une reponse a un ticket pour avoir les credentials de prod
