### ISSUE TITLE
Expérimenter la connexion avec un gestionnaire d'identité côté Agents

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1025]
KeyCloak https://auth.incubateur.net
Permet de fédérer des identités.

Cela pourrait permettre d'externaliser la complexité d'intégration des agents des différents départements et leur éviter de créer un nième nouveau mot de passe.

Une stratégie similaire pourrait être appliquée pour les usagers avec France Connect mais aussi avec les différents fournisseurs d'identité mis en place par les départements via leur outils de gestion de la relation usager/citoyens.

- Demander un compte admin sur https://auth.incubateur.net/ (sur Slack #domain-auth https://app.slack.com/client/T04C2PSNY/CMZ4NGQM7 ou à moi)
- Reprendre les infos du client OpenID Connect créé pour le test https://auth.incubateur.net/auth/admin/master/console/#/realms/rdv-solidarites-test/clients/25fe6fe7-eb03-445e-97d4-023c695c04eb/credentials
- ajouter la possibilité côté agent de se connecter avec ce fournisseur d'identité
- créer un compte utilisateur et choisir un MDP https://auth.incubateur.net/auth/admin/master/console/#/create/user/rdv-solidarites-test

On pourra voir comment récupérer plus d'info que l'email (Nom, Prénom).

**Comment by yaf** [comment]
@guillett dit

> Le code du dev pour France Connect pourrait être repris, au moins en partie car il s'agit du protocol OpenID Connect.

**Comment by adipasquale** [comment]
je voterais pour fermer ce ticket en attendant que le sujet soit demandé par un nouveau département. pour les departements existants ça n'apportera pas grand chose il me semble. @guillett ça te va ?

**Comment by guillett** [comment]
C'est demandé par la Meuse. À partir d'un LDAP. dont on a les infos.

**Comment by guillett** [comment]
C'est un sujet assez opérationnel assez important côté agent. Ça pourrait éviter la création de nouveaux comptes (mots de passe) en le déléguant au gestionnaire.

**Comment by yaf** [comment]
Le souci serait sans doute de configurer un gestionnaire d'identité par département ! À moins qu'il existe un gestionnaire étatique dans lequel TOUS les agents sont référencé ? :smile: 

C'est peut-être un ticket lié au ticket sur la création de la notion de département #1124  ?

**Comment by adipasquale** [comment]
cf https://news.ycombinator.com/item?id=26409820 pour être vraiment paumé sur ce sujet ^^

**Comment by adipasquale** [comment]
je suis d'avis de fermer ce ticket qui ne me paraît pas clair et pas prioritaire
