### ISSUE TITLE
afficher notifs qui vont être envoyées dans le tunnel RDV agent

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1042]
Dans le tunnel de prise de rendez-vous, coté agent, on pourrait calculer et expliquer si des notifications vont partir ou non, et vers quelle numéro.

**Comment by adipasquale** [comment]
@yaf je pense qu'il vaut mieux faire ce ticket en premier : https://github.com/betagouv/rdv-solidarites.fr/issues/1166 car le comportement sera probablement générisé depuis les POs vers les absences

**Comment by yaf** [comment]
Ah ok, je vais le remettre dans le paquet alors :)

Je me demandais si on ajoutait un step dans le wizard pour afficher ce truc ?

**Comment by adipasquale** [comment]
pardon @yaf je pense que mon commentaire ne concernait pas ce ticket, mais le ticket qui consiste à rajouter des notifs mails ICS aux agents pour les absences

**Comment by yaf** [comment]
C'est pas clair pour moi. Tu dis que ton commentaire qui dit de faire le #1166 avant est un commentaire à mettre dans le #1166 ? Est-ce que tu pourrais reprendre (peut-être au bon endroit :))

Et c'est pas grave, je fais l'autre en premier tant pis :smile:

**Comment by adipasquale** [comment]
dsl, je voulais dire que le commentaire aurait du être sur #1051 si ça te va je supprime mes commentaires ici et je déplace le bon sur #1051

**Comment by adipasquale** [comment]
done ! et pour répondre à ta question, je ne sais pas où afficher ces nouvelles infos dans le tunnel de prise de RDV il faut peut-être rajouter une étape oui ! surtout si ça devient configurable par la suite, càd qu'on permette d'overrider le comportement avec une checkbox et de ne pas envoyer les notifs
