### ISSUE TITLE
API invitation usager

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1046]
post /user/id-externe/invite renvoie un lien d'invitation pour création de compte

**Comment by adipasquale** [comment]
même question ici a-t-on vraiment validé avoir un SI prêt à l'utiliser en face ?

**Comment by yaf** [comment]
Même question qu’où ?

:smile: 

Je crois que je ferais la même réponse. Et je crois me souvenir que ça dit : l'Aveyron attends que nous ayons fait le taf pour avancer sur leur partie des développements. À vérifier avec eux s'ils sont vraiment prêt ?

**Comment by yaf** [comment]
Même chose que le ticket #1047 c'est lié aux discussions en cours sur la gestion du RSA (voir avec @guillett)

**Comment by yaf** [comment]
Faut-il garder cette issue ou bien nous enrichissons une seule issue avec tous les éléments de l'API usager ?

**Comment by yaf** [comment]
lié avec https://github.com/betagouv/rdv-solidarites.fr/issues/1047

**Comment by adipasquale** [comment]
redemandé et validé par l'Aveyron qu'ils sont prêts à l'utiliser.

**Comment by HoulesBenoit** [comment]
Je confirme que ça nous intéresse et que nous sommes prêt.
Nous avons bien avancé sur les tests de l'API création utilisateur.

**Comment by HoulesBenoit** [comment]
Bonjour,

Avez vous un tout petit peu de visibilité à nous donner sur la réalisation de cette fonctionnalité ?
De notre côté, tout est OK, nous n'avons pas commencé à expérimenter la création auto des comptes, car il nous manque cette API. 
On estime qu'il est préférable que les usagers reçoivent directement une invitation de validation de création du compte, sans quoi cela pourrait poser quelque souci de compréhension pour eux, de double compte pour nous/vous.
On souhaite également éviter que les agents aillent d'eux même cliquer sur le lien, puisque l'API le ferait pour eux.

De la visibilité si vous en avez, nous permettrait de notre côté de communiquer auprès de l'équipe projet sur cette nouvelle phase.

Merci d'avance.

Bon weekend de Pâques.

**Comment by yaf** [comment]
C'est bien noté.

Difficile pour le moment d'avoir de la visibilité. Nous essayons de mettre en place un moyen de nous en donner un peu plus. Nous essayons de revenir vers vous rapidement.

**Comment by yaf** [comment]
@HoulesBenoit comme vous pouvez le voir, l'équipe Data.insertion, par le biais de @qblanc avance sur le sujet :)

Je pense que vous devriez vous parler. Je pense qu'il y a beaucoup de similitude entre ce que Boris va développer et ce que l'équipe Data.insertion souhaite réaliser.

**Comment by qblanc** [comment]
Bonjour @HoulesBenoit.
la fonctionnalité a été déployée. Si vous envoyez une requête get à https://rdv-solidarites.fr/api/v1/users/:id/invite
avec :id remplacé par l'id de l'utilisateur concerné, vous recevrez en réponse un json où la valeur de invitation_url sera le lien d'invitation.

N'hésitez pas à me dire si vous rencontrez des soucis.
