### ISSUE TITLE
API création usager

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1047]
post /users {user_params} pour la création d'usager, renvoie un id-externe

après discussion avec Benoit Barnier de l'aveyron : 

De notre point de vue, il faut au minimum que l'on vous envoi:
- nom
- prénom
- email
Et en retour, il nous faut à minima l'ID de l'utilisateur nouvellement créé.

eventuellement la possibilité de definir un ou des agents referents en meme temps - mais a priori c'est pour une mauvaise raison qu'ils souhaitent utiliser ca.

en cas d'erreur de creation d'usager car email deja utilise on renverra une erreur. il faut un peu reflechir a comment faire prorprement dans le cas ou un usager existe dans une autre orga / departement pour que ce soit clair ce qui est en train d'etre fait : ajouter un usager existant a une orga ou creer un usager tout neuf. que faire dans le cas ou l'api modifie un usager existant ? 

il y a potentiellement un sujet creation d'invitations d'usagers, on peut ignorer pour l'instant

**Comment by adipasquale** [comment]
@yaf qui a demandé ça et a-t-on vraiment un SI prêt à l'utiliser en face ? sinon je propose de supprimer ce ticket tant que ce n'est pas le cas

La seule route d'API qu'on ait développée pour l'instant n'a jamais été utilisée au final 😬

**Comment by yaf** [comment]
C'est l'Aveyron, et ils (Benoit) a dit qu'ils nous attendent pour tester et commencer des développements de leurs coté. C'est peut-être un point à « vérifier » avec eux pour s'assurer que c'est toujours bien le cas.

**Comment by yaf** [comment]
C'est sans doute à lier au discussion RSA animé par @guillett  ?

**Comment by yaf** [comment]
lié avec https://github.com/betagouv/rdv-solidarites.fr/issues/1046
