### ISSUE TITLE
Plages d'ouverture - Envoyer un ICS en cas de modification

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1048]

**Comment by adipasquale** [comment]
@yaf c'est déjà le cas normalement https://github.com/betagouv/rdv-solidarites.fr/blob/master/app/models/plage_ouverture.rb#L11

est-ce que ce ticket est un rapport de bug pour dire que ca ne fonctionne pas ?

**Comment by yaf** [comment]
non, c'est sans doute un vieux ticket pas à jour.
