### ISSUE TITLE
Interconnexion rdv-sol vers Outlook : prise en compte des modifications apportées à la fiche usager a posteriori de la pose d'un RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1049]
Les modifications apportées à la fiche usager (mail, num de tél et adresse) a posteriori de la pose du RDV ne sont pas prises en compte.

Exple : pose d'un RDV à domicile, l'usager déménage, il informe la MDS qui modifie l'adresse dans la fiche usager. L'info n'est pas transmise à Outlook

**Comment by adipasquale** [comment]
@yaf est-ce que tu parles de la synchronisation via : 
1. les évènements ICS envoyés par mail 
ou
2. l'interconnexion réalisée par le 62 via les webhooks ?

**Comment by yaf** [comment]
Je ne sais plus d'où vient ce ticket. Je vais le fermer, ça reviendra sans doute si c'est important.
