### ISSUE TITLE
Ajouter le jour de début de la plage d'ouverture dans l'ICS

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1050]
La Drôme trouve que c'est compliqué de se retrouver dans celles déjà validées et celles à valider.

**Comment by adipasquale** [comment]
je n'ai pas compris ce ticket tu peux préciser @yaf ? je suis quasiment sûr que le jour de début est déjà dans l'événement ICS envoyé par mail.
Est-ce que tu voulais dire qu'il faut le rajouter dans le sujet ou le corps du mail peut-être ?

**Comment by yaf** [comment]
Je suis ok pour supprimer celui-ci. Je ne sais pas trop à quoi il correspond.
