### ISSUE TITLE
Envoyer des notifications mails avec fichier ICS aux agents pour les absences

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1051]
Pour avoir un agenda synchronisé, il est nécessaire que, comme les plages d'ouvertures et les RDV, les plages d’absence soient transmises à Outlook/messagerie

https://forum.rdv-solidarites.fr/t/faire-apparaitre-automatiquement-et-systematiquement-les-absences-et-les-rendez-vous-sur-lagenda-zimbra-outlook/91/5

**Comment by adipasquale** [comment]
@yaf je pense qu'il vaut mieux faire ce ticket en premier : #1166 car le comportement sera probablement générisé depuis les POs vers les absences

(note ce commentaire était avant sur le ticket 1042 par erreur)
