### ISSUE TITLE
[interconnnexion] lien entre rdv-solidarites et outlook

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1052]
Déverser tous les rdv dans l'outlook pour que ça génère une invitation automatiquement implantée dans l'agenda souhaité. 
Seine-et-Marne

**Comment by adipasquale** [comment]
si l'on fait ça il faut : 
- le rendre paramétrable car la plupart (ou au moins une grande partie) des agents ne veulent pas recevoir un mail par rdv
- faire en sorte que ça ne fasse pas doublon avec l'alerte qui existe pour tous les agents aujourd'hui pour les rdvs de dernière minute. Il faut probablement construire par dessus ce service plutôt qu'en ajouter un nouveau.

**Comment by yaf** [comment]
Je me rends compte que j'ai posé ce ticket (qui doit provenir de @guillett comme la plupart à propos d'inter connexion) alors que je n'ai pas forcément bien saisi de quoi il s'agit.

Pour moi, c'était le fait de communiquer un fichier ICS dans le mail de notification ou quelque chose dans le genre pour que ça apparaissent dans l'agenda de l'agent. Peut-être que ça passe par une histoire d'API où le SI serait tenu au courant des rdv pour les synchroniser avec l'outil d'agenda qu'ils utilisent ?

Et peut-être que je n'ai rien compris.

@guillett si tu passes dans le coin et que tu peux nous éclairer un peu ? Sinon, on peut aussi fermer le ticket et on verra ce qui sera demandé plus tard, ça me convient.

**Comment by guillett** [comment]
Je ne suis pas sur de comprendre ce ticket. Le ticket trello a-t-il été archivé/supprimé ?
Il y a avait à un moment donné la volonté d'avoir tous les RDVs dans les agendas des agents et sans interconnexions ça passe forcément par l'envoi d'email avec ICS.

Je suis favorable à fermer ce ticket si l'on ne sait à qui cela rend service.
