### ISSUE TITLE
Dans la page de paramètre « Vos motifs » Filtrer les motifs par service et par type

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1054]
## problème

La liste est trop longue en visuel et on se perd dans les tags. 

## Solutions envisagée

https://forum.rdv-solidarites.fr/t/gerer-les-motifs-avec-filtre-et-champ-de-recherche/98

Comme proposé ci-dessous par @adipasquale, Clarisse (92) a une préférence pour un système de filtre. Pas d'autres participation pour le moment.

**Comment by adipasquale** [comment]
est-ce que tu peux préciser l'interface que tu imagines @yaf ?
ce qui me semblerait pertinent serait d'ajouter des filtres par type de RDV et par service dans un premier temps, ca ne devrait pas etre tres dur a faire.

**Comment by yaf** [comment]
Discussion entamée par Clarisse (92) :) https://forum.rdv-solidarites.fr/t/gerer-les-motifs-avec-filtre-et-champ-de-recherche/98
