### ISSUE TITLE
[VAD] Retirer les motifs VAD des plages d'ouvertures

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1055]
la création de  plages d'ouvertures n'est pas possible, il faut choisir un lieu référencé. 

=> enlever les motifs "à domicile" des créations des PO

**Comment by adipasquale** [comment]
je ne comprends pas ce ticket @yaf tu peux expliquer ? c'est un bug ou bien une incoherence ? il me semble que c'est autant incoherent que la creation de POs avec un motif telephonique non ?

**Comment by yaf** [comment]
Je crois que c'est lié au fait qu'une plage d'ouverture dois forcément avoir un lieu, et ce n'est donc pas possible de faire des motifs de Visite à domicile sur une plage d'ouverture.

J'imagine que c'est également un type de motif qui n'est pas ouvert à l’usager.

```ruby
Motif.where(location_type: "home").where(reservable_online: true).count
# => 2
```

Je viens de poser la question à Élodie (62) car ces deux motifs sont du site de Lens 1 :)

Nous pourrions aussi poser la question sur le forum. L'idée serait de vérifier si dans l'avenir, les visites à domicile seront ouverte à la réservation en ligne.

J'imagine que c'est un type de motif pour lequel les agents préfère organiser eux même leur journée, histoire d'optimiser les trajets selon des critères qui sorte de RDV-Sol.

**Comment by adipasquale** [comment]
> une plage d'ouverture dois forcément avoir un lieu

oui en effet, d'où ma remarque : c'est aussi incohérent que pour les motifs téléphoniques

je ne sais pas trop si c'est nécessaire d'empêcher les agents de faire quelque chose qu'ils ne font déjà pas et qui n' a pas l'air de poser de soucis particuliers. 

Si on va dans cette direction en fait je serai plutôt d'avis de rendre les motifs non sur-place irréservables en ligne, et par conséquent inutilisables dans les plages d'ouvertures.

Si le souci est que c'est dur de choisir parmi les motifs parce qu'ils sont trop nombreux et qu'on n'arrive pas à les distinguer je m'attaquerai plutôt à ce problème. Il faudrait d'ailleurs commencer par vérifier que les motifs irréservables en ligne sont bien exclus des proposés dans la création de plage d'ouverture ça pourrait résoudre ce sujet de manière plus cohérente.

**Comment by yaf** [comment]
Tu as raison, j'avais oublié les motifs téléphonique :D

Je pense qu'on pourrait surtout rendre le lieu facultatif finalement. Les plages d'ouvertures semblent être vraiment intéressante pour tous les motifs (même si aujourd'hui il y en a peu en VAD, ça pourrait changer une fois ouvert aux usagers).

Le hic viens surtout de l'incohérence que ça crée de devoir associer une plage d'ouverture à un lieu. Il y aura un `belong_to` à modifier.

Est-ce que ça te convient @adipasquale  ?

**Comment by adipasquale** [comment]
Hum je ne suis pas encore convaincu. Rendre facultatif le lieu me parait compliqué car il faudrait le permettre uniquement pour des POs contenant uniquement des motifs téléphoniques et ou VAD, ça risque d'être compliqué à expliciter dans l'interface. 

En fait je ne comprends pas quel est le problème qu'on essaie de résoudre ici, tu peux détailler ce qui t'a été remonté par les agents ou bien que tu aimerais corriger ?

**Comment by yaf** [comment]
C'est un ticket du board Trello brouillon. Je vais avoir du mal à ressortir les « raisons ».

Ce que je vois de mon côté, c'est qu'il y a des plages d'ouvertures sur lesquelles ont été placé des lieux arbitrairement sans doute.

C'est peut-être pas bloquant, mais ça crée de l'incohérence dans l'application. Et si on commence à utiliser une couleur pour certains lieux (pour indiquer aux agents où ils vont tel jour), je crains que ça ajoute du bazar.

Je ne suis pas sûr de voir la complexité ? C'est plus compliqué que de rendre obligatoire tout le temps ou libre tout le temps le champ, et je pense que nous avons déjà des schémas un peu similaire non (un attribut obligatoire en fonction d'un contexte) ?

**Comment by adipasquale** [comment]
rendre le lieu optionnel casse la recherche côté usager @yaf c'est de là d'où vient la complexité, il faudrait permettre aux usagers de réserver des motifs hors-lieux. Je ne pense pas que le rapport coût impact de ce ticket justifie de s'y pencher pour l'instant

**Comment by yaf** [comment]
Je vais fermer ce ticket. Ce n'est pas assez clair, et la demande semble perdu (le pourquoi ?)
