### ISSUE TITLE
Réduire la liste de motif dans le formulaire de plage d'ouverture avec un filtre par service 

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1056]
ajout d'un champ "service" => par défaut le service renseigné est le service auquel j'appartiens, excepté pour les secrétaires, laisser le champ libre

**Comment by adipasquale** [comment]
pour l'instant c'est le scope `available_motifs_for_organisation_and_agent` qui est utilisé dans les formulaires de PO https://github.com/betagouv/rdv-solidarites.fr/blame/master/app/models/motif.rb/#L37

A mon avis ce n'est pas correct pour les admins. ce n'est pas parce que je suis admin que je peux me creer des POs pour des motifs hors de mon service. il faudrait valider que ce n'est pas le cas en prod, et si ca l'est demander pourquoi. ensuite changer ca pour que tous les agents soient a la meme enseigne : je peux seulement creer des motifs dans le service auquel j'appartiens. 

la regle est quasiment la meme pour les secretaires : des motifs de n'importe quel service SI ce motif est marqué realisable par le secretariat

**Comment by yaf** [comment]
Cette issue est inactive depuis un moment alors que nous allons en avoir besoin si nous ouvrons les services dans une organisation.

Je commente pour voir si ça lui donne une « activité ». Je l'ajoute également dans la colonne TODO.

**Comment by adipasquale** [comment]
@yaf 
- je ne pense pas que ce soit une `good-first-issue` car le sujet est en fait un poil complexe, il faut bien comprendre le systeme de permissions de l'appli cf mon commentaire precedent
- je renommerais bien ce ticket en qqch comme `réparer la liste de motifs sélectionnables dans le formulaire de plage d'ouverture` et la description en conséquence. Le fait de rajouter un filtre par service ne sera utile que quand les agents pourront appartenir à plusieurs services, c'est a ce moment qu'il faudra l'introduire et pour ces agents uniquement. Ca n'empeche qu'il faut corriger la liste actuellement affichée, donc ce ticket reste pertinent en amont

**Comment by yaf** [comment]
Je crois que ce ticket n'est pas prêt à être fait finalement.

Et quand je vois ce dont nous avons parlé durant le [point équipe du 23 avril](https://forum.rdv-solidarites.fr/t/point-de-situation-de-lequipe-au-23-avril-2021/235), je me dis qu'il est nécessaire de ne pas se précipiter à faire n'importe quoi.
