### ISSUE TITLE
Home page - Intégrer les logos des départements

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1057]
Mettre en avant le Consortium : la démarche et les partenaires

**Comment by adipasquale** [comment]
ticket non actionnable sans les fichiers des logos, est-ce qu'on les a déjà ? même une partie seulement

**Comment by yaf** [comment]
Je ne pense pas. J'ai reporté ce ticket ici pendant la migration. Je vais le fermer, ça n'a pas beaucoup d'intérêt, et si c'est important, ça refera surface plus tard :smile:
