### ISSUE TITLE
Envoyer un email avec .ics à l'agent pour chaque RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1059]
Pour le 77, aujourd'hui, le professionnel MDS ne reçoit une notification d'un rdv pris par l'usager uniquement si le rdv est pris à J-1. Peut-on envisager que le professionnel soit notifié en CCI à chaque rdv pour alimenter son agenda institutionnel (outlook) ?

Paramétrable au niveau d'une orga ou d'un département

**Comment by adipasquale** [comment]
Ça m'embête de rajouter encore un paramètre de configuration, surtout qu'à coup sur on va nous demander de le mettre à plein de niveau : département / orga / service / agent.
Mais je comprends le besoin. J'aurais tendance à dire qu'on ne met le paramètre qu'au niveau le plus bas = agent pour commencer. et opt-in 

Je crois que ce ticket est un peu prématuré en tout cas vu que pour l'instant il y a très peu de RDVs pris côté usagers.

**Comment by yaf** [comment]
Oui, c'est clairement pas prioritaire, et peut-être que ça pourrait passer à la trappe avec l'interconnexion ?

**Comment by yaf** [comment]
Je pense que ce ticket est en fait très lié à nos échanges sur les notifications avec fichier ICS. Une autre vois pour la synchronisation. Pour les départements dont la DSI n'a pas l'énergie, le temps ou les moyens de faire l'interconnexion par webhook.


https://forum.rdv-solidarites.fr/t/permettre-aux-agents-de-choisir-quels-mails-recevoir/29/2

**Comment by adipasquale** [comment]
Prévenir Irène du Var lorsque ce ticket sera fait, c'est bloquant pour le déploiement de leur côté, cette fonctionnalité est très demandée.

**Comment by HoulesBenoit** [comment]
Bonjour,

On comptait se jeter à l'eau, en attendant l'API d'invitation des usagers, sans reprendre le code du 62 car trop spécifique, mais si vous le faites d'ici peu, on se pose clairement la question de le réaliser.

J'ai vu que hier vous avez commencé à sizer la fonctionnalité, cela sous-entend que vous allez y travailler prochainement ?
Si vous avez d'ores et déjà de la visibilité, nous sommes preneur aussi d'information de votre part.

Merci d'avance.

Benoit Houles

**Comment by yaf** [comment]
Oui, nous pensons l'attaquer dans les semaines qui arrivent.

Nous n'avons pas encore fait en sorte d'afficher une estimation de temps, mais vous pouvez regarder le tableau projet pour avoir une idée. La colonne Todo est trié par ordre de priorité.

https://github.com/betagouv/rdv-solidarites.fr/projects/8?fullscreen=true

**Comment by yaf** [comment]
Après discussion avec @n-b nous nous disons que nous allons faire au plus simple : ajouter la configuration dans le profil agent. Chaque agent sera autonome pour activer ou désactiver l'envoie d'une notification email pour chaque création, modification, suppression de rendez-vous.

Attention, la suppression à la suppression sans annulation, et à l'annulation via le bouton et via le changement de statut.
