### ISSUE TITLE
Afficher le métier de l'agent dans les notifications usagers SMS et mail

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1060]
64 : L'usage du SMS est plus fort que l'email dans le social. Le SMS ne contient pas les documents à apporter au RDV. 

Proposition : à défaut de la liste des docs, faire apparaitre le type de pro avec qui il a RDV. Selon Christelle l'usager sait ce qu'il doit apporter en fonction du pro. 

Pour le 77, ce besoin émerge également. Certains usagers connus dans deux services doivent pouvoir faire la différence entre un rdv avec l'un et l'autre grâce soit au professionnel identifié, le service ou le motif du rdv.

Si on suppose que le SMS est lu sur un smartphone, nous pourrions, en plus de préciser le type de professionnel avec qui le rendez-vous à lieu, nous pourrions aussi proposer une url raccourci qui abouti sur une page « publique » d'information sur les document à apporter dans le cas d'un rendez-vous de tel motif avec tel pro ?

**Comment by adipasquale** [comment]
intéressant ! 

- c'est quoi le "type de professionnel" ? c'est le service de l'agent ? attention car à l'avenir on aura probablement des agents multi-services
- faire une page publique d'infos c'est intéressant aussi mais ça me paraît un peu overkill, et ça rajoute encore de la complexité dans la config des motifs, il faudrait que les agents rédigent une page par motif. Je pense que tout est déjà décrit dans le bloc "consignes post prise de rdv". Le problème devient alors que les usagers n'arrivent pas à accéder à leur RDV depuis le SMS - pour des sujets de register/sign up compliqué. On peut prendre deux pistes : améliorer notre parcours d'inscription/connexion et/ou rajouter un lien auto-signé read-only vers un rdvs#show dans le SMS

**Comment by yaf** [comment]
> Le problème devient alors que les usagers n'arrivent pas à accéder à leur RDV depuis le SMS - pour des sujets de register/sign up compliqué. On peut prendre deux pistes : améliorer notre parcours d'inscription/connexion et/ou rajouter un lien auto-signé read-only vers un rdvs#show dans le SMS

Oui, effectivement, c'est une autre possibilité qui rejoint les échanges que nous avions eus sur la facilitation de l'annulation de rendez-vous (voir la demande de déplacement).

**Comment by adipasquale** [comment]
je pense que ce ticket mérite encore d'être discuté côté forum pour valider quelle info on veut afficher : 

1. le(s) service(s) du RDV 
2. une nouvelle donnée : le métier de l'agent

je suis quasiment sûr que 1. est déjà affiché dans les SMS. 

si c'est 2 il faut demander à tous les départements si ça leur conviendrait et peut-être définir la liste des métiers existants, ou alors la rendre éditable par les départements individuellement ou encore un champ libre pour l'agent ? Il faudra limiter le nombre de caractères pour les SMS.

**Comment by yaf** [comment]
Oui, c'est 2, et tu as raison, il faut construire une liste et évoquer le coup de la longueur :)

https://forum.rdv-solidarites.fr/t/liste-des-metiers-agents-a-destination-des-sms-et-autres-notifications/131
