### ISSUE TITLE
Indiquer dans les SMS quel proche est concerné par le RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1062]
## Problème

Si j'ai plusieurs enfants je ne sais pas lequel amener à la consultation. 

(enfant ou proche)

## Proposition

Si je suis le responsable de la personne qui a rendez-vous, précisez le nom complet de la personne qui a rendez-vous dans la notification.

Une discussion lié a ce sujet https://forum.rdv-solidarites.fr/t/sms-faire-apparaitre-le-prenom-de-lenfant/196

**Comment by n-b** [comment]
@yaf cette issue et #1402 sont un peu liées, non?
