### ISSUE TITLE
Prendre en compte les navigateurs sans color picker

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1065]
## Problème

Certaines personnes admin utilise un navigateur n'affichant pas de color picker. Ces personnes saississent une couleur dans le texte.

## Solutions

Nous pourrions
- soit prendre en compte ces textes et les transformer en hexa pour pouvoir faire le calcul de constrate.
- soit proposer (comme initiallement imaginer) une palette de couleur (à la trello) permettant de garantir le constrate.

La deuxième option avait été écarté car nécessitant une modification de l'interface moins trivial que le calcul de contraste. Ceci étant, vue la situation, ça serait peut-être la meilleure option.

**Comment by adipasquale** [comment]
je pense que proposer une palette de couleurs est la bonne piste. Cette palette peut initialement venir en complément du champ libre pour ceux qui ne sont pas prêts à changer leurs couleurs existantes. Elle sera alors optionnelle, et permettra de donner une solution aux personnes sur des très vieux navigateurs sans color picker

**Comment by adipasquale** [comment]
on peut fermer cette issue non @yaf ?

**Comment by yaf** [comment]
Eh bien je ne sais pas trop. Je n'ai pas encore échangé avec Christelle à propos de ces agents qui ont utilisé des navigateurs sans color picker...
Tu as eu des nouvelles ? Vous avez (toi ou Radia) échangé avec l'une d'entre elle la semaine dernière il me semble, ça a donné quoi ?

**Comment by yaf** [comment]
Je ferme
