### ISSUE TITLE
Suivi de notifications

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1067]
Les notifications sont des éléments important dans RDV-Solidarités. Nous n'avons par contre aucune mesure du nombre de SMS envoyé par organisation, par rendez-vous, par personne, par service.

Avec la prise en charge des SMS par les départements, il sera peut-être intéressant de pouvoir dire si ça a raté de notre côté ou du côté du fournisseur. Un compteur serait un bon début. Peut-être faudrait-il même un peu plus de suivi, de statistique.

**Comment by adipasquale** [comment]
@yaf nous avons déjà mis en place des tags par organisation sur SIB : chaque SMS envoyé est estampillé avec l'ID de l'orga. ça permet aussi de grouper par département. mais pas par personne ni par service. 

![Screenshot 2021-01-05 at 09 05 26](https://user-images.githubusercontent.com/883348/103621301-4a19d500-4f35-11eb-8d01-7a982d42c984.png)

Mais effectivement je te rejoins sur le fait qu'il va falloir qu'on soit plus réactifs sur "notre partie" == la taskqueue. Je pense que ça va nous forcer à prioriser le passage à Sidekiq parce qu'aujourd'hui dur d'avoir des stats ou même de bien comprendre le fonctionnement des retries.

**Comment by yaf** [comment]
Tu as raison.

Et peut-être que la question ici c'est peut-être de savoir si nous déclinons toutes responsabilités sur l'envoie des SMS « nous, c'est bon, on a appelé l'API, si le message est pas arrivé, c'est forcément le fournisseur qui merde ». Ou bien si nous maintenons un état statistique des messages (tant de notification envoyé à telles dates, ....).

Je n’ai pas de réponse préféré. J'ai l'impression que ça serait bien d'avoir un outil de notre côté pour pouvoir déboguer notre partie du tuyau (ou permettre aux « agents-admin » de le faire en autonomie).

**Comment by adipasquale** [comment]
je partage que ca serait cool dans l'idéal d'avoir un outil pour que les agents admin puissent avoir du detail en autonomie, mais je n'ai pas le sentiment que ca soit un besoin exprimé fortement jusqu'à maintenant ? j'ai le sentiment que c'est de la cerise sur le gâteau pour plus tard et que jusqu'à maintenant les quelques fois où on nous a demandé de vérifier ou émis des doutes sur l'émission des SMS le debug dans SIB nous a largement suffi.

Qu'en penses-tu @yaf ?

**Comment by yaf** [comment]
Oui, c'est possible. C'est pas une priorité pour moi ce ticket. Ça le deviendra peut-être au moment du report de la gestion des SMS aux SI des départements.

**Comment by adipasquale** [comment]
je pense qu'on peut en effet fermer ce ticket tant que le sujet ne devient pas prioritaire, on ira le rechercher à ce moment
