### ISSUE TITLE
empêcher le remplissage du end_day pour les absences récurrentes

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1075]
## Problème 

il y a deux champs "date de fin" dans le formulaire des absences recurrentes. On ne comprend pas trop le sens.

## Detail 

- les absences et les plages d'ouvertures partagent le concern de recurrence
- le concern de recurrence peut inclure une date de fin de la recurrence, stockée en json dans `recurrence[:until]` 
- les absences ont un `end_day` mais pas les plages d'ouvertures
- une absence peut donc avoir a la fois un `recurrence[:until]` et un `end_day`. ca signifierait, j'imagine, une absence s'etalant sur plus d'un jour et se repetant.
- je pense que c'est tres rare et tres compliqué comme cas. en prod je compte trois cas, voir plus bas
- en prod `Absence.where.not(recurrence: nil).where("absences.end_day != absences.first_day").count  == 3`

## Solution 

- Empecher le remplissage du end_day pour les absences recurrentes, ne permettre des absences recurrentes que lorsqu'elles s'etalent sur un seul jour

**Comment by yaf** [comment]
Peut-être pourrions-nous « masquer » la date de fin d'absence. Ça harmoniserait avec les plages d'ouverture et réduirais la confusion.

**Comment by yaf** [comment]
Il y a 8 absences dans le cas maintenant

```
irb(main):002:0> Absence.where.not(recurrence: nil).where("absences.end_day != absences.first_day").count
=> 8
```

**Comment by yaf** [comment]
Et pour avoir un ordre de grandeur:

```
irb(main):003:0> Absence.where.not(recurrence: nil).count
=> 540
irb(main):004:0> Absence.count
=> 26_353
```

**Comment by yaf** [comment]
C'est peut-être à discuter sur le forum ?

**Comment by adipasquale** [comment]
je n'ai pas compris tes propositions ni ton analyse @yaf ça serait probablement plus efficace qu'on en parle de vive voix
