### ISSUE TITLE
[stats][departement] exporter des statistiques par département

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1077]
url : https://demo.rdv-solidarites.fr/stats/12

## Choix d'implémentation pour la performances

Attention au performance, c'est particulièrement long, puisqu'il y a beaucoup de donner.
- Peut-être que le contenu de ce fichier pourrais être envoyé par email une fois généré ?
- Une autre option serais de générer les stats au fur et à mesure, pour qu'au moment de récupérer le fichier, le contenu soit déjà prêt.

- [ ] remplacer le lien par "Télécharger un export de ces statistiques mois par mois"
- [ ] filtrer l'export sur le departement sélectionné
- [ ] Améliorer les perfs (lenteur) (cf https://www.skylight.io/app/applications/RgR7i58P67xN/recent/6h/endpoints/StatsController%23rdvs?responseType=xls)

Vaea Castaing: Besoin de disposer des stat du département en filtrant les organisations, mais sans faire l'export depuis chaque organisation

Yannick: Le commentaire d'Adrien ci-dessous n'est plus d'actualité suite à la modification profonde de ce ticket.

Adrien: @camillegarrigue1 @yannickfrancois5 a développé cette fonctionnalité testable sur https://demo-rdv-solidarites-pr718.osc-fr1.scalingo.io/ avec martine@demo.rdv-solidarites.fr : 123456

ca marche bien mais je ne crois pas que ca reponde au besoin de pouvoir faire des stats par departement. la ce que ca fait c'est que ca rajoute un export par organisation, donc a une echelle plus basse que departement. si tu veux comparer entre departements, il faudra que tu exportes depuis chacune des organisations de chacun des departements et que tu regroupes les exports.

est-ce que c'etait bien ce que tu souhaitais ? si c'est une premiere etape utile je la deploie telle quelle, et on pourra eventuellement iterer pour faire des exports a des echelles (departement entier puis tous les departements d'un coup).

**Comment by adipasquale** [comment]
aussi demandée par le Var, il faudrait dire à Irène et Saïd lorsqu'on a déployé ça

**Comment by yaf** [comment]
J'imagine que maintenant, avec la notion de territoire, c'est un peu plus facile à faire...

**Comment by yaf** [comment]
Il y a de la demande sur le sujet https://forum.rdv-solidarites.fr/t/statistiques-acceder-a-un-export-excel-par-departement/164/5

**Comment by yaf** [comment]
Il y a un hic malgré tout.

Ce n'est pas simplement une duplication des statistiques par organisation à déplacer au niveau territoire. Il faut revoir l'ensemble des pages et contrôleurs pour remplacer l'organisation par le territoire.

Ce ticket mérite de repasser en .M, soumis au vote.

Il serait peut-être intéressant aussi d'envisager de faire les statistiques dans le metabase pour l'occasion.

**Comment by yaf** [comment]
Les statistiques vont petit à petit être déplacé vers Metabase. Je ferme ce ticket.
