### ISSUE TITLE
Modifier un RDV « sur place »

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1079]
À la façon de faire des agents_référents dans la ficher usager, nous pourrions proposer de modifier le RDV dans le bloc de la fiche RDV.

Adrien: je vote pour repousser cette carte car a mon avis c'est compliqué a faire bien :
- design pas simple
- gestion des erreurs de validation nettement plus compliquées
- casse l'harmonie du site en general qui ne propose jamais ca

(mais j'approuve que ce serait une UX plus agreable)

**Comment by adipasquale** [comment]
ping @yaf pour archiver ce ticket qui n'est à mon avis pas prioritaire et difficile à attaquer car il cassera l'harmonie de l'UI

**Comment by yaf** [comment]
Ok. Est-ce que tu penses qu'il faudrait passer partout en une fois pour basculer sur ce mode d'édition ? Ou bien tu préfères qu'on ne prenne pas cette voie ? C'était dans les maquettes d'Anne-Sophie. Je n'ai pas forcément un avis très arrêté sur le sujet, si ce n'est que ce n'est clairement pas le plus important actuellement :)

**Comment by adipasquale** [comment]
Je pense que vu les dimensions de l'équipe et les ambitions du produit en termes de fonctionnalités, il faut tendre vers l'app web la plus simple à développer et c'est à mon avis l'app rails à l'ancienne avec peu d'AJAX et des formulaires HTTP classiques oui.

C'est extremement discutable comme opinion :) 

Pour ce sujet précis de formulaires inline je pense que ça casserait l'UI de le faire à un seul endroit et que ça serait un gros chantier à faible impact de le faire partout

**Comment by yaf** [comment]
Je suis assez d'accord avec toi, et j'apprécie tes arguments. J'avais envie de vérifier car tu as souvent été un grand défenseur des maquettes réalisées par Anne-Sophie. Et bien que j'apprécie ces maquettes, je pense comme toi que nous devons revoir un peu nos priorités à la vue de la taille de l'équipe.

Dans ce cas, il y a un ticket pour « revoir » la mise à jour d'agent référent :)

Je ferme, et pour l'agent référent, on verra bien.
