### ISSUE TITLE
alerter en cas de chevauchement avec un autre RDV dans le tunnel RDV agent

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1120]
De la même manière que nous avons commencé à mettre en place des alertes sur des collisions de plage d'ouverture, de rendez-vous sur d'autres plages d'ouvertures, nous pourrions ajouter une alerte sur un rendez-vous qui tombent sur un autre rendez-vous.

**Comment by adipasquale** [comment]
petite note @yaf  : il n'y a pour l'instant pas d'alertes sur "des collisions avec des rdvs sur d'autres plages d'ouvertures" . il y a uniquement : 
- des alertes si conflit avec une PO existante car sur un autre lieu
- des alertes si un RDV finit peu avant, pour prevenir que ca va laisser un trou

**Comment by yaf** [comment]
@adipasquale, l'idée est d'ajouter une alerte pour un chevauchement sur
- un rendez-vous existant dans la même orga
- un rendez-vous existant dans une autre orga
pour un même agent.

C'est bien ça ?
