### ISSUE TITLE
Créer un modèle pour les entités juridiques / départements

### ISSUE THREAD

**Issue by guillett** [betagouv/rdv-solidarites.fr#1124]
Aujourd'hui, les MDS/organisations sont regroupées par département à partir du champs texte `department` qui contient le code du département (92 pour les Hauts-de-Seine par exemple).

Je pense qu'il serait bien d'avoir une table pour regrouper les organisations et y ajouter certaines informations
- sectorisation (hack actuel)
- données de contact (hard code actuel)
- données RGPD (infos de contact des délégué.e.s à la protection des données personnelles)
- webhooks de notifications
- demain, la configuration pour l'envoi de SMS
-  et potentiellement d'autres choses notamment :
    - des motifs accessibles dans tout le département (pour éviter les resaisies par organisation)

**Comment by adipasquale** [comment]
- creer un objet départements
- rattacher les agents admin des départements
- corriger les policies en fonction

**Comment by yaf** [comment]
Fermé avec la PR #1215 
closed by #1215
