### ISSUE TITLE
Ajouter un numéro de téléphone pour les lieux

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1146]
https://forum.rdv-solidarites.fr/t/numeros-de-telephone-des-differents-lieux/119/2

Les lieux sont, pour la plupart du temps, des lieux fixe où les équipes d'agents travaillent quotidiennement. Pour les annulation, report et demande d'information, il serait plus efficace d'utiliser le numéro de téléphone d'un lieu.

La solution envisagée serait donc de
- [x] ajouter un numéro de téléphone à un lieu
- [x] afficher ce numéro de téléphone dans la notification quand il est présent, affiche le numéro de téléphone de l'organisation sinon
- [x] afficher ce numéro de téléphone dans la fiche du RDV coté usager

**Comment by adipasquale** [comment]
il faudrait en profiter pour améliorer la présentation côté agent admin de où est-ce que ce numéro sera affiché, et qu'il faut que le standard téléphonique correspondant ait accès à l'orga dans rdv-solidarités
