### ISSUE TITLE
Garder une trace de la date et heure de dernière connexion d'un usager

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1156]
Afin de savoir depuis combien de temps un usager ne c'est pas connecté, nous avons besoin de garder une trace de son dernier passage.

> en effet, enfin on pourrait aussi imaginer :
> `last_activity = max(last_rdv_date, user_updated_at)`
> et avoir une route `touch` qui bump le `user_updated_at` vers laquelle rediriger les users qui souhaitent conserver leur compte
> et avoir une route
> -- @adipasquale 

Mais sinon, on peut ajouter un champ `timestamp` qui serait mis à jour à chaque connexion.

**Comment by adipasquale** [comment]
`users.last_sign_in_at` ou `users.last_session_at` me parait plus parlant, faudrait regarder les wiki devise il y a probablement qqch
