### ISSUE TITLE
Pouvoir modifier la couleur de fond des plages d'ouverture

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1160]
À la manière des motifs, il serait intéressant de pouvoir modifier la couleur de fond des plages d'ouvertures.

Par défaut, elles resteraient couleur bleue ciel (pour les organisations qui ne souhaite pas les changer). 
Pour les départements qui le souhaitent, cette couleur permettrait de signaler un lieu différent, ou un type d'activité.

Voir l'échange sur le forum : https://forum.rdv-solidarites.fr/t/couleur-de-fond-des-plages-douverture/116/9

**Comment by adipasquale** [comment]
je doute que ce soit une bonne idée vue la tête des agendas aujourd'hui et le nombre d'infos différentes qu'on y affiche déjà

**Comment by adipasquale** [comment]
ça ne paraît pas être le sujet le plus urgent à faire et ce n'est pas super satisfaisant

**Comment by yaf** [comment]
ça serait intéressant d'en parler sur le forum avec la ou les référentes impacté dans ce cas.

**Comment by yaf** [comment]
Je ferme ce ticket pour le moment.
