### ISSUE TITLE
Supprimer les blancs avant et après les noms et prénoms

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1161]
J'ai découvert un usager avec un espace ajouté à la fin de son nom. Cela ne m'a pas aidé à le retrouver.

Nous pourrions ajouter un nettoyage de ces espaces (avant et après) dans les nom et prénom des usagers et des agents.

**Comment by adipasquale** [comment]
bien vu ! par contre la manière la plus simple et ruby-friendly de faire ça me semble être un before_save. est-ce que tu es opposé à l'introduction de nouveaux callbacks ? ou bien est-ce que tu as d'autres pistes ?

**Comment by adipasquale** [comment]
il faut peut etre une migraiton pour cleaner les existants, tester sur la prod

**Comment by adipasquale** [comment]
soit before_save soit juste validation plus cleaner en amont

**Comment by yaf** [comment]
Je ne suis pas à l'aise à l'idée d'ajotuer un callback. Je pencherais pour le nettoyage des paramètres quand il arrive. Via un service ou bien un form_models si ça rentre dans son rôle ?

**Comment by adipasquale** [comment]
ça me va si on fait nettoyage dans le controlleur (ou service) + validation dans le modèle + migration
