### ISSUE TITLE
Amélioration du tableau des motifs

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1174]
<img width="1024" alt="Screenshot 2021-02-08 at 19 11 51" src="https://user-images.githubusercontent.com/883348/107263033-8e6f2800-6a41-11eb-94e3-b9d0a45423d4.png">

**Comment by yaf** [comment]
C'était voulu. Mais j'aurais pu pousser un peu plus loin.

Le souci, c'est que si le résultat du filtre ou de la recherche n'a aucun motif correspondant, tu n'as plus accès aux filtres ni à la recherche, ni au lien « re-initialiser ».
 
L'objectif serait donc de faire la distinction entre
- je n'ai aucun motif
- aucun motif ne correspond à ma recherche ou mon filtre

Nous pouvons sans doute y arriver avec un compteur du nombre total de motifs. Ce compteur pourrais même être affiché quelque part en haut de page, dans le titre ?

**Comment by adipasquale** [comment]
ah bonne remarque je n'avais pas pensé à ça. L'état vide fait quand même assez bizarre là donc ça serait cool de réparer, mais pas du tout urgent.

Je ne sais pas si ça implique un compteur du nombre total de motifs nécessairement, on pourrait aussi mettre une condition dans le partial genre : 

``` 
- if @filters.any? || @motifs.any?
  - form_for ...
      - table ...
```

**Comment by adipasquale** [comment]
en passant, reparer le centrage du texte versus du bouton en dessous, ca fait mal aux yeux !

**Comment by yaf** [comment]
Je suis ok pour le bouton.

Par contre, après avoir essayé, je trouve que c'est vraiment une drôle d'expérience utilisateur d'avoir des éléments de filtre, un entête de tableau, et, parce que je filtre sur un motif inexistant, je n'ai plus rien à par un lien de création et un lien pour « réinitialiser ».

Quand on regarde sur la page agent (qui propose un tableau sans filtre et une zone de recherche), nous laissons apparaitre l'entête de tableau quand il n'y a rien.

![Capture d’écran de 2021-03-21 18-42-48](https://user-images.githubusercontent.com/42057/111915201-58c45280-8a75-11eb-84f7-f02356c469e2.png)
