### ISSUE TITLE
Agenda agents inter-organisations

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1185]
Un agent travaillant sur plusieurs organisations va devoir jongler entre les organisations pour avoir une idée de son planning.

L'idée, pour commencer à simplifier, est de modifier la vue agenda existant pour y afficher les items des autres orgas.

Attention à l'effet "sapin de noël"; il y a déjà beaucoup de couleurs et codes dans l'agenda, on s'apprête à rajouter un nouveau.

Il faut aussi commencer par rendre non-cliquables les items hors-orga courante.

**Comment by adipasquale** [comment]
bien tester sur les données de prod pour des cas réels pour voir avec du volume

**Comment by yaf** [comment]
Il y a un souci de performance.

**Comment by yaf** [comment]
clos via  PR #1396
