### ISSUE TITLE
Limiter la création d'une organisation par un agent non authentifié

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1192]
La page de création d'une organisation est accessible à qui veut. Aucune limitation pour le moment. La validation est faite par l'équipe.

Il y a plusieurs départements, déjà existant, dans lesquels nous avons eu des cas de personnes (du département ou pas) voulant créer une organisation par ce biais. 

L'idée serait de ne pas pouvoir créer d'organisation nouvelle par ce chemin si le département demandé à déjà au moins une organisation (et donc au moins un agent). 

Reste à savoir si nous proposons un email de contact autre que `contact@rdv-soldiarites.fr` pour en savoir plus ? Est-ce que nous pourrions mettre l'email de la personne référente du département ?
Ce dernier point pourrais être discuté sur le forum, ou bien non traité pour le moment. Il y a une page `contact` qui pourrait suffire.

**Comment by adipasquale** [comment]
je pense que cette remarque est valide en prod où dans quasiment 100% des cas on voudra que ce soit le.la référent.e qui fasse les créations d'organisations.

Par contre en démo je pense que c'est pas mal de laisser la possibilité aux agents curieux de tester des configurations. je ne sais pas si c'est un vrai cas d'usage ceci dit, peut-être que 100% des tests en démo par des agents dans des départements existants sont des erreurs

**Comment by adipasquale** [comment]
ok mon commentaire va trop loin, on peut ignorer ce cas
