### ISSUE TITLE
refacto duplicate user warning

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1214]
https://github.com/betagouv/rdv-solidarites.fr/blob/master/app/models/user.rb/#L38

- ce warning de ne devrait pas etre dans le modele mais dans un form model specifique a l'admin
- refacto ce systeme de warning maison par la gem qu'on utilise maintenant pour les warnings du tunnel RDV admin pour harmoniser

**Comment by yaf** [comment]
Je crois que ça m'aiderait si tu pouvais préciser « ce » warning :)

**Comment by adipasquale** [comment]
en effet ! j'ai rajouté un lien vers la validation en question
