### ISSUE TITLE
External calls to the user API are rejected due to CORS issue

### ISSUE THREAD

**Issue by qblanc** [betagouv/rdv-solidarites.fr#1236]

**Comment by adipasquale** [comment]
hello et bienvenue @qblanc ! tu peux préciser comment reproduire ? 
et on a tendance à parler français sur ce repo, mais c'est comme tu le sens :)

**Comment by qblanc** [comment]
Hello !
Quelle que soit la requête que je lance, même pour une requête d'authentification avec des credentials corrects, je récupère des 403. Je le teste via analyse-flux-insertion en local, depuis la feature que je dev (pour l'instant en local). 
A priori c'est lié au fait de faire les requêtes via navigateur, donc je ne sais pas si tu peux le reproduire via Postman.

**Comment by adipasquale** [comment]
merci pour les détails

> faire les requêtes via navigateur

c'est a dire ? comment fais tu tes requetes ? tu utilises un outil genre httpie/curl ou bien une interface gui genre postman ?

**Comment by qblanc** [comment]
Via un form construit pour l'occasion sur analyse-flux-insertion (pas encore déployé ni mergé). Dans l'idéal pour le répliquer il faudrait que tu pull la branche dédiée sur analyse-flux-insertion en local, donc pas hyper pratique.

**Comment by adipasquale** [comment]
ok bien compris 👌 en effet aujourd'hui ce n'était pas prévu pour intéragir depuis d'autres interfaces web donc je comprends mieux que ça puisse planter maintenant. On va corriger ça. merci !

**Comment by yaf** [comment]
J'ai l'impression que ce ticket est à fermer. Est-ce que c'est ok @qblanc  ?
