### ISSUE TITLE
Investiguer le bouton "prochain creneau" n'apparait pas toujours

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1239]
rapport de bug d'elise forget du 15/03/2021 : 

> Lorsque l’on utilise la fonction « trouver un créneau », le bouton qui emmène automatiquement vers le prochain créneau dispo n’apparaît pas systématiquement. Il me semble que Christelle Cufay avait déjà fait remonté ça, je le constate à mon tour aujourd’hui.

**Comment by n-b** [comment]
Je pensais que ça serait lié à #1382 et corrigé dans #1390, mais en fait on dirait que non: les plages d’ouvertures “cached” ne sont pas dépendantes de la semaine affichée. J’imaginais que seules les plages d’ouvertures déjà existantes à la semaine affichée serait présentes.

**Comment by n-b** [comment]
Impossible à reproduire aujourd’hui, y compris par les référentes concernées : je suppose que c’est dans des conditions bien spécifiques, on verra bien si ça remonte. Je ferme en attendant.
