### ISSUE TITLE
Changer les descriptions des "types de RDV" lors de la création d'un motif

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-solidarites.fr#1243]
Il est inscrit : 
**Sur place** "L'usager sera notifié que le RDV aura lieu à l'adresse remplie dans son profil"
**A domicile** "Le RDV aura lieu au lieu sélectionné (MDS...)"

Et cela semble l'inverse lorsqu'on donne un rdv à un usager (confirmé par Thomas)

**Comment by adipasquale** [comment]
bienvenue @ClaireCasu ! Merci pour ce rapport d'un joli bug on va corriger ca rapidement
