### ISSUE TITLE
corriger ICS suppression plage ouverture pour outlook 64

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#1275]
>D'autre part, j'ai supprimé des plages d'ouverture.
> J'ai bien reçu le mail.
> Mais lorsuqe je clique sur supprimer une fois que j'ai ouvert le fichier ics, rien ne se passe : l'évènement ne disparaît pas, il reste intégré.

**Comment by adipasquale** [comment]
fonctionne bien sur Mac Os Calendar

**Comment by yaf** [comment]
Ça fonctionnait bien sur google calendar quand j'avais testé.

**Comment by adipasquale** [comment]
<img width="650" alt="Screenshot 2021-03-25 at 10 19 10" src="https://user-images.githubusercontent.com/883348/112450171-679c5500-8d54-11eb-8f1a-2af8f6fd7adb.png">

ca semble fonctionner sur mon environnement W10+Outlook2013
