### ISSUE TITLE
Inviter un agent d'un autre service ne fonctionne pas, silencieusement

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1281]
_Suite à une discussion sur Slack avec Élodie._

Si j'ai un agent sur une organisation dans un service donné ;
Lorsque je l'invite sur une autre organisation dans un autre service ;
Il est invité dans cette dernière organisation, mais en restant sur son service initial, sans rien me dire de spécial.

_il est possible aussi que s'il était agent et que je souhaite l'inviter en admin, ça ne fonctionne pas non plus. Je n'ai pas pris le temps de vérifié_

**Comment by adipasquale** [comment]
👍 en effet il y a une belle incohérence dans l'UX de ce cas : j'invite un agent pré-existant dans une autre orga.

Il faudrait probablement revoir un peu plus profondément l'interface d'invitation d'agent : 
- on pourrait scinder les formulaires "1. inviter un agent n'ayant pas encore de compte sur RDV-Solidarités" et "2. inviter un agent ayant déja un compte dans une autre orga"
- dans le formulaire 1. si tu mets une adresse email déjà utilisée, on te met une erreur explicite : cet agent existe déjà
- dans le formulaire 2. on te demande uniquement l'adresse email de l'agent existant + le rôle que tu souhaites lui donner dans cette nouvelle orga (les rôles sont indépendants par orga mtn @yaf) mais pas le service

**Comment by yaf** [comment]
Il est possible que ce ticket soit « réparé » via le #1325 . Je le laisse en priorité basse en attendant.
