### ISSUE TITLE
Ajouter un linter Slim

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1288]
Afin de partager une façon d'organiser nos vues Slim ;

- [ ] installer le linter Slim
- [x] l'ajouter à l'intégration continue

**Comment by n-b** [comment]
Ahah, j’avais justement noté ça dans les choses à proposer. Peut-être que pour simplifier la transition, il faudrait ne passer rubocop que sur les fichiers (ou les lignes) modifiées dans une PR.
Ou alors, on fait une grosse passe de refacto, mais c’est un peu rébarbatif, et je ne sais pas trop quel quantité de fixes rubocop peut faire automatiquement.

Pour slim spécifiquement, j’ai l’impression que [slim-lint](https://github.com/sds/slim-lint) ne gère de toute façon pas la correction automatique. 🤷

**Comment by yaf** [comment]
On peut imaginer que la PR qui introduit ces outils apporte beaucoup de changement pour la mise en conformité. À moins qu'on puisse faire, comme avec rubocop, un fichier `_todo` avec les exceptions qui permettent de ne pas tout corriger d'un coup. :thinking:
