### ISSUE TITLE
Affecter un agent à plusieurs services

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1300]
Suite à plusieurs discussions, la meilleure solution pour permettre à des agents d'intervenir sur plusieurs services, c'est de pouvoir les affecter à plusieurs services.

[Discussion sur le forum](https://forum.rdv-solidarites.fr/t/agents-multi-services-nouvelle-proposition-pouvoir-affecter-un-agent-a-plusieurs-services/219)

- La relation entre les agents et les services passera de 1-à-plusieurs à plusieurs-pour-plusieurs.
- modifier l'écran des agents
 
l’affectation à un service se ferait avec une case a coché dans le formulaire agent. Les cases ne pourront pas être décochées si l’agent a eu un rendez-vous, une plage d’ouverture pour un motif de ce service.

Vérifier les accès ouvert et les policies.

**Comment by adipasquale** [comment]
je pense que c'est plutot `L` @yaf !

**Comment by yaf** [comment]
Oui, effectivement :sweat_smile:

**Comment by yaf** [comment]
Nous allons finalement opter pour une autre approche.

voir https://forum.rdv-solidarites.fr/t/agents-multi-services-nouvelle-proposition-pouvoir-affecter-un-agent-a-plusieurs-services/219/6

Je ferme ce ticket et la PR qui va avec.
