### ISSUE TITLE
Rapatrier les pages CGU, Conditions générales d'utilisations et politique de confidentialité dans le service

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1302]
- Parce que maintenant ces pages en bougent plus beaucoup ;
- parce que dans la doc, ces pages font un peu tâche ;
- parce que le lien externe pour ce type de page, ça fait bizarre.

Nous pourrions rapatrier  les pages CGU, Conditions générales d'utilisations et politique de confidentialité dans l'application, puis supprimer les icônes de lien externe dans les pieds de page.

![Capture d’écran de 2021-04-06 11-40-46](https://user-images.githubusercontent.com/42057/113691650-f3a36a80-96cc-11eb-8789-1002db6bb742.png)

**Comment by adipasquale** [comment]
je ne suis pas super convaincu perso
- je trouve ça pratique de pouvoir éditer ces fichiers statiques sans passer par le code / un déploiement
- elles sont sur le même domaine (mais un sous domaine oui)
- si elles font tache dans la doc je les mettrais bien dans une catégorie "documents légaux"

**Comment by yaf** [comment]
Je note que tu n'es pas convaincu. Ceci étant, comme le dit @n-b , ça fait bizarre d'aller sur un autre site pour voir ces documents. De plus, ils ne changeront pas souvent.

Tout ça pour dire que oui, c'était pratique au moment de les mettre au point. Mais maintenant qu'ils ne bougent plus, pourquoi les garder à l'extérieur ? Je ne vois pas de raison convaincante de les laisser sur le gitbook.

**Comment by n-b** [comment]
Je n’ai pas d’avis fort sur le fait de les garder sur le gitbook ou les mettre dans le source; je crois par contre qu’on peut se passer de l’icône “lien externe” quand on va de l’app à la doc :)

**Comment by yaf** [comment]
Je crois que ça nettoierais quand même un peu la doc aussi de rapatrier ces pages.

**Comment by yaf** [comment]
Bon, je vais fermer cette issue. On verra plus tard.
