### ISSUE TITLE
Affiner l'accès aux rendez-vous de suivi

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1326]
Dans le cas de rendez-vous de suivi, l'application peut laisser croire qu'il y a un rendez-vous possible, alors qu'en fait ce n'est pas possible.

Pour reproduire :
- je suis usager avec un agent référent ;
- je sélectionne un rdv sur un motif de suivi sur lequel mon agent référent n'a pas de plage d'ouverture ;
- après authentification, je passe à l'affichage des plages par lieu, avec la promesse d'une disponibilité la semaine suivante ;

![Capture d’écran de 2021-04-12 16-18-29](https://user-images.githubusercontent.com/42057/114409461-c3ffd100-9baa-11eb-88c2-94af492c78b7.png)

![Capture d’écran de 2021-04-12 16-18-36](https://user-images.githubusercontent.com/42057/114409498-cd893900-9baa-11eb-987d-63488953fa5d.png)

![Capture d’écran de 2021-04-12 16-18-38](https://user-images.githubusercontent.com/42057/114409496-ccf0a280-9baa-11eb-9094-ddd3f0295c7f.png)

Pour ne pas afficher de fausse information et nourrir de faux espoir, ça serait nécessaire de vérifier si l'usager à bien un référent qui a des plages d'ouvertures ouvertes sur ce motif.

**Comment by n-b** [comment]
Alors je crois que c’est corrigé depuis #1390, et en fait c’était un peu le même bug. Dans [CreneauxSearchConcern](https://github.com/betagouv/rdv-solidarites.fr/blob/master/app/service_models/concerns/users/creneaux_search_concern.rb#L24), on passe bien les agents dans les options, et depuis 1390, c’est correctement pris en compte dans [FindAvailabilityService#perform](https://github.com/betagouv/rdv-solidarites.fr/blob/93b2c79b326e270a23f8a14b6d5b05af0119b072/app/services/find_availability_service.rb#L29)

Je vais essayer de me faire un petit schéma des différents services de créneaux, etc. Il y a peut-être un peu de simplification à faire sans tout refactorer.
