### ISSUE TITLE
Faire un script d'invitation d'usager en masse

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1330]
La plupart des départements déploient RDV-Solidarités sans ouvrir aux usagers. Pour le faire après coup, ça nécessite d'inviter tous les usagers. C'est long et fastidieux. 

Nous pourrions proposer un script qui invite tous les usagers d'un département, d'une organisation...

**Comment by n-b** [comment]
Ça peut aussi être un bouton d’action en masse dans la liste `admin/organisations/:id/users`.

**Comment by n-b** [comment]
(Ça tire aussi un chantier potentiel d’“action en masse” générique.)

**Comment by yaf** [comment]
En même temps, je pense que c'est très « one shot ». Je me dis qu'on peut supprimer cette Issue. On verra si le besoin revient.
