### ISSUE TITLE
Réponse API quand record non existant

### ISSUE THREAD

**Issue by qblanc** [betagouv/rdv-solidarites.fr#1336]
Quand la requête GET de user ou de invite est faite sur un id non-existant : cela renvoie parfois un json d'erreur, mais parfois un ActiveRecord::RecordNotFound.

**Comment by n-b** [comment]
@qblanc je déterre cette issue, pour voir si on y fait quelque chose : est-ce que c’était une erreur json ou une exception aléatoirement pour la même requête, ou bien est-ce que c’est deux scenarios distincts?

**Comment by qblanc** [comment]
@n-b côté Rdv-solidarités, cela renvoie ActiveRecord::RecordNotFound.
Celui qui a émis la requête reçoit une 404

**Comment by n-b** [comment]
Je suis en train de regarder un peu ça, on va faire en sorte que ça soit toujours 404 avec explication de l’erreur dans le json.
