### ISSUE TITLE
Investifation : Plus de créneau disponible en cas de chevauchement de plage d'ouverture

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1340]
Suite à un appel d'une coordinatrice de la somme ce matin. Il semble qu'il y ait un souci avec les créneaux disponibles quand des plages d'ouvertures se chevauchent.

Elles sont en pleine migration de : une organisation par secteur géographique à une organisation pour tout le département/territoire
Du coup, elles ont des plages d'ouvertures sur les orgas par secteur, qui se retrouve en chevauchement avec des plages d'ouverture sur l'orga destination. Dans cette situation, il semblerait qu'il n'y ait aucun créneau disponible (quand on fait la recherche de créneau coté usager et coté agent)

Et même après avoir supprimé la plage d'ouverture de l'orga de secteur (celle qui doit disparaitre), il n'y a apparemment toujours pas de créneau dispo.

**Comment by yaf** [comment]
L'organisation cible pour la somme est « (ID 149) TERRITOIRE SOMME-SANTERRE » et, il me semble, que la MDSI d'où on essaie de faire la migration est la « (ID 86) MDSI Albert ».

Je n'ai pas réussi à retrouver le nom de la coordinatrice que j'ai eu au téléphone ce matin. J'imagine que nous pourrions passer par les référentes pour avoir son contact si besoin. Je pourrais m'en occuper.

**Comment by n-b** [comment]
Mm, je reproduis pas à premier vue: j’ai deux plages d’ouvertures (aux mêmes horaires) pour la même agent sur deux organisations différentes, et je trouve bien des créneaux:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/139391/114709440-ddc92180-9d2c-11eb-8f8e-103b2813c31c.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/139391/114709447-defa4e80-9d2c-11eb-8a5a-ad172f0f5ce0.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/139391/114709453-e0c41200-9d2c-11eb-8e24-45e61822d4d0.png">

**Comment by n-b** [comment]
J’ai fouillé un peu plus, mais j’ai un peu de mal à retrouver mes petits; je soupçonne que c’est plutôt les organisations marquées avec “NE PLUS POSER DE RDV après le 30 juin” qui sont concernées, par exemple la 147, vers la 149. Ça ne m’étonnerait pas que ce soit plus un problème de configuration qu’un bug, mais ça recoupe un peu les questions de lisibilité et d’agenda multi-organisation, de toute façon.

**Comment by yaf** [comment]
Je vais essayer de reprendre contact avec la personne qui a appelé pour avoir plus d'information.

**Comment by yaf** [comment]
https://pad.incubateur.net/H7rfwU6TRsuVxIgozT39Rg?edit

**Comment by yaf** [comment]
Le problème venait du fait que l'agent en question avait posé une absence « pour se souvenir » de ne pas poser de rendez-vous sur cette « ancienne organisation » :)
