### ISSUE TITLE
Alerter l'agent au moment où il pose une absence

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1401]
Lorsqu'un agent pose une absence ;
s'il y a un rendez-vous sur la période ;
rien n'est fait.

À minima il serait intéressant d'utiliser le système d'avertissement que nous avons commencé à mettre en place à divers endroit de l'application.

Issue d'une discussion sur le forum https://forum.rdv-solidarites.fr/t/absence-et-suppression-de-rdv/204

**Comment by n-b** [comment]
duplique #1007
