### ISSUE TITLE
Configuration des envois de SMS par territoire

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1408]
Les territoires vont utiliser leur propre marché pour l'envoie des SMS.

L'idée serait donc d'ajouter une entrée dans cet écran permettant de :
- choisir un fournisseur pour l'envoie de SMS
- faire la configuration nécessaire pour pouvoir l'utiliser.

Puis faire les branchements qui vont bien pour que ce soit effectivement ce fournisseur qui soit utilisé dans le cadre d'envoi de ce département.

![Capture d’écran de 2021-05-03 10-28-47](https://user-images.githubusercontent.com/42057/116855846-5cadcd80-abfa-11eb-96d3-5ffd44ad666f.png)

À ce stade, nous savons nous interfacer avec Send In Blue et Netsize.

Un autre travail consistera à ajouter d'autres fournisseurs au fur et à mesure que les départements les demanderont.

ps: le terme territoire semble poser des problèmes. Ce que nous avons appelé secteur dans la sectorisation correspond plus ou moins à un territoire.. Une organisation est aussi correspondante à un territoire... Si nous trouvons une meilleure terminologie, ça serait intéressant.

**Comment by n-b** [comment]
Pour la configuration de l’_API Light Contact Everyone_ (Orange) pour la Somme: https://pad.incubateur.net/QPaxiD8nSbGfhiNbKMjYFw
