### ISSUE TITLE
Empécher de créer un rendez-vous dans le passée

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1427]
La page des statistiques ne s'affiche plus correctement depuis quelques jours.

![Screenshot_2021-05-05 Statistiques - RDV Solidarités](https://user-images.githubusercontent.com/42057/117208526-841cba00-adf5-11eb-98d8-5112d96d8270.png)

La requête permettant de récupérer une répartition des rendez-vous par statut n'en fini plus de tourner.

![Capture d’écran de 2021-05-05 22-59-52](https://user-images.githubusercontent.com/42057/117208615-a31b4c00-adf5-11eb-8024-5c4616dfc390.png)

Ce problème était lié à des rendez-vous créés avec des dates très loin dans le passé (année 0021 et 0202). Il y a sans doute deux leçons à en tirée :
- certains agents ont sans doute des interfaces sans date picker (vieux navigateur ?)
- il est très bizarre de pouvoir créer un rendez-vous dans le passé.

Ce ticket s'enrichi donc d'un blocage de la création de RDV dans le passé.

**Comment by yaf** [comment]
Après récupération d'un dump de la démo, je constate que localement, j'ai également des problèmes.

La requête SQL est longue, mais le serveur fini par répondre : 
> 22:10:27 web.1     | Completed 200 OK in 61979ms (Views: 0.1ms | ActiveRecord: 54.7ms | Allocations: 54744201)

Ensuite, c'est le JavaScript de rendu qui ne fonctionne pas.

**Comment by yaf** [comment]
Si je commente le `group_by_week` ça fonctionne.

> lapin_development=# explain analyse SELECT count(rdvs.*) FROM rdvs WHERE (starts_at < '2021-05-17') AND rdvs.status != 1 GROUP BY rdvs.status;
>                                                  QUERY PLAN                                                  
> -------------------------------------------------------------------------------------------------------------
>  HashAggregate  (cost=59.22..59.27 rows=5 width=12) (actual time=1.741..1.745 rows=4 loops=1)
>    Group Key: status
>    Batches: 1  Memory Usage: 24kB
>    ->  Seq Scan on rdvs  (cost=0.00..51.62 rows=1518 width=155) (actual time=0.018..1.363 rows=1514 loops=1)
>          Filter: ((starts_at < '2021-05-17 00:00:00'::timestamp without time zone) AND (status <> 1))
>          Rows Removed by Filter: 61
>  Planning Time: 0.109 ms
>  Execution Time: 1.783 ms
> (8 lignes)


>  lapin_development=# explain analyse SELECT count(rdvs.*) FROM rdvs WHERE (starts_at < '2021-05-17') AND rdvs.status != 1 AND (rdvs.starts_at IS NOT NULL) GROUP BY rdvs.status, (DATE_TRUNC('week', (rdvs.starts_at::timestamptz - INTERVAL '6 day') AT TIME ZONE 'Europe/Paris') + INTERVAL '6 day') AT TIME ZONE 'Europe/Paris';
>                                                  QUERY PLAN                                                  
> -------------------------------------------------------------------------------------------------------------
>  HashAggregate  (cost=85.78..117.86 rows=1283 width=20) (actual time=8.335..8.414 rows=227 loops=1)
>    Group Key: status, timezone('Europe/Paris'::text, (date_trunc('week'::text, timezone('Europe/Paris'::text, ((starts_at)::timestamp with time zone - '6 days'::interval))) + '6 days'::interval))
>    Batches: 1  Memory Usage: 97kB
>    ->  Seq Scan on rdvs  (cost=0.00..74.40 rows=1518 width=163) (actual time=0.058..7.296 rows=1514 loops=1)
>          Filter: ((starts_at IS NOT NULL) AND (starts_at < '2021-05-17 00:00:00'::timestamp without time zone) AND (status <> 1))
>          Rows Removed by Filter: 61
>  Planning Time: 0.283 ms
>  Execution Time: 8.559 ms
> (8 lignes)
>

**Comment by yaf** [comment]
Pour les stats, j'ai l'impression qu'on gagnerait à basculer sur metabase. Ça apporterait pas mal de flexibilité, sachant que nous pourrions mettre en place quelques requêtes, et aider à en construire de nouvelle si besoin, ou bien faire en sorte que les référentes sollicite leur DSI pour les aider.
Ceci étant, ça pourrait être intéressant de stocker la semaine malgré tout (semaine+année ?)

**Comment by yaf** [comment]
Bon, le problème vient, pour la production et la démo, d'un rendez-vous qui a été posé très loin dans le passé.
l'année 0012 pour la démo et l'année 0202 pour la production... Je soupçonne que certains agents utilise des navigateurs qui n'affiche pas les date picker (?).

J'hésite à ajouter un contrôle pour « empêcher » de poser un rendez-vous dans le passé. Qu'est-ce que tu en penses @n-b  ?

**Comment by n-b** [comment]
Ooohh c'est donc ça. Carrément, ça peut pas faire de mal de toute façon. 👍
