### ISSUE TITLE
Créneau disponible sur deux services différents

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1446]
Étant donnée
- deux motifs ayant le même libellé, mais attaché à deux services différents ;
- un agent dans chaque service (A et B)
- des plages d'ouvertures chacun sur le motif de son service.

En tant qu'agent ;
quand je cherche un créneau sur le motif RDV-BLA ;
je vois des disponibilités pour l'agent du service A et l'agent du service B

![Capture d’écran de 2021-05-11 19-24-35](https://user-images.githubusercontent.com/42057/117858988-bf543880-b28e-11eb-9595-772abb034fe3.png)

**Comment by n-b** [comment]
J’avais remarqué dans le code de la recherche de disponibilité qu’on cherchait par _nom de motif_ et nom par motif (par id). Je pense que c’est ça. Ça m’avait surpris, et je pense que c’est fait exprès, mais peut-être que ce n’est plus pertinent. Il faudra fouiller un peu l’historique.
