### ISSUE TITLE
Contacter l'équipe sur son email directement

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1465]
Nous avons mis en place Zammad en pensant que ça nous aiderait. Ça nous a apporté une chose : la meilleure qualification des demandes.

Je pense que nous pourrions arriver à un résultat similaire, dans une forme plus simple à traiter, en utilisant un template de corps de message et de sujet pour suggérer de nous fournir certaines informations.
De plus, ça réduirais notre dépendance à un outil externe, payant.

L'idée serait donc de reprendre les deux zones de formulaire (page support coté agent et page contact coté usager). Peut-être que ça pourrait être la même page support d'ailleurs. Les usagers pourrait très bien accéder à la documentation pourquoi pas.

**Comment by n-b** [comment]
duplique #1398, fixé par #1543
