### ISSUE TITLE
Organiser les noms et prénom des agents pour rendre cohérent l'affichage du tri

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1467]
Les agents sont triés par ordre alphabétique sur le nom de famille, or nous affichons le prénom puis le nom. Ça donne une expérience surprenante visuellement, l'impression que ce n'est pas trié.

![Screenshot_2021-05-21 Agenda de Polo DURANT (Service Social) - RDV Solidarités](https://user-images.githubusercontent.com/42057/119192507-926b0700-ba80-11eb-96ae-175eab8e2b1c.png)

Il serait bon de modifier l'affichage pour afficher le nom en premier, ou bien changer le trie.

_Il y a plusieurs endroits où les agents sont listé, mais sans doute est-il possible de ne changer que la méthode qui combine prénom et nom pour les remettre dans l'autre ordre_

**Comment by n-b** [comment]
J’ai revert #1529 juste après le déploiement, ça crashe à la pose de rendez-vous:
https://sentry.io/organizations/rdv-solidarites/issues/2178934294/?environment=production&project=1811205&query=is%3Aunresolved

```
NoMethodError: undefined method `reverse_full_name' for #<Lieu:0x00005585041beea8>
  from activemodel (6.0.3.7) lib/active_model/attribute_methods.rb:432:in `method_missing'
  from actionpack (6.0.3.7) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  from actionpack (6.0.3.7) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  from actionpack (6.0.3.7) lib/abstract_controller/rendering.rb:25:in `render'
  from actionpack (6.0.3.7) lib/action_controller/metal/rendering.rb:36:in `render'
  from actionpack (6.0.3.7) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  from activesupport (6.0.3.7) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  from vendor/ruby-2.7.3/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
  from activesupport (6.0.3.7) lib/active_support/core_ext/benchmark.rb:14:in `ms'
  from actionpack (6.0.3.7) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  from actionpack (6.0.3.7) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  from activerecord (6.0.3.7) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
  from actionpack (6.0.3.7) lib/action_controller/metal/instrumentation.rb:43:in `render'
  from app/controllers/admin/rdv_wizard_steps_controller.rb:17:in `new'
```

Je réouvre ici, ça n’a pas l’air trop dur.
