### ISSUE TITLE
Autoriser tous les numéros de téléphone valide

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1471]
Remonté par les côtes d'Armor, il semble que certains numéros de téléphone ne soient pas considéré comme valide (Voir le message privé sur le forum pour le détail du numéro. Il ne fonctionne pas en local pour moi non plus)

**Comment by n-b** [comment]
Les erreurs remontées correspondent à des numéros valides mais d’outremer: dans nos cas, Mayotte (`0639…`) et la Réunion (`0693…`). Je pense qu’il faut changer la façon dont on configure PhoneLib, et qu’il faut faire plusieurs appels à `PhoneLib.valid_for_country` avec les country-codes que l’on veut accepter.

Il reste une inconnue: est-ce que netsize (ou les opérateurs sms) acceptent les envois vers numéros? et à quel coût?

**Comment by n-b** [comment]
D’après les logs netsize, on a déjà envoyé des sms quatre fois à mayotte/la réunion (+262) et en guyane (+594). Le numéro en base était bien un `06 94 40…`. Côté netsize ça fonctionne, ça coûte simplement deux fois plus cher 😅.
