### ISSUE TITLE
Rendre les liens clickable dans les consignes de RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1483]
> Hello la team !
> 
> On a une incohérence coté consignes.
> Nous avons intégré un lien URL pour présenter le bilan école maternelle à partir d’une vidéo explicative :

![image008](https://user-images.githubusercontent.com/42057/120621913-a3435180-c45e-11eb-8d3a-ffee140a7453.png)

> 1/Dans les instructions avant le rdv- l’adresse ne se transforme pas en lien hypertexte 

![image009](https://user-images.githubusercontent.com/42057/120621962-ae967d00-c45e-11eb-91fe-c66b20cba59c.jpg)

> 2/ lorsque sur les indications après le rdv l’adresse url se transforme bien en lien hypertexte 

![image010](https://user-images.githubusercontent.com/42057/120622034-beae5c80-c45e-11eb-9619-cc01a39e30cc.png)

L'idée intéressante serait de permettre le markdown ? En intermédiaire, ça serait pas mal d'avoir au moins le lien.

**Comment by n-b** [comment]
On peut faire ça assez simplement avec [`auto_link`](https://github.com/tenderlove/rails_autolink). On utilise déjà `simple_format` pour une bonne partie des champs libre, on peut chainer les deux :-)
