### ISSUE TITLE
Corriger les tests de features

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1493]
EDIT:

~~Il y a un test qui c'est mis à échouer sans qu'aucun changement n'est eu lieu sur le code concerné.~~
~~Pour pouvoir avancer, les parties qui ne fonctionnent ont été commenté.~~
~~Ce ticket est là pour nous rappeler qu'il serait une bonne idée de creuser cela.~~

---

Les feature specs se sont mis à échouer largement depuis une semaine (fin mai 2021) dans les github actions et en local. Ce qu’on sait:
* ça ne concerne que les `specs/features`
* ça n’échoue que en parallèle
  * mais aussi bien en local avec `parallel:spec` (aka `make test`) que sur github (via `rspec_splitted.rb`)
* Ce ne sont pas toujours les mêmes tests qui échouent; 
* En local avec parallel:spec, ça n’échoue pas si on réduit le nombre de spec jusqu’à avoir moins d’un spec par job.
* Il est fort possible que les échecs avec parallel:spec et github actions soient similaires, mais indépendants. On avait déjà remarqué des hoquets avec parallel:spec.
* Ça pourrait être dû à la base nettoyée par erreur par un autre spec. (cf DatabaseCleaner).
  * Avec parallel:spec, chaque runner tourne en principe sur sa propre base
  * Sur Github Actions, je ne vois pas dans notre code ce qui fait tourner chaque instance sur une base séparée, c’est assez curieux.

**Comment by n-b** [comment]
Suite des investigations: j’ai fouillé un peu du côté de DatabaseCleaner, mais ça semble correctement configuré, et chaque instance tourne bien sur sa propre base. De même, on a bien 8 serveurs capybara en parallèle, a priori chacun sur leur port.

J’ai re-regardé les tests qui échouent: c’est toujours un élément manquant, souvent le `page-title`. Le screenshot et l’extrait html enregistrés par capybara après l’échec contiennent bien l’élément recherché! En plus, c’est la première ou une des premières ligne du test.

Est-ce que c’est un simple problème de délai ? Pourquoi est-ce que ça serait systématique quand ou tourne en parallèle, et pourquoi est-ce que ça n’échouerait pas en monothread?

**Comment by yaf** [comment]
:thinking: 
Merci pour le partage de la réflexion. Il y a peut-être un problème de délai effectivement.
