### ISSUE TITLE
Rendre RDV non annulable 

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-solidarites.fr#1496]
À la demande de la Drôme, un rendez-vous doit être non annulable (ou annulable qu'une fois) car dans le cadre du RSA il s'agit plus d'une convocation et ils pensent que le rendre annulable retarderait le premier rendez-vous.

**Comment by aminedhobb** [comment]
Dans un premier temps, nous afficherons un message de prévention au moment de l'annulation pour rappeler au demandeur les conséquences d'une annulation (https://mattermost.incubateur.net/betagouv/pl/muje3r9rytn8ipiz6rg6nxiacr).

**Comment by yaf** [comment]
Ce ticket me semble livré. Je le ferme.
