### ISSUE TITLE
Afficher l’alerte de numéro de téléphone existant aussi quand on crée un usager Responsable

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1509]
## Actuellement

Quand on crée un usager avec un numéro de téléphone déjà connu en base, on a un warning: “Attention, un usager avec le même numéro de téléphone existe déjà.”. Ça fonctionne dans le cas nominal.

Par contre, quand on crée un usager “Proche”, puis qu’on lui associe un nouveau “Responsable”, ce warning n’apparait pas avant la création.

![Screenshot_2021-08-17 Nouvel usager - RDV Solidarités(1)](https://user-images.githubusercontent.com/42057/129744568-0f72a3b5-04a4-4ec6-88ec-455efb7f1e3f.png)

![Screenshot_2021-08-17 Billy BOB - RDV Solidarités](https://user-images.githubusercontent.com/42057/129744578-3db7e8f1-e8b0-4ad3-863a-c166d3c7c0b2.png)

Nous avons bien, après la création, le message “D'autres usagers utilisent ce numéro de téléphone” sur la fiche de l’usager créé, mais c'est déjà trop tard.

## Attendu

Il faudrait que le warning s’affiche aussi quand on crée un proche et son responsable avec un numéro existant.

## Note technique 

Derrière, c’est `DuplicateUsersFinderService` et `ActiveModel::Caution`, et à vue de nez, le dernier refactor d‘importance est #1214. Je connais mal ce code, mais j’ai peur que ça soit un peu complexe à corriger.

## Personne à notifier :

* a pierrot

**Comment by yaf** [comment]
Le coût de correction de ce problème en temps de réalisation et en complexité ajouté au code source RDV-Solidarités est élevé.

Sachant que 
- nous allons devoir modifier intégralement ces parties
- le doublon est détecté malgré tout, mais a postériori
- le cas d'usage est rare (?)
- le doublon sur le téléphone n'est pas bloquant

Nous pensons qu'il est préférable de fermer le ticket et de passer à autre chose.
