### ISSUE TITLE
Alerter lorsque que le rendez-vous entre en colision avec une absence

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1523]
Actuellement, les absences sont qu'affiché dans l'agenda.

Il serait bien d'ajouter une alerte lors de la création et la modification d'un rendez-vous si la date du rendez-vous est en collision avec une période d'absence.

_Voir le système d'alerte déjà en place._

_Ce billet est le miroir de celui sur l'ajout d'une alerte lorsque l'on pose une absence alors qu'il y a un rendez-vous existant_ : https://github.com/betagouv/rdv-solidarites.fr/issues/1401

**Comment by n-b** [comment]
duplique #1007
