### ISSUE TITLE
Prio tickets `.M` sur le [tableau des prio](https://docs.google.com/spreadsheets/d/1ryGnWWCx2EOoJ0a1weckx6TUwxhQD_AYBWw6vn0R3iA/edit?usp=drive_web&ouid=105077925985295860964)

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1583]
Pas de prio sur les tickets `.S`

**Comment by francois-ferrandis** [comment]
Je vois ça quand j'essaye d'ouvrir le Google Sheet : 

![image](https://user-images.githubusercontent.com/6357692/170273411-c1909a43-ec98-4476-81c7-c765765f4a2a.png)

**Comment by yaf** [comment]
Oui, c'est normal. Il a été supprimé. Où y a-t-il encore des références à ce tableau ?
