### ISSUE TITLE
Mise à jour de la doc d'API

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1586]
il faudrait mettre à jour la doc en correspondance.:
* [x] suite à la PR #1577 (et #1585)  qui ajoute des informations dans l'API
* [x] suite à la PR #1578 et #1581 qui modifient le contenu pour l’api users

**Comment by n-b** [comment]
J’ai mis à jour la doc de l’api pour les Motifs (#1577 et #1585). J’ai quelques suggestions sur l’api elle-même (poke @aminedhobb :
* Ajouter `active` et `reservable_online` au blueprint. C’est plus cohérent si on peut faire une requête sur ces attributs.
* Gérer aussi le cas `active=false`. À vue de nez, un truc du genre `.where(active: !!params[:active] if params.include?(:active)`. (idem `reservable_online`)
* C’est pas très important ici, et clairement on le fait pas partout, mais en général, si on commence à faire des queries sur un attribut, il faut un index en base. C’est pas cher, surtout sur un booléen.
* Ça serait cool aussi d’avoir la route index sans organisation. C’est peut-être un peu subtil à cause des policies, mais ça serait plus cohérent avec le reste de l’api?
