### ISSUE TITLE
Permettre aux agents de réinitialiser leur mot de passe depuis la page de connexion d’usagers

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1614]
Un agent qui oublie son mot de passe est déjà confus, et ne voit pas forcément la distinction entre la page de réinitialisation usager et la page de réinitialisation agent. Dans `Users::SessionsController#create`, on fait quelque chose (de pas forcément très élégant) pour permettre aux agents de se connecter depuis la page de connexion des usagers. On pourrait faire la même chose dans `Users::PasswordsController#create`.

On peut aussi travailler plus simplement sur la formulation et la présentation des pages de login, il y a peut-être améliorations faciles.

Demandes:
* Amandine P, email 4 août 2021 à 12:47 “Problème de connexion à RDV Solidarités”

**Comment by n-b** [comment]
@aminedhobb c’est lié à #1576: dans `CustomDeviseFailure`, on fait:
```
class CustomDeviseFailure < Devise::FailureApp
  # redirect to registration
  def route(scope)
    scope == :user ? :new_user_registration_url : super
  end
  ...
```

Est-ce que c’est toujours pertinent? On redirige *toutes* les erreurs de login sur la page d’inscription, c’est vraiment ce qu’on voulait faire?

**Comment by aminedhobb** [comment]
> ~@aminedhobb c’est lié à #1576: dans `CustomDeviseFailure`, on fait:~
> 
> ```
> class CustomDeviseFailure < Devise::FailureApp
>   # redirect to registration
>   def route(scope)
>     scope == :user ? :new_user_registration_url : super
>   end
>   ...
> ```
> 
> ~Est-ce que c’est toujours pertinent? On redirige _toutes_ les erreurs de login sur la page d’inscription, c’est vraiment ce qu’on voulait faire?~
> 
> Edit: ce commentaire était pour #2029

Je viens de voir ce commentaire @n-b désolé, mais pour info c'est pas moi qui l'avait introduit, il avait été introduit ici: https://github.com/betagouv/rdv-solidarites.fr/pull/1138
