### ISSUE TITLE
Débrayer l’envoi de notification au rendez-vous

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1617]
## Actuellement

Des notifications usagers sont envoyées à la création du rendez-vous, et un peu avant le rendez-vous pour faire un rappel (voir Notifications usagers - RDV-Solidarités pour plus d’information).

Les motifs peuvent être configurés pour être
- visible et notifié
- visible et non notifié
- invisible (et donc non notifié)

## Attendu

L’idée serait de permettre, à la fin du tunnel de prise de rendez-vous, de désactiver la notification usager. Peut-être en mettant une case à cocher (cochée par défaut) pour débrayer l'envoi (une par notification).

Il faudrait pouvoir conserver le rappel de notification. Faut-il faire 2 cases à cocher par notification ? Ou bien prévoir une liste déroulante permettant de choisir la configuration voulue : 
- aucune notification
- rappel uniquement
- notification complète.

![Screenshot_2021-08-05 Créer RDV 4 4 - RDV Solidarités](https://user-images.githubusercontent.com/42057/128322672-97a2716c-cda5-4572-adc5-725c493620e4.png)

La configuration de motif doit permettre de « préremplir » les champs dans le tunnel de prise de RDV. Ceci étant, l'agent pourra « débrailler » ces aspects dans le dernier écran du tunnel.

Il faudra donc ajouter une case pour activer ou désactiver la visibilité d'un RDV coté usager. :warning: **Attention, un RDV non visible ne peut pas être annulé par l'usager !**

## Référence

C’est un sujet qui a été évoqué lors de lors de l'atelier sur la cellule familiale : https://forum.rdv-solidarites.fr/t/atelier-cellule-familiale-et-notifications-multiples-jeudi-6-mai-2021-11h/247

Voir https://forum.rdv-solidarites.fr/t/debrayer-lenvoie-de-notification-au-rendez-vous/281

**Comment by n-b** [comment]
On peut faire #1706 et #1617 en même temps, c‘est les mêmes vues.

**Comment by yaf** [comment]
- [ ] pouvoir préciser dans le tunnel de prise de RDV
- [ ] cocher / décocher / bloquer en fonction des infos disponible (motif, préférence usager, présence email et mobile) à l'affichage
- [ ] afficher les informations sur la fiche du RDV
- [ ] prendre en compte l'information lors de l'envoie de notification (ou non)
- [ ] modifier les choix à postériori sur la fiche rdv (?)
- [ ] ajouter l'information (surtout si ouverture du changement sur la fiche RDV) dans le journal d'évènement du RDV
