### ISSUE TITLE
Filtrer les rendez-vous annulés dans l'agenda

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1634]
## Actuellement

Lorsqu'un rendez-vous est annulé, par un agent ou par un usager, ce rendez-vous apparaît rayé dans l'agenda.

![Screenshot_2021-08-17 Votre agenda - RDV Solidarités](https://user-images.githubusercontent.com/42057/129734112-325bf3c0-e2b5-4b32-9606-fa6940e34d37.png)

Pour certains agents, c'est rassurant, pour d'autres, c’est perturbant.

Ceux et celles pour qui c'est perturbant demande à pouvoir supprimer les rendez-vous.

Le filtre des rendez-vous par status (en haut à droite de la copie d'écran) ne fonctionne plus aujourd'hui.

## Attendu

Remplacer le filtre qui ne fonctionne pas par une case a coché (décoché par défaut ?) pour activer l'affichage des rendez-vous annulés.

**Comment by n-b** [comment]
J’ai jeté un coup d’oeil, on peut corriger le filtre facilement. Par ailleurs, on a un peu de baddata sur Rdv, et notamment sur les scopes `Rdv.canceled` et `Rdv.not_canceled` qui se basent sur la présence ou non de `Rdv#canceled_at`. Aujourd’hui en prod:
```
> Rdv.not_cancelled.unknown.count
=> 34973
> Rdv.not_cancelled.waiting.count
=> 53
> Rdv.not_cancelled.seen.count
=> 161870
> Rdv.not_cancelled.excused.count
=> 620  ⚠️
> Rdv.not_cancelled.revoked.count
=> 0
> Rdv.not_cancelled.noshow.count
=> 2190  ⚠️

> Rdv.cancelled.unknown.count
=> 10  ⚠️
> Rdv.cancelled.waiting.count
=> 0
> Rdv.cancelled.seen.count
=> 10  ⚠️
> Rdv.cancelled.excused.count
=> 25311
> Rdv.cancelled.revoked.count
=> 284
> Rdv.cancelled.noshow.count
=> 16278
```

En principe, tous les Rdv en `excused`, `revoked` et `noshow` ont une date `cancelled_at`, et seulement ceux-ci. Il faudrait nettoyer un peu en base. Par ailleurs, on pourrait optimiser un peu les scope en question avec un `where(status: %w[excused revoked noshow])`, `status` est fait pour ça et est indexé.

**Comment by yaf** [comment]
à fermer par #2271 ?
