### ISSUE TITLE
Ajouter un lien vers la fiche RDV depuis l'évènement ICS

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1671]
## Actuellement

L'évènement ICS contient peu d'information sur le rendez-vous. C'est voulu, ça limite la diffusion d'informations personnel. Par contre, les agents qui voient un rendez-vous dans l'agenda sont obligé d'aller sur RDV-Solidarités et de « retrouver » le rendez-vous en question.

## Attendu

Ajouter un lien vers la fiche du rendez-vous dans RDV-Solidarités dans l'évènement ICS. Cela permettrait aux agents de pouvoir cliquer sur un lien dans leur agenda pour se pointer directement sur la bonne fiche dans RDV-Solidarités.

_C'est peut-être à ajouter également pour les absences et plages d'ouvertures ?_

## Références

- https://forum.rdv-solidarites.fr/t/rajouter-des-liens-vers-rdv-solidarites-dans-les-fichiers-ics-envoyes-aux-agents/213/2 où @n-b évoque des pistes pour faire ça.

**Comment by francois-ferrandis** [comment]
@yaf À ce que je vois, le lien est déjà présent pour les RDV ; est-ce que ce ticket consiste à l'ajouter pour les absences et les plages d'ouverture ?

**Comment by yaf** [comment]
Est-ce que tu as vu un lien vers le RDV dans le fichier ICS joint ? Je viens de faire le tour de mes outils et je n'arrive pas à importer l'ICS dans
- thunderbird
- évolution
- gnome-calendar
- google calendar (en ligne donc)

et lorsque j'ouvre le fichier dans un éditeur de texte, je vous un fichier binaire :-/

Est-ce que c'est moi uniquement ? Est-ce qu'il y a un pépin avec l'environnement de dev ? Est-ce que les ICS pour les agents sont cassés ?

Si tu as vérifié que ça apparait bien dans le fichier ICS de la pièce jointe de la notification à l'agent, alors c'est que c'est bon, et ce ticket peut être fermé :)

Merci ! :bow:
