### ISSUE TITLE
Trouver un créneau côté agent depuis un smartphone

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1674]
## Actuellement

RDV-Solidarités, bien que peu optimisé pour l'utilisation sur mobile, n'interdit pas l'accès via ce type de terminal.

Par contre, côté agent, le bouton « trouver un créneau » n'apparait pas.

Pour y accéder, les agents les plus à l'aise avec le numérique utilise la configuration « version ordinateur » du navigateur de leur smartphone. Mais ce n'est pas possible sur tous.

![f5ad5751a127c38d8e570e9e496b2bde0c805d24](https://user-images.githubusercontent.com/42057/131152485-80dc3d58-71d6-4167-9334-635d55390471.png)

## Attendu

Pouvoir utiliser le bouton « trouver un créneau » côté agent, depuis un smartphone.

## Demandes

* Le 24 sept. 2021 à 15:55, Isabelle B., Amandine P.
    > Isabelle: Les professionnelles remontent qu’elles ne peuvent saisir de RV sur RDVS à partir de leur tél mobile professionnel.
    > Isabelle: Ça occasionne de nouveaux appels aux secrétaires pour fixer des RV alors qu’ils pourraient être pris directement par les professionnelles en visite auprès des usagers.
    > Amandine: C’est surtout que je suis quasi sûr que cela fonctionnait avant…. Mais j’ai peut etre revé

**Comment by n-b** [comment]
Est-ce que ça vaut le coût de lancer un chantier plus général de comptabilité mobile / responsive / etc? Ça peut être beaucoup de travail, et je ne sais pas quelle est la proportion d’agents gênés par ça.

**Comment by yaf** [comment]
Apparemment, ça ne fonctionne pas ?

![Screenshot_2021-09-28 Votre agenda - RDV Solidarités](https://user-images.githubusercontent.com/42057/135044069-ee81946c-cb94-43ff-b309-eacddd239fe9.png)

**Comment by n-b** [comment]
Le déploiement avait planté côté scalingo. Je le relance.

**Comment by yaf** [comment]
Ah oui, merci. Je comprends mieux. Je pense que c'est un peu pareil pour mon autre sujet sur l'ajout de la ville dans l'export :thinking:
