### ISSUE TITLE
Corriger l’imprécision des statistiques des status sur la semaine en cours

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1678]
Sur https://www.rdv-solidarites.fr/stats/92#chart-4, la dernière colonne correspond aux états des Rdv de la semaine en cours. Elle semble ne pas correspondre à la réalité; Clarisse B nous indique qu’à lundi midi, les stats pour l’intégralité des département ressemblaient à ça:

![image001](https://user-images.githubusercontent.com/139391/131640143-ebd6b3d8-5e3c-4405-8c13-20fa5967681c.png)

Mon analyse à première vue était qu’on avait qu’un poignée de Rdv en base, ce qui expliquait le problème, mais après vérification il y avait déjà quelques centaines de Rdv. Par ailleurs, les stats pour le CD77 semblait déjà plus cohérentes:

![image002](https://user-images.githubusercontent.com/139391/131640383-7b0db63b-0ac7-4966-90b5-ba99350ac8d6.png)

Il ne semble pas non plus y avoir de problème pour les stats des semaines précédentes.

Ça pourrait s’expliquer par une bête histoire de cache, mais je n’ai pas l’impression qu’on garde les résultats des stats en cache. @yaf ça t’évoque quelque chose?

---
Demandes
* Clarisse B le 30 août 2021 à 11:58

**Comment by n-b** [comment]
Par ailleurs: il y a un problème je crois avec le code couleur: le rouge devrait correspondre aux absences non excusées

**Comment by yaf** [comment]
Est-ce que nous avons toujours ce problème ? Est-ce vraiment un problème ?

**Comment by n-b** [comment]
Non, pas vraiment. Enfin, on n’y a rien fait, mais c’est inévitable que les stats de la semaine en cours soient moins cohérentes le lundi. On a corrigé le thème de couleurs, c’est déjà ça. Je ferme, on réouvrira au besoin.
