### ISSUE TITLE
Corriger / compléter l’intégration des webhooks de la Drôme

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1696]
Nous avons des retours d’erreurs réguliers pour les créations de Plages d’ouvertures et d’Absence de la part du webservice de la drôme.

Quand on envoie une Absence:
```
response: 400
body: {"message": "The following parameters are missing: email, end, start, name, users, uuid, "}
```
Ce sont les noms de paramètres pour un Rdv; on dirait que le serveur essaye d’intrerpréter le payload comme un Rdv.

Quand on envoie une PlageOuverture:
```
response: 400
body: {"message": "Model not allowed."}
```

À vrai dire, je ne suis même pas certain que ça ait jamais fonctionné 🤔 

Demandes:
* Le 9 sept. 2021 à 12:39, S. NASLOT

**Comment by yaf** [comment]
J'ai commencé à supprimer certaines erreurs. Celle sur les absences et les plages d'ouvertures. L'interconnexion semble ne pas prendre en compte ces évènements. Il y a une notification par email en parallèle. Je suppose que les Zimbra peuvent se retrouver à jour via ces notifications.

Reste à statuer sur les erreurs de transmission de RDV. Je dirais que les rendez-vous anciens peuvent être supprimé. C'est à discuter.

**Comment by yaf** [comment]
Analyse des nombreux jobs en erreur sur l'interconnexion avec la Drôme.

La date de début des problèmes (date du plus vieux des messages) : 
> enqueued_at: '2021-08-28T12:57:50Z' 
C'est un samedi.

Nous n'avons livré aucune modification autour de cette date.
Notre livraison précédente était le jeudi 26.

Le message d'erreur de ce message
`body: {"message": "Appointment id doesn't exist"}`

Pour cette erreur, difficile de rejouer le message.

---

Erreur sur une absence 
Quel **email** est manquant ? Il y a celui de l'agent
Pour le **start** et le **end**, il y a le first_day et start_time ainsi que le end_day et end_time...
Pas de **name** effectivement, nous donnons toujours un first_name et last_name pour l'agent.
Pas de **users** pour une absence, c'est normal.
Ici, pas de champ appelé **uuid**, mais l'**id** de l'absence fait office d'identifiant unique

> body: {"message": "The following parameters are missing: email, end, start, name, users, uuid, "}

---

"meta": "model":"PlageOuverture","event":"created","timestamp":"2021-09-03 09:54:47 +0200"}}'

body: {"message": "Model not allowed."}
   
---

J'ai l'impression que nous avons

- une série d'erreurs sur les absences, parce que le format d'une absence n'est pas celui d'un RDV. Ces erreurs ont du passé inaperçu puisque les absences sont notifié par email et donc potentiellement synchronisé par cette autre voie...
- une série d'erreurs sur les RDV parce que l'identifiant de rendez-vous ("Appointment id doesn't exist") n'est pas retrouvé... 
- quelques erreurs sur les plages d'ouverture

**Comment by yaf** [comment]
## Plage d'ouverture

Le « model » d'objet que nous envoyons pour les plages d'ouvertures n'est pas autorisé. Pour tous les messages concernant les plages d'ouverture que nous envoyons, nous recevons une erreur `"Model not allowed."` du connecteur de la Drôme.

## Absence

Pour les absences, nous recevons systématiquement le message d'erreur suivant : 

`"The following parameters are missing: email, end, start, name, users, uuid, "}`

Pourtant, dans chacun des messages envoyé, retourné en erreur, que nous avons regardé, il y a bien les emails, la date de début e de fin, le nom, les usagers et l'identifiant unique...

Est-ce qu'il y a un souci dans la prise en compte coté du connecteur de la Drôme ?

## RDV

Pour les messages envoyés pour la synchronisation de rendez-vous, retourné en erreur, nous observons :

Le cas de la mise à jour d'un rendez-vous ;
avec un évènement contenant : `"model":"Rdv","event":"updated"` dans le message envoyé ;
nous avons deux messages d'erreurs
- `"Can't update appointment."`
- `"Appointment id doesn't exist"`

Le cas de la suppression d'un rendez-vous ;
avec un évènement contenant : `"model":"Rdv","event":"destroyed"` dans le message envoyé ;
nous avons  un message d'erreur
- `"Appointment already deleted."` 

Pour le cas de la création d'un rendez-vous, il n'y a aucun message d'erreur.
