### ISSUE TITLE
Pouvoir créer des RDV effectués en binôme d’agents de services différents

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1708]
## Actuellement

Aujourd’hui, il est impossible d’avoir sur le même Rdv plusieurs agents de services différents.

## Attendu

On veut pouvoir ajouter à un même Rdv plusieurs agents de services différents (mais dans la même organisation.)

## Technique

A priori, il n’y a rien dans le schéma de la base de données qui l’interdise; par contre, les agents des autres services ne sont pas disponibles quand on crée le Rdv, parce que les Agents proposés sont ceux dont le service est associé au motif, et qu’un Agent ne voit que les agents de son service.

Est-ce qu’il faudrait pouvoir voir tous les agents de l’organisation _qui font partie d’un service répondant au motif du Rdv_?

## Demandes

* Discussion préalable sur le forum https://forum.rdv-solidarites.fr/t/pouvoir-creer-des-rdv-effectues-en-binome-dagents-de-services-differents/73
* Le 10 sept. 2021 à 12:03, LE HELLOCO Magalie

**Comment by yaf** [comment]
Ce problème sera sans doute réglé, ou plus facile à résoudre, quand le ticket #1670 sera terminé...
La liste des agents pourra alors être celle des agents autorisés sur le motif

**Comment by yaf** [comment]
Ce [ticket](https://github.com/betagouv/rdv-solidarites.fr/issues/1708) est trop gros. Il décrit bien le problème, et oriente la solution vers ce que nous avons déjà évoqué : le décloisonnement.

Pour rappel, le thème « décloisonnement » ne signifie pas enlever les mûrs de séparation entre les services, mais les rendre plus flexible.

L'idée est bien de permettre à des agents de services différentes de réaliser des rendez-vous ensemble pour un motif donnée (et seulement sur ceux là). **C'est le décloisonnement de motif**. Pour y arriver, l'agent aura besoin de trouver des créneaux disponible dans l'agenda de l'autre agent. **C'est le décloisonnement d'agenda**. Où nous avons ajouté un élément qui permet de partager un agenda avec ou sans le détail des rendez-vous.

Nous allons donc fermé ce ticket unique [#1708](https://github.com/betagouv/rdv-solidarites.fr/issues/1708). Il correspond au groupement de tous les tickets de décloisonnement :
- [ Simplifier la configuration et affiner les droits d'accès des motifs #1779 ](https://github.com/betagouv/rdv-solidarites.fr/issues/1779) ; Ce ticket contient le déplacement des motifs au niveau du territoire (département) ET la modification d'accès. C'est-à-dire la liste des agents que l'on peut sélectionner lorsque l'on cherche un créneau ou que l'on crée un RDV ; Aujourd'hui, c'est une liste selon le service, après ce ticket, ça sera ceux qui ont l'autorisation sur ce motif (peu importe le service). Peut être fait avant l'accès à l'agenda (#1692 et #1782) mais dans ce cas, le rendez-vous se posera en « aveugle », sans voir l'agenda de l'autre agent. Ce n'est pas bloquant je pense. 
- [ Accéder agenda par agenda, en lecture seul ou en écriture #1692 ](https://github.com/betagouv/rdv-solidarites.fr/issues/1692) warning Faire ce ticket après #1782
- [ Remonter la gestion des agents et leur accès au niveau du territoire #1782 ](https://github.com/betagouv/rdv-solidarites.fr/issues/1782)
- [ Associé les usagers aux territoires plutôt qu'aux organisations #1786 ](https://github.com/betagouv/rdv-solidarites.fr/issues/1786) Si ce ticket est réalisé avant #1692 et #1779 alors la restriction d'accès se fera en fonction du service. C'est un ticket un peu à part, et qui pourtant à un impact assez fort sur la prise de RDV : plus besoin de créer un usager pour se rendre compte « ensuite » qu'il existe déjà... Nécessite sans doute un travail sur la visibilité des champs (avant ?) [ Paramétrer les champs utilisés pour qualifier un usager #1814 ](https://github.com/betagouv/rdv-solidarites.fr/issues/1814)
