### ISSUE TITLE
Ne pas tenir compte des majuscules dans l’email à la connexion

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1709]
## Actuellement

Un usager enregistré avec l’email toto@toto.com ne peut pas se connecter s’il saisit TOTO@TOTO.COM. C’est contre-intuitif, parce que RDVS convertit l’adresse en minuscule lors de la création du compte.

## Attendu

Permettre de se connecter avec une adresse email sans tenir compte de la casse.

## Technique

* Il faut le faire aussi bien pour les agents que pour les usagers.
* Vérifier ce que dit la rfc sur ce sujet, quand même.

## Demandes

* Le 13 sept. 2021 à 11:36, Vaneecke E.

**Comment by yaf** [comment]
J'ai l'impression que ce problème est déjà réglé ou bien il apparait dans un cas particulier non évoqué dans l'énoncé :thinking:

**Comment by n-b** [comment]
Je ne reproduis pas non plus :-/

Je ferme, ça reviendra si c’est un vrai problème 🤷
