### ISSUE TITLE
Ne pas prendre en compte les faux négatif de la Drôme

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1752]
## Actuellement

L'outil d'interconnexion de La Drôme ne traite pas les plages d'ouvertures et les absences.

Il nous renvoie également des erreurs lorsqu'un rendez-vous ne peux pas être modifié ou supprimé.

## Attendu

Analyse les erreurs renvoyées par l'outil d'interconnexion de la Drôme et ne pas prendre en considération ces erreurs-là.

## Technique

Les erreurs à récupérer

- response: 400 body: {"message": "The following parameters are missing: email, end, start, name, users, uuid, "}
- response: 400 body: {"message": "Model not allowed."}
- response: 400 body: {"message": "Appointment already deleted."}

**Comment by n-b** [comment]
Le but est d’éviter que ces erreurs applicatives du côté du webhook ne remontent dans sentry; est-ce que c’est lié à #1490, où on pourrait désactiver les notifications ?

**Comment by yaf** [comment]
Via https://github.com/betagouv/rdv-solidarites.fr/pull/1871 nous avons pu désactiver l'envoie des webhook pour les absences et les plages d'ouvertures.
