### ISSUE TITLE
Ne pas prendre en compte les erreurs d'envoi de SMS sur des numéros invalide

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1753]
## Actuellement 

Il y a des erreurs d'envoi de SMS lié à des numéros qui ne sont pas attribués

## Attendu

Il serait bon de faire remonter l'information sur la fiche usager que le téléphone n'est pas un numéro de mobile valable, que nous ne pouvons pas envoyer de message à ce numéro.

_Pourquoi les numéros ne sont pas détectés par la lib Phonelib ?_

## Technique

Le type de réponse à récupérer

`:response=>{"responseCode"=>16, "responseMessage"=>"Could not route message", "timestamp"=>"2021-09-27T01:24:57Z", "traceId"=>"8e44414a6392925f59d2"}`

**Comment by n-b** [comment]
> Pourquoi les numéros ne sont pas détectés par la lib Phonelib

Pour moi ce sont simplement des numéros non attribués, on ne peut pas vraiment le savoir avant d’essayer de les contacter.

**Comment by n-b** [comment]
Ah, et ce retour concerne netsize (aka linkmobility). Les autres opérateurs ont peut-être des retours différents. C’est aussi lié à #1431

**Comment by francois-ferrandis** [comment]
Voir aussi #2729

**Comment by francois-ferrandis** [comment]
Je trouve que ce ticket fait doublon avec #2729 donc je ferme. :broom:
