### ISSUE TITLE
Corriger l’affichage du message d’erreur à la fusion d’usager

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1762]
## Actuellement

Si la fusion échoue, on a le message d’erreur générique de Rails:

![image002](https://user-images.githubusercontent.com/139391/135305442-7d91428e-3b87-4440-b1f5-e68387cb215a.png)

## Attendu

Il faudrait afficher l’erreur 🤷 .

## Demandes

* Le 29 sept. 2021 à 15:00, MELIX B.

**Comment by NFontelle** [comment]
https://sentry.io/organizations/rdv-solidarites/issues/3268459491/?project=1811205&query=is%3Aunresolved+sdk.name%3Asentry.ruby.rails&sort=date&statsPeriod=14d

Lié à cette erreur ?
