### ISSUE TITLE
Fusionner dans le bon sens les usagers si l’un des deux vient de franceconnect

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1763]
## Actuellement

En cas de fusion d’usagers, si l’un deux a été créé par franceconnect, il est impossible de remplacer son nom/prénom par l’autre.

## Attendu

Il faut forcément garder son nom, ou fusionner vers l’autre usager.

## Demandes 

* Le 29 sept. 2021 à 15:00, MELIX B.

**Comment by yaf** [comment]
Décomposé en deux tickets distincts :
- #2705 
- #2706
