### ISSUE TITLE
Libérer les absences - Associer une absence uniquement à l'agent

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1796]
Voir https://pad.incubateur.net/39O_Ikc_SPKWJ1jQtWraWA?edit pour les notes de conception

## Actuellement

Soit un agent Bob qui travaille sur  2 organisations : Paris Nord et Paris Sud.
Bob pose un congé sur l'organisation Paris Sud.

Les collègues de Bob du même service et de la même organisation vois les congés dans l'agenda.

Un collègue d'une autre organisation ne voit pas les congés de Bob.

Refs :
- https://zammad10.ethibox.fr/#ticket/zoom/1857
- https://zammad10.ethibox.fr/#ticket/zoom/3468
- https://zammad10.ethibox.fr/#ticket/zoom/3994

## Attendu

Voir dans l'agenda de Bob, peu importe l'organisation où je suis, ses congés.

**Attention :warning:** le calcul de créneau sera impacté par cet aspect organisation.

## Technique

Les absences sont aujourd'hui associées à l'organisation d'où elles ont été posées. Nous pourrions faire sauter ce lien pour associer les absences uniquement à l'agent.

**C'est surtout une modification technique, car les indisponibilités sont déjà visibles d'une organisation à l'autre**

## Dépendance

Nécessite une modification sur les organisations, ce qui pose une question sur la gestion des webhooks. Ces derniers étant associé à l'indisponibilité via les organisations. Si le lien est cassé, plus de webhooks possible.

Nécessite donc que #2546 soit réalisé avant.

**Comment by yaf** [comment]
Le mieux serait de lier une absence à plusieurs organisations (voir toutes) (?)

**Comment by yaf** [comment]
Voir https://pad.incubateur.net/39O_Ikc_SPKWJ1jQtWraWA?edit pour les notes de conception

**Comment by francois-ferrandis** [comment]
@mekaidmekaid Voici les changements qui vont impacter les départements lors du déploiement de ce ticket. Il faudrait voir avec eux si ça les impacte, et si oui, décider d'un plan de migration.

Jusqu'à maintenant, les webhooks envoyaient ces données vers les serveurs configurés par les départements : 

```json
{
  "absence": {
    "id": 123456,
    "start_time": "10:00:00",
    "title": "Indisponibilité 1",
    "...": "...",
    "agent": { "id": "..." },
    "organisation": {
      "id": 1,
      "email": null,
      "name": "Mon orga",
      "phone_number": null
    }
  }
}
```

Avec le changement proposé dans ce ticket, l'attribut `"organisation"` deviendra `"organisations"` et contiendra désormais une liste d'au moins un élément :

```diff
-    "organisation": {
-      "id": 1,
-      "email": null,
-      "name": "Mon orga",
-      "phone_number": null
-    }
+    "organisations": [
+      {
+        "id": 1,
+        "email": null,
+        "name": "Mon orga",
+        "phone_number": null
+      },
+      {
+        "id": 2,
+        "email": null,
+        "name": "Mon autre orga",
+        "phone_number": null
+      }
+    ]

Le plan de migration que je propose : garder à la fois un attribut `"organisation"` (contenant la première orga de la liste) et le nouvel attribut `"organisations"`, le temps que les utilisateurs de webhooks adaptent leurs systèmes, puis supprimer `"organisation"` quand c'est migré.

Scénario idéal : le champ `"organisation"` n'est pas utilisé par les départements, et là on fait le changement sans souci.

Note : RDV-Insertion, les seuls utilisateurs de notre API, nous ont dit qu'il n'utilisaient pas les absences (ni en API ni en webhooks), tu confirmes @Holist ?

**Comment by victormours** [comment]
Vu avec François :
- les trois tickets donnés en exemple indiquent que les agents s'attendent à ce qu'une absence s'applique à toutes les organisations
- ça peut être plus simple d'appliquer les absences à toutes les organisations plutôt qu'ajouter une table de jointure

Proposition de spec :
- Dans un premier temps : sur l'index des absences pour les agents appartenant à plusieurs organisations, indiquer que bientôt les absences s'appliqueront à toutes les organisations, et dire que si ce fonctionnement risque de leur poser problème, ils peuvent nous écrire un mail à l'adresse de contact. Ça nous permet de faire de la recherche utilisateur passive en attendant qu'on fasse le développement
- Contacter les départements qui utilisent les webhook, et les prévenir que le champs absences.organisation_id sera supprimé, et leur demander si ça pose pb
- Contacter Rdv insertion pour leur dire que ce champs va disparaitre de l'api et des webhooks
- Deuxième déploiement : supprimer la colonne absences.organisation_id

**Comment by yaf** [comment]
Il faudra penser à modifier l'agenda du coup, car il affiche les absences de toutes les organisations actuellement (il va y avoir des doublons dans la solution que vous proposez)
