### ISSUE TITLE
Gérer les services par territoire depuis le module de configuration

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1807]
## Actuellement

Dans la page d'invitation d'un ~~agent~~ professionnel, la liste des services contient l'ensemble des services disponible, existant sur RDV-Solidarités

Parfois, les départements souhaitent modifier le nom d'un service, mais les autres départements qui l'utilisent ne le veulent pas...

Et puis, la liste des services commence à être très longue...

![Capture d’écran de 2022-12-12 15-28-47](https://user-images.githubusercontent.com/42057/207071030-31cc170a-2181-45e2-9bf5-775242dd773f.png)

## Attendu

Avoir un menu dans l'interface d'administration territorial pour créer, modifier, supprimer les services.

S'il n'y a aucun service, alors cette notion ne doit pas être visible dans l'interface métier ni l'interface usager

**Comment by francois-ferrandis** [comment]
Penser à adapter ce qui a été fait dans #2572 :wink:

**Comment by victormours** [comment]
Il y a de la logique spécifique aux cnfs qui va pouvoir être simplifiée grâce à cette issue (voir https://github.com/betagouv/rdv-solidarites.fr/pull/2321)

**Comment by victormours** [comment]
On fait comme pour les catégories de motif

**Comment by mekaidmekaid** [comment]
Yes, j'organise un atelier là-dessus pour revenir sur les limites de la configuration actuelle et explorer les différentes issus.
