### ISSUE TITLE
Ajouter ANDI à la liste des scripts approuvés

### ISSUE THREAD

**Issue by rebeccadumazert** [betagouv/rdv-solidarites.fr#1859]
En vue de rendre RDV-Solidarité accessible, l'ajout du script ANDI est nécessaire afin que toute personne visitant le site et souhaitant vérifier son accessibilité puisse utiliser le service ANDI sans qu'il n'y ait d'erreurs dans la console.

**Comment by yaf** [comment]
Closed by #1860
