### ISSUE TITLE
Réponse de l'usager aux notifications par courriel directement vers les agents concernées

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1876]
## Actuellement

Les usagers reçoivent des notifications emails et SMS.

Lorsqu'ils et elles répondent au courriel, c'est à l'adresse contact@rdv-solidarites.fr que la réponse arrive.

L'équipe, fait ensuite suivre ce message aux agents concernés.

## Attendu

Que la réponse de l'usager soit envoyé directement aux agents concernés, sans passage intermédiaire.

**Il faut impérativement que l'adresse courriel de l'agent reste masqué pour que l'usager ne puisse pas le solliciter en direct par la suite**

L'idée est d'avoir une adresse courriel généré pour chaque rendez-vous. Cette adresse aurait une validité limitée (quelques jours après le RDV ?)

## Technique

Je n'ai aucune idée de comment nous pouvons mettre ce schéma en place :)

## Référence

- https://forum.rdv-solidarites.fr/t/mails-recus-par-lequipe-technique-incluant-des-informations-personnelles/120/18

**Comment by n-b** [comment]
Duplique #1649, non? (Je suis à peu près sûr que oui, je ferme, criez-moi dessus sinon!)
