### ISSUE TITLE
Mettre à jour le compteur des RDV au moment d'ajouter ou retirer un agent d'un RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1895]
## Actuellement

Lorsque l'on retire ou ajoute un agent à un RDV, le compteur de rendez-vous à renseigner n'est pas mis à jour.

## Attendu

Mettre à jour le compteur des RDV au moment d'ajouter ou retirer un agent d'un RDV

**Comment by n-b** [comment]
Il me semblait qu’on était couvert pour ça: dans AgentsRdv, la relation `belongs_to :rdv` est `touch: true` et je crois qu’on avait vérifié ça. Il y a peut-être une autre raison pour laquelle la callback n’est pas appelée.
