### ISSUE TITLE
Utiliser le nom de naissance plutôt que le nom marital

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1898]
## Actuellement

> 
> Ayant commencé d’inscrire des patientes dans RDV solidarités, je me suis 
> aperçue que pour une femme mariée à qui le nom de naissance et le nom de 
> mariage ont été renseignés ,c’est le nom de mariage qui est retenu 
> principalement avec le nom de naissance entre parenthèses .
> 
> Or pour avoir suivi la réunion sur le DMP qui sera très prochainement 
> mis en place en 2022, c’est le nom de jeune fille qui va primer et 
> uniquement celui –ci.
> 
> Sur HORUS ,nous aurons donc le nom de jeune fille et sur RDV solidarités 
> nous aurons le nom de mariage.
> 
> Je crains pour ma part de grandes confusions à ce propos.

https://solidarites-sante.gouv.fr/systeme-de-sante-et-medico-social/masante2022/

## Attendu

Utiliser le nom de naissance en priorité.

:question:  **Nous pourrions échanger la position des deux noms, mais ça va peut-être créer de la confusion. Comment amener ce changement ?**

**Comment by n-b** [comment]
Mmm, en tout cas on parle de nom de famille (qui est le nom de naissance) et de nom d’usage (qui, si différent, est souvent le nom marital).

En réalité, je ne suis pas tellement sûr qu’il y ait une grande confusion entre ces deux présentations.
```diff
- Geraldine Bourgoin (Gaillard)
+ Geraldine Gaillard (Bourgoin)
```

**Comment by yaf** [comment]
J'imagine que le souci envisagé par cette personne, c'est d'avoir `Geraldine Bourgoin (Gaillard)` sur le système métier (iodas, horus, ...) et `Geraldine Gaillard (Bourgoin)` sur RDV Solidarités...

Et peut-être que cette crainte aura disparu lorsqu'il y aura un moyen de lier RDV aux applis métier (un lien vers ?) voir, à minima un champ contenant le numéro de dossier sur l'appli métier.

Je n'ai pas encore fait de ticket dans ce sens... Peut-être faut-il l'ajouter ?

**Comment by yaf** [comment]
Je ferme ce ticket qui n'en est plus une discussion à avoir, si le sujet reviens, qu'une demande de modification claire.
