### ISSUE TITLE
Nettoyage et unification des écrans d’accueil usager

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1901]
Contexte: #1865

Aujourd’hui, l’accueil sur le site et les premières étapes de la recherche sont gérés pas plusieurs routes dans `WelcomeController` et `LieuxController`. Dans #1865, @aminedhobb a mis en place une solution alternative, à l'origine pour gérer un système d’invitation externes, qui permet d’afficher le bon accueil en fonction du contexte fourni par l’usager. L’idée générale est qu’il s’agit moins d’« étapes » d’un formulaire de recherche que de différents « indices » provenant de plusieurs sources, permettant de savoir quoi proposer à l’usager. Celui-ci, en définitive, cherche à prendre rdv.

On a donc une notion de “contexte de recherche”, (`SearchContext` dans #1865), qui réunit les information d’usager courant, d’invitation, de géolocalisation, de lieu et de motif spécifiés, etc. Si les informations suffisent à afficher un choix de créneaux, c’est ce qu’on affiche; sinon, on demande les informations manquantes.

Le but de ce refactor est d’utiliser l’action `SearchController#search_rdv` de #1865 à la place des actions `WelcomeController#welcome_service` `#welcome_departement` et `#search` ainsi que `LieuxController#index` et `#show`. Dans #1865, j’évoque aussi le fait de faire du `SearchContext` un ActiveModel, pour gérer les erreurs et localisations de façon standard.

Au passage, on pourra jeter un coup d’oeil à `Users::CreneauxController`, qui ne sert aujourd’hui qu’à décaler un rdv (en file d’attente), mais qui a une logique similaire.

**Comment by yaf** [comment]
![usager-qui-prend-un-rdv](https://user-images.githubusercontent.com/42057/176979236-1d4c15de-8104-47d7-9359-590397777f27.jpeg)

**Comment by francois-ferrandis** [comment]
@yaf Merci pour ca schéma qui permet de s'y retrouver dans l'historique des changements de la page d'accueil ! :ok_hand:
