### ISSUE TITLE
Corriger les erreurs de chargement de l’agenda

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#1912]
Nous avons parfois des erreurs de chargement de l’agenda chez certains agents. Ça ne semble pas directement lié à un cas précis, les erreurs ne sont pas systématiques. Par ailleurs, ces erreurs ne remontent pas à Sentry.

![Capture d’écran 2021-12-07 112505](https://user-images.githubusercontent.com/139391/145049133-17004158-ccd7-4b5c-9a66-4f4bcecf0577.png)

Demandes:

* M. LE HELLOCO (G GUILLEMENOT, A ROSTREN)  Le 7 déc. 2021 à 12:22

C’est peut-être lié à la configuration spécifique à St-Brieuc? Ça semble n’arriver que sur cette zone.

**Comment by yaf** [comment]
Corrigé par #1913
