### ISSUE TITLE
Visualiser les plages d'ouvertures et les absences dans leur page index respective

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1919]
## Actuellement

Les plages d'ouvertures et les absences sont représentées sous forme d'un tableau textuel.

![Screenshot_2021-12-08 Vos plages d'ouverture - RDV Solidarités](https://user-images.githubusercontent.com/42057/145285224-599f30f7-8a65-42c8-a185-52ee83b32342.png)

Une partie importante des informations des plages d'ouvertures et des absences sont pourtant lié aux dates

## Attendu

Avoir une représentation visuel des plages d'ouvertures et des absences.
Peut-être en utilisant l'agenda en rendant les zones bleues (ou grises) cliquable, ou bien en explorant une autre façon de le faire.

**Comment by damienlethiec** [comment]
J'ai lancé une discussion sur #2856 @yaf @sebastiencarceles @NesserineZarouri

**Comment by yaf** [comment]
_Je réponds ici pour documenter ce ticket-là. Le #2856 ne concerne pas, pour le moment, le médico-social_

C'est une difficulté dans le médico social oui ! C'est pour ça que le #1919  est là :)

Je me permets de partager une copie d'écran de prod (puisque ce ne sont pas des données sensibles) :


![Screenshot 2022-10-05 at 21-24-19 Plages d'ouverture de Matthieu AUDEBERT (Service des solidarités territoriales) - RDV Solidarités](https://user-images.githubusercontent.com/42057/194145241-efe22041-1459-4e83-b78e-59bd278eba99.png)

Difficile de savoir si « les permanences » de cette personne sont corrects, sans trou, couvre bien les périodes imaginés... D'autant qu'il faut le faire pour tous les professionnels du lieu sans doute (c'est une page qui manque aussi pour le moment)

Un cas d'utilisation : 
En tant que coordinateur/secrétaire d'un lieu, ou d'une MDS, et je dois m'assurer que notre « offre de service » correspond à notre politique départemental.

Autre cas d'utilisation qui est : 
En tant que professionnel, j'aimerais savoir dans quel lieu se trouve ma permanence dans les jours à venir (pour savoir où je vais travailler)


Après, ce n'est pas une super priorité, donc si tu veux laisser de côté, c'est ok aussi. Mais ce ticket est à garder, merci :)

**Comment by damienlethiec** [comment]
Ok, je vois mieux le besoin ! Est-ce que dans un premier temps je peux essayer de mettre en place une deuxième vue (vue calendrier) qui ne ferait pas perdre cette vue là à ceux qui ont moins de plage et s'en sorte bien comme ça ? Histoire de ne pas les perturber ? Mon idée pour cette vue : reprendre le full_calendar en n'affichant que les plages d'ouverture. Tu vois une meilleur idée ?

**Comment by yaf** [comment]
> Ok, je vois mieux le besoin ! Est-ce que dans un premier temps je peux essayer de mettre en place une deuxième vue (vue calendrier) qui ne ferait pas perdre cette vue là à ceux qui ont moins de plage et s'en sorte bien comme ça ? Histoire de ne pas les perturber ? Mon idée pour cette vue : reprendre le full_calendar en n'affichant que les plages d'ouverture. Tu vois une meilleur idée @yaf ?

Oui, ça semble une bonne idée, ça aide à l'accompagnement du changement.
