### ISSUE TITLE
Afficher une seule fois les agents pouvant être référent

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#1998]
## Actuellement

Étant donné un agent qui est associé à plusieurs organisations ; 
Lorsque l'on affiche la liste des agents pouvant être référent d'un usager, cet agent apparaît 2 fois

![Screenshot 2022-01-12 at 15-10-13 Modifier les référents de Patricia DUROY - RDV Solidarités](https://user-images.githubusercontent.com/42057/149155962-01860ef1-665e-4520-859a-c3ad6c8ed10c.png)

## Attendu

L'agent ne devrait être affiché qu'une fois.

Au passage, cette liste n'est pas paginé, ça fait potentiellement une très grosse requête et un affichage long, il serait préférable de mettre en place la pagination.

**Comment by n-b** [comment]
J’ai regardé ça en même temps que #2115, et j’arrive pas à reproduire. En fait, je ne vois pas comment la requête actuelle pourrait produire des doublons, les jointures sont dans une subquery, ça a l’air propre.

**Comment by n-b** [comment]
Compris: c’est lié au service secrétariat. Si le current_agent est du service secrétariat, la query est un `joins(:organisation)`, et on a des doublons.

PR en approche.
