### ISSUE TITLE
Construire des vues d’aperçu des sms 

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#2050]
Comme `rails/mailers`, mais pour les sms. Aujourd’hui, pour expérimenter les formulations de sms, on passe par les tests unitaires, ce qui fonctionne, mais ne permet pas d’itérer rapidement et de voir où tombe la limite des 160 caractères.

Il faudrait une vue listant les previews, et un affichage court simulant le texte reçu, avec la limite à 160.

C’est un peu lié à #1431, puisqu’il s’agit de limiter la consommation de sms.

Demandes:
* Le 25 janv. 2022 à 23:15, CASTAING V

**Comment by yaf** [comment]
Est-ce que l'idée serait d'avoir un aperçu coté équipe ou bien visible coté agent aussi ?
Les SMS étant contextuel à un motif et une adresse, peut-être que lié à un RDV, ça serait intéressant ? 

C'est un peu le doigt dans la personnalisation des messages, et après tout, pourquoi pas :)
