### ISSUE TITLE
Affiche le lieu qui avait été sélectionné quand on revient au filtre de la recherche de créneaux agent

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2054]
## Actuellement

Lorsque je mets un lieu en filtre dans la recherche de créneau coté agent, que j'affiche les créneaux disponibles, puis revient aux filtres, le lieu n'est plus sélectionné.

![Screenshot 2022-01-27 at 08-16-40 RDV Solidarités](https://user-images.githubusercontent.com/42057/151310041-f8a08bd3-5c56-4fc5-ae56-83c3e5cb7c62.png)

![Screenshot 2022-01-27 at 08-16-50 RDV Solidarités](https://user-images.githubusercontent.com/42057/151310052-8c5e7cb9-56b4-4c4d-967e-ec9bb71e2fa8.png)

![Screenshot 2022-01-27 at 08-16-58 RDV Solidarités](https://user-images.githubusercontent.com/42057/151310065-309979c8-d7de-4813-ac19-825a917f3a2f.png)

## Objectif

Maintenir le lieu dans les filtres.

**Comment by n-b** [comment]
Je vais regarder, je pense que c’est lié à ce que que change dans #2052
