### ISSUE TITLE
Affiner les durées et intervalles par défaut des créneaux d’un motif

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#2138]
Suite à une discussion sur l‘affichage des créneaux (https://github.com/betagouv/rdv-solidarites.fr/pull/2132#discussion_r802685972) et un échange avec le département 77.

Deux points d’améliorations possibles:
1. Il y a parfois besoin d’un intervalle entre deux Rdv (pause, préparation, ou debrief interne…). Aujourd’hui, ce n’est pas pris en compte dans le calcul de créneau: si un Rdv termine à 15h00, le suivant peut commencer à 15h00. C’est contourné par les agents en définissant des “mini plages d’ouvertures” qui durent exactement le temps d’un Rdv, et en décalant ces plages d‘ouverture du temps de pause. (C’est le cas dans le 77)
2. Si on est _actuellement_ dans une plage d’ouverture qui se trouve être libre, un Rdv ne peut pas commencer maintenant, mais doit attendre le prochain _slot_ qui tombe pile sur une durée par défaut du Rdv après le début de la plage d’ouverture. On peut alors se retrouver à attendre par exemple 59 minutes parce que la plage d’ouverture a commencé il y a une minute. (Évidemment, dans le monde réel, les secrétaires et agents ne font pas ça.) (J’espère.)

On pourrait donc:
1. Ajouter un intervalle minimum dans la configuration du motif. Ça veut dire que pour l’usager, le Rdv dure 50 minutes, mais que pour l’agent, 60 minutes sont réservées.
2. Définir un “pas” minimal de début de rendez-vous, par exemple toutes les 5, 10 ou 15 minutes, configurable par Motif.

C’est aussi un peu lié à #1908.

Demandes:
* A Perriot, A. Bard, V. Castaing, 31 janvier 2022 15:40

**Comment by yaf** [comment]
Je ne suis pas sûr de comprendre le 2. Tu as le processus qui permettrait de se retrouver dans cette situation ? J'ai en tête que le calcul de créneaux se fait à partir de la prochaine minutes (ou 5 ?), et que les créneaux disponibles sont calculé à partir de là. Mais un truc m'échappe sans doute :thinking:

**Comment by n-b** [comment]
Oui, c’est exactement ce dont on a parlé ([et qu’on a changé, du coup](https://github.com/betagouv/rdv-solidarites.fr/pull/2132#discussion_r802927286)) dans #2132. Maintenant, c’est en dur un pas de 5 minutes; avant il y a 8 jours, on pouvait perdre, au pire, `default_duration_in_min - 1.minute` .

**Comment by yaf** [comment]
Ça me semble un pas si simple. Et après discussion avec les référentes en cercle plus large, elles n'en ressentent pas le besoin. La pause peut être incluse dans la durée d'un motif (on pense à un RDV de 45 minutes, on dit qu'il dure 50 minutes pour avoir 5 minutes de transition).

Je ferme donc ce ticket.
