### ISSUE TITLE
Afficher des adresses moins longues

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2159]
## Actuellement

Les adresses des lieux comportent des infos dupliquées : en plus des infos qui suffiraient à poster une lettre (numéro et nom de rue, nom de ville, code postal) il y a le numéro du département, le nom du département en toutes lettres, et le nom de la région.

Par exemple : 15 Allee Nelson Mandela, Tremblay-en-France, 93290, 93, Seine-Saint-Denis, Île-de-France

Cette duplication n'est pas nécessaire, et augmente les coûts en allongeant les sms.

## Objectif

L'adresse donnée en exemple deviendrait 15 Allee Nelson Mandela, Tremblay-en-France 93290.
Cela permettra de faire des sms plus court, et d'afficher des adresses plus simples.

## Technique

Il faudra sans doute modifier la manière dont on enregistre les adresses données par la BAN dans `app/webpacker/components/places-inputs.js`.

Idéalement, ça serait bien de rétroactivement corriger les adresses déjà persistées dans la colonne `lieux.address`, et éventuellement dans `users.address`.

**Comment by yaf** [comment]
Ne pas utiliser l'adresse complète 

https://github.com/betagouv/rdv-solidarites.fr/blob/0db7eb0f446e6b568392d57aa2cb4b6e142c65e4/app/models/concerns/rdv/address_concern.rb#L14

et 

https://github.com/betagouv/rdv-solidarites.fr/blob/production/app/sms/users/rdv_sms.rb#L41

**Comment by yaf** [comment]
Il faudra peut-être en profiter pour ne pas afficher l'adresse si c'est un motif de RDV à domicile... (c'est peut-être déjà le cas ?)

**Comment by rebeccadumazert** [comment]
> Il faudra peut-être en profiter pour ne pas afficher l'adresse si c'est un motif de RDV à domicile... (c'est peut-être déjà le cas ?)

**Comment by yaf** [comment]
Il y a peut-être moyen de traiter aussi #2277 en même temps ?

**Comment by yaf** [comment]
> YannickF.
> [11:37](https://mattermost.incubateur.net/betagouv/pl/c656c3papidnfkr4fm1ahd1u7e)
> 
> [@Rebecca Dumazert]() pour les histoires d'adresses
> [11:37](https://mattermost.incubateur.net/betagouv/pl/gxdtjudydfg9bjnchxprc4knpo)
> 
> Il y a plusieurs chose :
> [11:37](https://mattermost.incubateur.net/betagouv/pl/wxnwnmeg9prbffae3zhj9r96yy)
> 
> La doc de l'API pour la BAN : https://adresse.data.gouv.fr/api-doc/adresse
> [11:38](https://mattermost.incubateur.net/betagouv/pl/iicmp8iio3ffmg3rcgw88gxjda)
> 
> Le js qui fait l'appel : app/webpacker/components/plages-input.js
> [11:38](https://mattermost.incubateur.net/betagouv/pl/cgiz6qr17jyxbbcf5781uio49y)
> 
> L'adresse est inséré dans le SMS à la ligne 57 du fichier app/sms/users/rdv_sms.rb
> [11:39](https://mattermost.incubateur.net/betagouv/pl/9ahry475u3dex8mm6m78hpnhwy)
> 
> Voir app/models/concernes/rdv/address_concern.rb
> [11:40](https://mattermost.incubateur.net/betagouv/pl/yfaqrtxoktnitdyzkh17mx6m5o)
> 
> Rdv.joins(:motif).where("motifs.location_type": "public_office").sample(1).first.address_complete pour voir les adresses en base de données. Parfois elles sont retouché par les utilisateurs, parfois c'est l'adresse que l'on récupère de la BAN, (donc une trop grosse adresse) 
> [11:43](https://mattermost.incubateur.net/betagouv/pl/9jaap9nm6jg7mqzh5b9w97wxmh)
> 
> La surface du problème c'est que l'adresse est trop longue dans le SMS, ça fait un coup de SMS trop important. On paie un « SMS » pour 160 caractères. Si ça dépasse, on paie 2 SMS...
> [11:44](https://mattermost.incubateur.net/betagouv/pl/uo3urfe863df8k7p7uxoh3d47w)
> 
> Le problème de fond, c'est que nous utilisons la BAN comme source de donnée d'adresse. C'est pratique pour avoir la longitude et la latitude qui nous servent dans la sectorisation pour faire des rapprochements géographique (ex : c'est quoi la MDS la plus proche de chez moi). Mais c'est tout (je crois) !
> YannickF.
> [11:49](https://mattermost.incubateur.net/betagouv/pl/4ngzegpjgpycxyr96du7woktgy)
> 
> Mais ça fait peut-être un trop gros changement... Cependant, il faudra y penser à un moment je pense
> [11:50](https://mattermost.incubateur.net/betagouv/pl/99uwrhzwmidudjz3et3xtnpzmy)
> 
> Peut-être en laissant une saisie libre, et en faisant une sorte de validation de l'adresse par la ban après coup... 
> YannickF.
> [11:56](https://mattermost.incubateur.net/betagouv/pl/ankpbabpqtyg8d5epywafeu8ia)
> 
> Peut-être que le mieux serait de pouvoir enregistrer la ville, le code postal, le numéro de rue et le nom de la rue dans des champs spécifique (qui peuvent être masqués). Nous pourrions utiliser ces champs pour faire une adresse courte (short_address) dans le address_concern qui prendrais le numéro de rue, le nom de rue et la ville et c'est tout.
