### ISSUE TITLE
Masquer les champs sociaux et le champ remarques de la fiche usager

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2192]
## Actuellement

En plus des informations d'identité et des moyens de contacts, nous avons des champs pour récolter des remarques et des informations sociales.

![Screenshot 2022-02-28 at 15-24-25 Léa DUPONT - RDV Solidarités](https://user-images.githubusercontent.com/42057/155999481-ae9911ca-7ac4-4497-a958-5b9de76446da.png)

## Objectif

Réduire les champs de qualification d'un usager.

Nous pouvons ajouter un élément de configuration (dans le module de configuration, un nouveau menu ?)

![Screenshot 2022-02-28 at 15-27-31 RDV Solidarités](https://user-images.githubusercontent.com/42057/156000093-17d9db8d-9c2b-45b2-a88e-34a5aa8c6598.png)

Il y a plusieurs manières de voir ça :
- soit un menu autour de l'usager (quels autres éléments de configuration usager nous pourrions mettre ici ?)
- soit un menu sur le paramétrage de l'interface graphique de RDV-Solidarités (dans lequel nous pourrions mettre aussi le faire d'afficher les samedis et/ou les dimanches dans l'agenda par exemple ...)

:warning: ne pas supprimer les données pour le moment. Nous pourrions avoir besoin de récupérer certaines informations.

:candy: en profiter pour rapatrier les données qui sont dans la table `user_profiles` (`logement` et `notes`) sur la fiche usager. Pour la migration, prendre le logement donc le champ `updated_at` est le plus récent et pour le champ `notes` faire une concaténation. Ça sera plus simple à gérer ensuite.

ref #1814

**Comment by victormours** [comment]
> Il y a plusieurs manières de voir ça :
- soit un menu autour de l'usager (quels autres éléments de configuration usager nous pourrions mettre ici ?)
- soit un menu sur le paramétrage de l'interface graphique de RDV-Solidarités (dans lequel nous pourrions mettre aussi le faire d'afficher les samedis et/ou les dimanches dans l'agenda par exemple ...)


Je penche plutôt pour la deuxième option, et je pense même que ce paramétrage plus général de l'interface graphique n'a pas besoin d'être accessible en dehors du superadmin pour le moment : on ne va pas avoir d'utilisateurs qui changent de type d'usage entre social/pas social (par exemple : ça n'est pas utile de proposer cette option de configuration aux conseillers numériques). Autrement tant qu'on n'a pas le besoin d'une interface utilisateur pour changer ça, n'en proposons pas. :)

**Comment by victormours** [comment]
D'accord, je comprends mieux. Du coup ça serait au niveau du territoire qu'on aurait cette option ?

**Comment by yaf** [comment]
oui
