### ISSUE TITLE
Éviter de changer d’organisation en affichant la fiche d’un usager depuis la recherche

### ISSUE THREAD

**Issue by n-b** [betagouv/rdv-solidarites.fr#2195]
Si un usager appartient à plusieurs organisations, il arrive que le lien vers sa fiche depuis la recherche emmène vers une autre organisation que celle affichée actuellement. Il faut rester sur la même organisation. (Le contenu de la fiche usager dépend de l’organisation actuelle: seuls les rendez-vous de l’organisation actuelle sont affichés)

<img width="1222" alt="Capture d’écran 2022-03-01 à 11 21 18" src="https://user-images.githubusercontent.com/139391/156151346-cdb9db12-680e-4c2d-91c7-b7cbaee0de70.png">

Demandes:

* Le 22 févr. 2022 à 14:53, Cufay C

**Comment by yaf** [comment]
J'ai commencé à regarder à partir d'un cas signalé dans le 92.

L'usager a effectivement 2 organisations. Et chaque organisation est liée à un territoire différent !

Ce qui est surprenant, c'est que la création du lien se base sur l'organisation courante. Aussi, ça signifierait que le bug et lié à une confusion sur la récupération de l'organisation courante ?

Ce bug n'est pas vraiment reproductible. Même en prod, je n'ai pas réussi à retombé sur le cas à chaque fois... Disons plutôt, je l'ai constaté en arrivant en prod. Puis, au fil des explorations, il a « disparu ». La seule chose que je n'ai pas fait en prod c'est de modifier les données depuis une orga ou de l'autre pour voir si ça a une conséquence.
