### ISSUE TITLE
Rendre plus visible et compréhensible la recherche d'un RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2200]
## Actuellement

Pour créer un RDV coté professionnel, il y a
- le clic dans l'agenda
- la recherche de créneau depuis l'agenda
- la recherche de créneau depuis une fiche usager

Certaines personnes ne connaissent pas la recherche de créneau ou ne la retrouve pas (bouton peu visible).

Sur mobile, le clic sur l'agenda n'est pas facile (il faut rester longtemps appuyé dessus il parait ?).

Il n'y a aucun moyen de rentrer dans le tunnel de prise de rendez-vous en dehors de ces points.

## Objectif

Rendre le chemin de création d'un RDV plus visible et plus simple.

- [ ] Renommer le bouton « trouver un créneau » en « Trouver un RDV »
- [ ] Ajouter le bouton « Trouver un RDV » de la page agenda vers le menu (pour qu'il soit visible de toutes les pages)
- [ ] Faire en sorte que le bouton « Trouver un RDV » soit contextuel : si je suis sur une fiche usager, présélectionner l'usager comme c'est le cas aujourd'hui avec le bouton de trouver un créneau depuis la fiche usager.
- [x] ~~supprimer le bouton trouver un RDV de la page agenda~~
- [x] ~~supprimer le bouton trouver un RDV de la fiche usager~~
- [ ] Ajouter un bouton/lien dans la page de recherche de créneau pour « prendre un RDV en dehors des plages d'ouvertures » pour entrer directement dans le tunnel de prise de RDV sans présélectionner la date et l'heure.

_Nous allons maintenir les boutons existant pour le moment_

**Comment by victormours** [comment]
@yaf 👍  Ça m'a l'air très bien

j'ai juste un petit doute sur la suppression du bouton "Trouver un RDV" de la page agenda. Il semble qu'il est très utilisé et que ça va chambouler pas mal d'usages si on le supprime. Est-ce que ça vaut pas le coup de le laisser ? Il fera peut-être un peu doublon avec celui dans le menu de gauche, mais est-ce que c'est si grave ?

**Comment by yaf** [comment]
J'ai mis le 83 en tag, car Irène avait évoquée la solution de pouvoir entrer dans le tunnel de prise de RDV directement pour pouvoir poser un RDV plus facilement depuis un smartphone.
