### ISSUE TITLE
Cacher les options de réservation en ligne pour les CNFS

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2243]
Il va y avoir 2 paliers pour le déploiement de rdv Solidarités aux CNFS : 
- 1er palier déployé en mars :  RDVS sera uniquement utilisé comme outil interne, et la réservation de RDV en ligne ne sera pas ouverte au public
- 2e palier déployé en avril ou mai : ouverture de la réservation en ligne

Pour le moment, on veut donc simplifier l'interface, et ne pas proposer la réservation en ligne aux cnfs.
La PR https://github.com/betagouv/rdv-solidarites.fr/pull/2206 a déjà commencé ces changements.

**Comment by yaf** [comment]
fermé par #2244
