### ISSUE TITLE
Cohérence entre le texte et la définition de l'indisponibilité

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2252]
## Actuellement

Lorsque l'on pose une indisponibilité du 14 mars 2022 à 9 h jusqu'au 17 mars 2022 18 h (par exemple). L'affichage rempli l'espace entre ces deux bornes, mais le texte nous dit autre chose (tranche de 9 h à 20 h). Il y a une incohérence.

![Screenshot 2022-03-10 at 21-46-14 Votre agenda - RDV Solidarités](https://user-images.githubusercontent.com/42057/157751827-b65953fc-ac4b-4ef2-a7a6-ed7a42270403.png)

## Objectif

Rendre cohérent l'affichage avec la définition créée. Voir autour de la méthode `all_occurrences_for` dans le fichier `app/models/concerns/recurrence_concern.rb`

**Comment by sebastiencarceles** [comment]
Quel est le résultat attendu ici @yaf ? Est-ce que :
- on aimerait que les colonnes grises dans l'agenda s'arrêtent à 18h ?
- ou bien c'est le tooltip (qui indique 9h-18h) qu'il faut modifier pour qu'il affiche 9h-20h ?
Merci

![image](https://user-images.githubusercontent.com/1193334/187895817-ff467abf-2469-4d1b-b466-7c700cad01d3.png)
