### ISSUE TITLE
Formater les anciennes adresses de lieux pour qu'elles soient plus courtes

### ISSUE THREAD

**Issue by rebeccadumazert** [betagouv/rdv-solidarites.fr#2293]
## Actuellement

Les adresses des lieux déjà existants comportent des infos dupliquées : en plus des infos qui suffiraient à poster une lettre (numéro et nom de rue, nom de ville, code postal) il y a le numéro du département, le nom du département en toutes lettres, et le nom de la région.

Par exemple : 15 Allee Nelson Mandela, Tremblay-en-France, 93290, 93, Seine-Saint-Denis, Île-de-France

Cette duplication n'est pas nécessaire, et augmente les coûts en allongeant les sms.

## Objectif

Une issue a été mise en production afin que les futures adresses renseignées soient dans le bon format. L'objectif de cette issue est de venir modifier les adresses déjà existantes qui contiennent des informations dupliquées et qui augmentent le prix des sms.

**Comment by n-b** [comment]
C’est la suite de #2159  qui a été fermée par #2292 :)
