### ISSUE TITLE
Restreindre les invitations de nouveaux agents pour les CNFS

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2312]
Pour les cnfs, c'est très pratique de pouvoir donner accès à leur agenda à un collègue, notamment aux gens qui gèrent l'accueil de leur france service.
Par contre, on veut les empêcher d'inviter d'autres agents non-cnfs qui pourraient organiser des rdv (et donc nous coûter des sms).

Pour l'ajout de nouveaux agents, on veut donc leur permettre d'inviter uniquement des agents pour le service secrétariat, et non-admins.

Pour le moment, ce fonctionnement est spécifique aux cnfs. A terme, on pourra voir si on veut que ça soit configurable.

**Comment by yaf** [comment]
J'ai peur que l'on trouve ici une réponse étrange à un problème simple.

Pourquoi créer des comptes agents à ces personnes ? Elles devraient uniquement pouvoir poser des RDV pour les CNFS non ?
J'ai l'impression que c'est un peu comme ouvrir au public, sauf qu'on voudrait que le public soit restreint.


Il faut peut-être repartir du problème pour trouver la meilleure solution.

En s'inspirant des invitations de Data.insertion, nous pourrions probablement proposer des motifs qui serait accessible exclusivement aux personnes qui ont l'url (avec un token ?). Ça pourrait amorcer une évolution de RDV solidarités qui permettrait à un agent de proposer à des personnes de prendre RDV avec lui (un peu calendso/calendly je dirais ?)

Dispo pour discuter de ça jeudi si besoin.
