### ISSUE TITLE
Ne pas préremplir la liste des agents

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2338]
## Actuellement

Dans les listes déroulantes, nous n'affichons que les 10 premiers résultats. L'idée est d'inciter les personnes à saisir les premières lettres.

![Capture d’écran de 2022-04-05 21-06-55](https://user-images.githubusercontent.com/42057/161831106-28810caf-3c2d-46c2-9fe0-f175ea655620.png)

Le souci, c'est que l'affichage donne l'impression qu'il manque des données.

## Objectif

Afficher le champ de recherche, avec une liste vide.

Il y a sans doute à voir si d'autres listes pourrait se retrouver dans cette situation.

Utiliser le « commencer à taper pour rechercher » qu'il y a dans le tunnel de prise de RDV pour la recherche usager.

Et prendre en compte le nombre d'agents peut-être ? Comme dit @victormours, s'il y en a peu, alors afficher la liste directement.

Nous pourrions dire que 
- si moins de 10 agents, alors on affiche la liste des agents
- si plus de 10 agents, alors on affiche le texte « commencer à taper pour rechercher »

**Comment by victormours** [comment]
Pour les organisations avec peu d'agents (c'est le cas pour la plupart des cnfs), il vaudrait mieux ne pas avoir de champs de recherche et avoir tous les noms

**Comment by yaf** [comment]
Nous avons exploré la résolution de ce ticket en cherchant à ajouter une condition sur le nombre d'agents pour savoir s'il faut les afficher ou non.

Cela nous amène à faire une requête supplémentaire pour connaitre le nombre d'agents avant l'affichage.

Ce changement ergonomique apporterait plus de confort pour les agents du Médico Social qui n'ont pas l'habitude d'utiliser le champ de recherche (c'est le cas de combien d'agent, peut-être tous ?).

Nous préférons laisser ce ticket de côté pour le moment.

 Il serait intéressant de faire des tests utilisateurs sur cette zone et ces cas d'usages. 
**Peut-être que nous pourrions trouver un bien meilleur moyen de naviguer sur les agendas d'autres agents !** D'ailleurs, pourquoi naviguer sur les agendas des autres : pour trouver des créneaux. Fonction accessible par le bouton « trouver un RDV »...

(cc @NFontelle )
