### ISSUE TITLE
Rdvs Collectifs : Renseigner les participations individuellement

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2353]
## Actuellement

La participation ou non d'un usager à un rdv est stockée dans l'état du rdv. Si l'usager est absent, c'est directement dans la colonne `rdvs.status` qu'on le persiste.
Pour le suivi des stats et pour les rendez-vous collectifs d'information sur le rsa, les référentes ont besoin de pouvoir indiquer la présence de chaque participant.

## Objectif

Pour les rdvs collectifs, ce système ne marche pas si certains participants sont absents et que les autres sont présents (ce qui risque d'être la plupart des cas).

Au moment de renseigner le statut du rdv pour un rdv collectif, il faudrait donc permettre d'indiquer la participation pour chaque usager.

Il faudra veiller à ne pas casser ou fausser l'affichage des statistiques. 🙃 

Un découpage possible de ce ticket pourrait être de d'abord faire la migration de l'info vers une colonne de la table rdvs_users (aka participations) en gardant la même interface pour les rdvs individuels, et ensuite de faire une nouvelle interface pour les rdvs collectifs.

**Comment by yaf** [comment]
Lors de nos discussions lors des précédents atelier, les référentes étaient très motivées pour ne pas faire de distinction entre les RDV individuel et collectif.

Il y a déjà un ticket sur le sujet https://github.com/betagouv/rdv-solidarites.fr/issues/2235

duplicate #2235 ?

**Comment by victormours** [comment]
Effectivement c'est un doublon, je ferme celui-ci
