### ISSUE TITLE
Dupliquer les plages d'ouvertures sur d'autres agents (ou plage d'ouverture multi-agent)

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2368]
## Problème

Les plages d’ouvertures sont liées à un agent. Certaines plages sont partagées par plusieurs agents. Ces plages correspondent plutôt à une sorte de permanence, de temps de travail, de disponibilité, d’un type de personnes.

## Solution

La meilleure option serait de pouvoir ouvrir une plage à plusieurs agents.

Une autre solution serait de pouvoir copier une plage d’un agent à l’autre.

# Capturé lors de la discussion de backlog grooming :

Il y a deux interprétations possibles de ce problème :
- soit on essaye de faire des rdv en binôme, où deux agents interviennent ensemble, et dans ce cas c'est en priorité au niveau de la prise de rendez-vous qu'il faut faire des choses
- soit il s'agit de faciliter la création en masse de plages d'ouverture, et dans ce cas il faut regarder plus largement comment la navigation est faite, puisqu'elle est tout le temps centrée sur un agent à la fois

**Comment by yaf** [comment]
> Lorsque un médecin et une puéricultrice interviennent ensemble sur une même plage d'ouverture, il faut créer en double la plage d'ouverture sur chaque agenda.
> Serait-il possible d'ajouter un autre agent sur la création d'une plage d'ouverture pour que cela la créée automatiquement sur l'agenda de l'agent ajouté ?

-- Magalie (22)

**Comment by yaf** [comment]
> Bonjour,
> 
> je valide totalement cette proposition !
> 
> Dans l'attente, certains pourraient-ils nous dire comment ils ont contourné cette difficulté ?
> 
> Merci d'avance.

-- Christelle (64)

**Comment by yaf** [comment]
C'est une piste de résolution intéressante : pouvoir créer une plage d'ouverture pour plusieurs agents.

Ça signifie aussi qu'il faudrait considérer que ces agents ne sont qu'un, et donc que ça n'ouvre pas 2 rendez-vous sur la même heure, mais bien un créneau pour voir ces deux agents. Il faudra aussi posé le rendez-vous sur les deux agendas.

Est-ce que nous pourrions limiter à un binôme ?

Il faudra aussi trouver un moyen de bien préciser que ce n'est pas une plage d'ouverture commune (où les créneaux serais dédoublé).

C'est une piste intéressante, merci beaucoup.

**Comment by yaf** [comment]
> Oui limiter à 2 agents c’est bien
> Il faut juste créer la même plage d’ouverture sur les 2 agendas si on a la possibilité d’ajouter un 2eme agent

-- Magali (22)

**Comment by yaf** [comment]
La résolution n'est pas simple.

Aujourd'hui, une plage d'ouverture est liée à 
- un agent
- un lieu
- des motifs.

C'est aussi (surtout ?) un outil indispensable pour la création des créneaux disponible (pour l'accès par les usagers ou bien, coté agent, quand on passe par la recherche de créneaux).

Je me dis que nous pourrions associer une plage à un lieu, et ajouter des agents, mais ça ne résoudrait pas le problème puisqu'il faudrait faire la différence entre le faire que deux agents sont disponibles sur la même plage d'ouverture (et donc propose des créneaux en double) Et le fait que ces deux agents travaillent « ensemble ».


Comment faites-vous aujourd'hui @DEP22 @Christelle-Cufay-64  ?

**Comment by yaf** [comment]
> Ces créneaux d'ouverture concernent un binôme d'agent, donc sans se poser de question quand on crée une plage pour l'un, on duplique la plage pour l'autre (à l'image de ce qui est fait pour les RDV avec plusieurs agents)

-- Magali (22)

**Comment by Holist** [comment]
On a un besoin équivalent coté RDV-Insertion dans le cadre de l'expérimentation FT.
