### ISSUE TITLE
Page d'erreur 422 lors d'une erreur de validation sur la fusion d'usagers

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2391]
Bug décrit dans le mails de Clarisse Beauvois du 19/04 : lors d'une erreur de validation sur la fusion de deux usagers, on affiche la page de 422 par défaut de Scalingo, à la place d'un message d'erreur de validation.

**Comment by yaf** [comment]
À priori, c'est lié au #1762 
duplicate ?
