### ISSUE TITLE
Affichage du calendrier dans des timezones en dehors de la métropole

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2393]
Bug : Pour les agents qui ne sont pas sur la timezone de la métropole, les rdvs sont décalés dans le calendrier.

voir https://zammad10.ethibox.fr/#ticket/zoom/18

**Comment by yaf** [comment]
Voir comment jouer avec les timezones dans https://fullcalendar.io/

Ou bien c'est un problème plus général ?

**Comment by francois-ferrandis** [comment]
Après investigation, voici le comportement actuel lorsque le navigateur déclare la timezone "Indian/Reunion" (GMT+04:00).

1. Lorsqu'on crée une plage sur le calendrier en sélectionnant par exemple 16h30 -> 17h, **FullCalendar prend bien en compte l'offset lié à la timezone détectée**, et notre JS redirige alors vers `Admin::RdvWizardStepsController#new` avec en paramètre GET `{ starts_at: "2022-05-04T16:30:00+04:00" , ... }`. 
2. Le serveur reçoit donc la string `"2022-05-04T16:30:00+04:00"`. Cette valeur représente l'heure sélectionnée de façon correcte, elle correspond bien à 16h30 à la réunion, ou à 12:30 UTC, ou à 14:30 à Paris en heure d'été (GMT+02:00).
3. Le contrôleur passe les paramètres à `Admin::RdvWizardForm::Step1`, et à ce moment là un objet `Rdv` est instancié à l'aide de la valeur en string :  https://github.com/betagouv/rdv-solidarites.fr/blob/1f719d3517a0b4034a60235d511fb67fdf1be597/app/form_models/concerns/admin/rdv_wizard_form_concern.rb#L30
4. Rails détecte alors que la colonne `starts_at` est de time Postgres `datetime` **sans timezone**, c'est à dire que c'est un timestamp UTC sans aucune information d'offset ou de timezone. C'est pour cette raison que lorsque la valeur `2022-05-04T16:30:00+04:00` est assignée à l'attribut `starts_at` de l'objet de classe `Rdv`, les informations d'offset sont utilisées puis perdues, et on a :
```ruby
@rdv.starts_at
# => 2022-05-04 14:30:00 +0200
```
5. Quoi, comment ça 14:30+02:00 ? Et oui, ce que je ne vous ai pas dit c'est que **notre appli est [configurée](https://github.com/betagouv/rdv-solidarites.fr/blob/1f719d3517a0b4034a60235d511fb67fdf1be597/config/application.rb#L24) pour utiliser par défaut la timezone "Paris".** Et donc à partir de cette étape, c'est l'heure de Paris qui va être affichée et manipulée, puisque nous avons perdu les informations d'offset originales ! 
6. On arrive donc sur le formulaire, et il affiche l'heure de Paris : 
![Screenshot from 2022-04-26 20-26-14@2x](https://user-images.githubusercontent.com/6357692/165347931-4029cbfc-56e6-4ea8-af3d-07cfcdd8c560.png)
On peut supposer que lorsque la personne arrive sur cet écran, elle corrige le 14:30 et 16:30, car elle croit manipuler l'heure de la Réunion, alors qu'en réalité c'est l'heure de Paris qu'elle saisit !
![Screenshot from 2022-04-26 20-27-31@2x](https://user-images.githubusercontent.com/6357692/165348090-3278c028-43c1-4b95-96c0-b9bfd0f69fa6.png)

Solutions possibles : 
* Associer à chaque compte une timezone et [l'utiliser](https://stackoverflow.com/a/32451148/2864020) + continuer à stocker les heures de rdv en UTC pur
* Associer une timezone à chaque rdv afin de disposer d'informations plus explicites, mais je pense que ça complexifie le code à pas mal d'endroits

À prioriser en backlog grooming je pense !

**Comment by yaf** [comment]
Merci beaucoup pour l'analyse très complète ! :bow:

**Comment by victormours** [comment]
On a dû faire un rollback parce que ça créait un soucis sur le tooltip dans le calendrier

**Comment by victormours** [comment]
Autre ticket zammad concerné : https://zammad10.ethibox.fr/#ticket/zoom/435
