### ISSUE TITLE
Pourquoi il manque parfois des villes dans l'export statistique alors que l'usager à une adresse ?

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2467]
## Actuellement

Dans l'export statistique, nous avons la ville lorsqu'il n'y a qu'un seul usager au RDV.

Sauf dans certains cas où pourtant l'usager a bien une adresse renseignée.

## Objectif

Enquêté sur pourquoi il manque parfois des villes dans l'export.
Sans doute lié au mécanisme de mise à jour ?
Faut-il envisager d'avoir l'adresse sur plusieurs champs ?

Nous pourrions tirer aussi sur la question de notre relation à la BAN. Très forte aujourd'hui, pour un usager assez réduit il me semble.

**Comment by sebastiencarceles** [comment]
J'ai enquêté sur ce sujet et voici mes observations.

# Pourquoi la ville est vide dans l'export

On a des users en base avec une `address` mais sans `city_name`. Or c'est le `city_name` qui est utilisé dans l'export.

Je n'ai pas pu le vérifier sur la prod parce que je n'ai pas les accès, mais ça me semble assez indiscutable. 

- [ ] Il serait intéressant de regarder combien de personnes ça concerne, pour déterminer s'il est préférable de patcher les données à la main ou s'il faut trouver une solution plus robuste.

# Pourquoi le `city_name` du User est vide

Quand on regarde dans `places-input.js`, on voit que le champ `city_name` du formulaire est renseigné à partir des données retournées par la BAN.

# Hypothèse

Pour les Users concerné·es, l'agent·e saisit une adresse inconnue de la BAN et valide le formulaire.

Il est même possible que l'adresse soit reconnue par la BAN, mais si l'agent·e ne sélectionne pas l'adresse proposée dans le dropdown, alors le `city_name` du formulaire n'est pas peuplé : 

![image](https://user-images.githubusercontent.com/1193334/188579777-23fa6e13-e6a6-4d46-92d8-f9a587d0857a.png)

Après validation du formulaire, on a donc bien un·e User avec `address` mais sans `city_name` : 

![image](https://user-images.githubusercontent.com/1193334/188579956-4d2da6c2-aea1-4243-bb49-6a989ac1fb7e.png)

# Recommandations

Si le nombre de Users concerné·es est anecdotique, je recommande de laisser comme ça et de corriger manuellement les données.

Si le nombre de Users concerné·es est important (à voir comment placer le seuil), je recommande de revoir le formulaire et son fonctionnement : 
- soit l'agent·e sélectionne une adresse proposée par la BAN dans le dropdown, le cas échéant
- soit le formulaire permet (et oblige ?) la saisie de l'adresse de façon détaillé (rue, complément, code postal, ville)

**Comment by yaf** [comment]
Merci beaucoup !

```
irb(main):008:0> User.where(city_name: [nil, ""]).where.not(address: [nil, ""]).count
=> 113837
```
Ça fait beaucoup pour une correction à la main.

Il existe un script qui avait servi à initialiser ces champs à leur création https://github.com/betagouv/rdv-solidarites.fr/blob/production/scripts/update_city_name_postal_code_and_city_code_from_address.rb Peut-être que nous pourrions faire tourner ce script chaque nuit pour rattraper ce qui pourrait l'être ?

Je viens de faire un essai, ça ne change rien aux données de prod de passer ce script. Les adresses saisies ne sont pas dans la BAN (soit parce qu'elles sont malformées, soit parce qu'elles ne sont pas présentes dans la BAN).

Je ferme ce ticket, nous ne pouvons pas faire grand-chose ici. J'ai en tête (depuis quelque temps) de faire une analyse de notre utilisation de la BAN et de trouver une autre stratégie pour notre gestion des adresses... Cela nous permettra sans doute de résoudre ce problème.
