### ISSUE TITLE
Accès partenaire

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2469]
## Actuellement

Plusieurs départements (mais pas que ?) travail avec des partenaires. Ce ne sont ni des usagers, ni des agents ou professionnelles qui seront d'un côté ou de l'autre du RDV, mais souvent des personnes qui souhaite pouvoir poser des RDV avec des agents / professionnel pour des usagers. 

## Objectif

_Nécessite un peu de précision de la part des personnes demandant ces accès_

Nous pouvons imaginer déjà le fait de pouvoir prendre un RDV pour un usager avec un agent sans être ni l'un ni l'autre. Ça ressemble au profil secrétariat, mais peut-être avec des accès différents.

Est-ce que les « nouveaux » droits d'accès seront suffisants pour ce type de profil ?

**Comment by victormours** [comment]
C'est très similaire à la notion de secrétariat qui est utilisée pour répondre à ce besoin côté cnfs. On a un besoin similaire aussi dans le cadre du travail sur la cartographie avec Rés'in.

**Comment by yaf** [comment]
Je crois que les nouveaux droits d'accès permettront d'avoir des profils de ce genre...

**Comment by victormours** [comment]
Ce ticket est géré par la mise en place des prescripteurs https://github.com/betagouv/rdv-solidarites.fr/issues/3033 (avec éventuellement les améliorations en cours our le Var et d'autres publics)
