### ISSUE TITLE
RDV annulé puis réinitialisé : usage⋅re non notifié⋅e

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#2538]
## Actuellement

* Comportement actuel : Lorsque l'on réinitialise le statut d'un RDV, aucune notification n'est envoyée. Cela signifie que si un RDV est annulé, puis réinitialisé (si l'agent réalise que l'annulation était une erreur), **aucune notif n'est envoyé pour indiquer que le RDV n'est plus annulé**.
* Étapes pour reproduire cette situation : Créer un RDV, puis l'annuler, puis le réinitialiser. Consulter ensuite la section "Notifications envoyées" : aucune notif n'a été envoyée suite à la réinitialisation. (voir captures d'écran ci-dessous)

## Objectif

* Comportement attendu : envoyer une notification pour indiquer que le RDV a été réinitialisé (formulation à réfléchir)
* Options envisagées, le cas échéant : empêcher de réinitialiser un RDV annulé, et donc forcer à le recréer

## Pourquoi

La confiance en les notifications est un sujet clé de RDV-S, et l'expérience utilisateur qui consiste à recevoir seulement un SMS d'annulation pour un RDV qui a toujours lieu est inacceptable.

Le 31 mai 2022, nous avons reçu un e-mail d'une référente indiquant :

> Bonjour,
> Je suis alertée ce jour par une famille qui a reçu un SMS d’annulation pour un RDV prévu ce mercredi avec moi. Le RDV n’est pas annulé et n’a fait l’objet d’aucune modification de la part de notre service. Nous ne comprenons pas pourquoi la famille  a reçu un SMS en ce sens et espérons que ce n’est pas le cas pour d’autres familles.
> Cordialement,

Suite à une investigation, il se trouve que nous avons trouvé des RDVs qui avait été annulés puis réinitialisés., et qui pourraient correspondre à cette demande (pour laquelle nous avons demandé un ID de RDV, sans réponse pour l'instant).

## Captures d'écran pour reproduire

![image](https://user-images.githubusercontent.com/6357692/171429755-bb325154-8c18-4191-a92c-2d2b1552646d.png)
![image](https://user-images.githubusercontent.com/6357692/171429774-18e3d64c-6063-43e2-a1d8-80eefbcc6086.png)
![image](https://user-images.githubusercontent.com/6357692/171429780-79d13a56-2de2-4fe4-9210-fbd29e7a3fd1.png)

**Comment by victormours** [comment]
Myriam a retrouvé le rdv qui posait problème c'est https://www.rdv-solidarites.fr/admin/organisations/152/rdvs/763109?agent_id=429 (cc @francois-ferrandis )

**Comment by francois-ferrandis** [comment]
> Myriam a retrouvé le rdv qui posait problème c'est https://www.rdv-solidarites.fr/admin/organisations/152/rdvs/763109?agent_id=429 (cc @francois-ferrandis )

Ce RDV est un vendredi alors que la demande d'origine parlait d'un vendredi.

Je laisse [ici le ticket Zammad de la demande](https://zammad10.ethibox.fr/#ticket/zoom/424), su lequel on peut parler de l'incident reporté, et ainsi garder ce ticket pour parler conception produit. :wink:

**Comment by yaf** [comment]
J'ai l'impression que l'option qui consiste à ne pas pouvoir réinitialiser un RDV annulé (à l'initiative de l'usager ou du service) serait une bonne option. Un peu cache, mais après tout, il y a un popup de confirmation (qui ne doit même plus être lu)....

Ça me semble une démarche « pédagogique » intéressante.

**Comment by francois-ferrandis** [comment]
> J'ai l'impression que l'option qui consiste à ne pas pouvoir réinitialiser un RDV annulé (à l'initiative de l'usager ou du service) serait une bonne option. Un peu cache, mais après tout, il y a un popup de confirmation (qui ne doit même plus être lu)....
> 
> Ça me semble une démarche « pédagogique » intéressante.

Le gros avantage de cette solution à mes yeux c'est qu'on réduit la complexité, et notamment auprès des usager⋅es, à qui on a pas à expliquer "votre RDV a été réinitialisé, donc en fait il n'est plus annulé, à moins qu'il soit annulé à nouveau". :hand_over_mouth:

**Comment by victormours** [comment]
Aujourd'hui, on a la possibilité de rétablir un rdv annulé. Il y a des specs qui vérifient ce comportement, donc ça n'a pas été ajouté par hasard.
Plus important, c'est une fonctionnalité utilisée : depuis le 1er juin, on a eu 3206 changements d'états de rdv pour revenir d'une annulation (source : `select count(*) from versions where item_type = 'Rdv' and event = 'update' and object_changes ilike '%status:_- excused_-%' or object_changes ilike '%status:_- revoked_-%' and created_at >  '2022-06-01';`

Qualitativement, c'est aussi quelque chose qu'on retrouve dans les discussions avec les agents : parfois ils font une fausse manip', et ils annulent par erreur. C'est des choses qui arrivent, et c'est pas la peine de les punir pour ça.

Il y a une implémentation simple qui consisterait à renvoyer les notifications de confirmation en se branchant dans le `RdvUpdater` ligne 29. Ça ne rajoute pas plus de complexité que d'interdire ce changement, et ça permet de ne pas supprimer une fonctionnalité qui rend service aux agents.

**Comment by yaf** [comment]
Merci pour cette analyse.

Un des problèmes, c'est la compréhension coté usager. 
- je reçois une notif qui dit RDV
- je reçois une annulation du dit RDV
- je reçois ??? une re-ouverture du RDV finalement ?

Peut-être faut-il traiter le problème de « pourquoi » on se retrouve à utiliser cette possibilité de « re-initialiser » ? Souvent, parce qu'on se trompe je suppose. Alors c'est que le mécanisme n'est pas bon.

Je suis ok pour dire que la solution #2613 est un peu « punitive » telle quelle.

Plutôt que de bloquer pour le moment, et plutôt que de remettre en place les notifications (qui me semble tordu), nous pourrions prendre un objectif de « réduire » l'utilisation de ce bouton et explorer des pistes pour aider ça ? 

Il y a une exploration à faire. C'est sans doute le moment de faire appel à Myriam et Nesserine pour questionner les agents.

**Comment by victormours** [comment]
Pour une analyse quantitative, c'est intéressant de regarder le temps écoulé entre la dernière modification sur l'état et la correction : sur juin dernier, c'est moins d'une minute dans environ un tiers des cas, moins de 5mn pour environ la moitié des cas.

Ça ouvre la porte à une réduction simple du nombre de notifications erronées : on peut programmer le job de notification pour qu'il soit envoyé avec une minute de délai (ou un peu plus), et n'envoyer la notification que si le rdv est toujours dans un état annulé.

Autrement dit, on aurait le fonctionnement suivant :
- Un agent marque le rdv comme annulé par erreur
- Le job de notification est programmé pour une minute plus tard
- L'agent se rend compte de son erreur quelques secondes plus tard, et corrige l'état du rdv
- Le job est lancé, voit que le rdv n'est plus annulé, et n'envoie pas de notification.

Comme ça, plutôt que d'envoyer des notifications par erreur, on n'en envoie pas du tout.

L'inconvénient est qu'on introduirait une latence sur toutes les notifications d'annulation, donc il faut voir en fonction des chiffres combien de latence on se permet.

Le sql pour le temps écoulé (il y aurait des implémentations plus élégantes, mais ça donne une idée) :
```SQL
select distinct (versions.created_at - prev_ver.created_at) from versions
join versions as prev_ver
  on (
    (prev_ver.object_changes ilike '%status:%excused%' and versions.object_changes ilike '%status:_- excused_-%' )
    or 
    (prev_ver.object_changes ilike '%status:%revoked%' and versions.object_changes ilike '%status:_- revoked_-%')
  ) and prev_ver.id != versions.id and versions.created_at > prev_ver.created_at
where
  versions.item_type = 'Rdv' and versions.event = 'update'
  and versions.created_at >  '2022-06-01'
  and prev_ver.item_id = versions.item_id and prev_ver.item_type = 'Rdv'
;
```

**Comment by yaf** [comment]
Est-ce que la solution qui couvre les différents cas ne serais pas un truc intermédiaire comme 

- mettre en place ce délai d'envoi de notification d'annulation (5 à 10 minutes ?)
- ajouter un message d'information au moment de la réinitialisation d'un statut de RDV futur pour prévenir que l'usager ne sera pas notifié (dans le popup de confirmation de réinitialisation)

![Capture d’écran de 2022-07-11 10-16-17](https://user-images.githubusercontent.com/42057/178219660-0bd4da75-1cb2-4b1c-9065-29760c47a4af.png)

**Comment by yaf** [comment]
(pour documenter un peu plus le point d'au-dessus, nous avons un système qui permet d'envoyer une notification « manuelle » déjà en place : 


![Screenshot 2022-07-11 at 10-17-36 Votre agendaRDV Joséphine DUROY 🏠 - RDV Solidarités](https://user-images.githubusercontent.com/42057/178219947-0e1c89e0-8123-4c10-963c-6c2c8b7bf039.png)

**Comment by victormours** [comment]
Pourquoi est-ce qu'on est en train de partir sur une tangente avec des nouvelles solutions ? Mettre un message pour dire que l'usager n'est pas notifier ça ne répond pas au problème.
Le plus simple reste d'envoyer un mail pour expliquer la situation. J'ai l'impression qu'on ne s'est pas décidé à faire ça parce qu'on ne trouvait pas comment le formuler. Voici une proposition :

sujet : Votre rdv du 17/07 est maintenu
Vous avez reçu une notification indiquant que votre rendez-vous du 17/07 avait été annulé, mais il est finalement maintenu.
**Votre rendez-vous du 17/07 aura donc bien lieu à 14h à la médiathèque Sonia Delaunay.**

Pour la question meta : on garde les infos ici : elles sont publiques et faciles à retrouver par la suite.

**Comment by yaf** [comment]
Après en avoir parlé, nous allons reprendre la PR pour faire des notifications de « création » au moment où un RDV est réinitialisé.

**Comment by francois-ferrandis** [comment]
Merci beaucoup d'avoir eu cette discussion ici, de mon point de vue c'était la meilleure chose à faire pour partager l'information au sein de l'équipe et historisé la décision.
