### ISSUE TITLE
Supprimer un RDV dont la notification d'annulation est bien partie

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2543]
## Actuellement

Nous ne pouvons pas supprimer un RDV qui a été notifié. Même si nous l'avons annulé.

## Objectif

Il est logique de bloquer la suppression d'un RDV qui a été notifié à un usager. Mais une fois l'annulation notifiée, nous pourrions autoriser à nouveau la suppression.

Et plutôt que de dire que ce n'est pas possible, nous pourrions peut-être ne pas afficher le bouton ?

**Comment by yaf** [comment]
On pourrait aussi envisager un « soft delete »

**Comment by yaf** [comment]
Dans un premier temps, j'envisage de faire en sorte que l'on supprime un RDV (et ses `receipts`) si
- il n'y a pas eu de notification 
- ou la dernière notification est une annulation

**Comment by victormours** [comment]
Pour avoir un meilleur historique des décisions produit, ça serait chouette que les raisons pour lesquelles les référentes veulent des suppressions soient documentées dans le ticket. Jusque là on pensait que l'option annuler le rdv et cacher les rdv annulés dans le calendrier suffisaient.

Je crois qu'on s'était dit qu'il valait mieux ne pas supprimer les rdv pour lesquels une notification était envoyée parce qu'on voulait éviter que les usagers n'arrivent sur une page 404 (mais je suis pas sûr). Est-ce que si on explique sur cette page que le rdv a (probablement) été annulé puis supprimé ça devient acceptable de faire ça ?
Est-ce que c'était aussi parce qu'on voulait éviter de supprimer les receipts ?

En tout cas, l'option de supprimer le rdv (et ses receipts) s'il a été annulé ou s'il n'a pas de receipt me semble bien. 👍 
On pourrait vouloir garder les receipts pour faire des stats, mais je pense que le volume de rdv supprimés sera suffisamment faible pour ne pas trop les fausser.

**Comment by yaf** [comment]
Tu as tout as fait raison. Et j'ai quelques histoires à partager, mais je crois que ça serait intéressant de faire une « vraie » enquête.

Mon hypothèse, et je (avec l'aide de Myriam peut-être ?) vais faire le tour des référentes pour leur vérifier, c'est qu'aujourd'hui, pour supprimer un agent, un lieu, ou un usager (ou autre élément lié à un RDV), il ne faut pas qu'il soit lié à un RDV...

Une piste pour éviter d'avoir à faire ce genre de chose serait de « dénormaliser » le RDV pour qu'une fois créé, il ne soit plus lié aux structures ayant permis de le créer. Je crois que c'est une bonne piste d'architecture pour la généralisation. Nous pourrions prendre un moment pour en parler sans doute.

Je vais faire l'enquête auprès des référentes avant de finaliser la PR. Merci !

**Comment by yaf** [comment]
Création d'un ticket pour proposé de ne pas vraiment supprimer les RDV

#2691

**Comment by yaf** [comment]
Le pad de travail autour des cas d'usages remonté par les référentes

https://pad.incubateur.net/-xZrQQ8FSum1veWgq3QJ_A#

La première réponse pencherait bien pour 
- autoriser la suppression à tout moment
- ne pas vraiment supprimer les RDV (#2691

**Comment by yaf** [comment]
réglé par l'installation du #2801
