### ISSUE TITLE
Crash lors de la recherche de créneau : "PG::DataException: range lower bound must..."

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#2547]
# Edit du 29 juin 2022

Je suis parvenu à reproduire avec les seeds de base en faisant "Trouver un RDV" puis en saisissant une date dans le passé, ce qui nous amène ici : 
http://localhost:3000/admin/organisations/1/agent_searches?service_id=&motif_id=2&from_date=15%2F06%2F2022&agent_ids%5B%5D=&lieu_ids%5B%5D=&commit=Afficher+les+cr%C3%A9neaux

Comme @yaf le suspectait, il y a bien un bug dans `#ensure_date_range_with_time` depuis #2504 (coucou @aminedhobb). :wink: 

Note : il semblerait que ce crash ait aussi lieu côté user (voir [cette occurrence](https://sentry.io/organizations/rdv-solidarites/issues/3270502722/events/1d6a7190340c4bf6b82ba44ff62187a7) par exemple).

# Ticket original

Parfois lorsqu'un⋅e usagè⋅re recherche un créneau (`Users::RdvsController#index`), nous avons l'erreur suivante :

> PG::DataException: ERROR: range lower bound must be less than or equal to range upper bound

Ce crash se produit moins d'une dizaine de fois pas jour :
https://sentry.io/organizations/rdv-solidarites/issues/3268291575

**Comment by yaf** [comment]
Voir `app/lib/lapin/range.rb` sans doute.

**Comment by francois-ferrandis** [comment]
Je suis parvenu à reproduire avec les seeds de base en faisant "Trouver un RDV" puis en saisissant une date dans le passé, ce qui nous amène ici : 
http://localhost:3000/admin/organisations/1/agent_searches?service_id=&motif_id=2&from_date=15%2F06%2F2022&agent_ids%5B%5D=&lieu_ids%5B%5D=&commit=Afficher+les+cr%C3%A9neaux

Comme @yaf le suspectait, il y a bien un bug dans `#ensure_date_range_with_time` depuis #2504 (coucou @aminedhobb). :wink:

**Comment by aminedhobb** [comment]
L'erreur semble indiquer que la borne inférieure est postérieure à la borne supérieur, je suis pas sûr que ça vienne de #2504 qui consistait à restreindre les cas où on arrondissait la borne inférieur en début de journée.

À vue de nez je dirais que le problème se pose [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/4bb223234acb4a688c4c214be378e59bbaaaa92a/app/lib/lapin/range.rb#L16). Si on cherche dans un intervalle dans le passé, on ne changerait que la borne inférieur et ça risque de donner cette erreur.

Mais dans quels cas aurait-on besoin de chercher des intervalles dans le passé 🤔  ?

Je n'ai pas plus investigué donc il est tout à fait possible que ça ne soit pas du tout ça :). Malheureusement je pars en vacances demain soir donc j'aurais pas le temps d'en savoir + avant mon retour 😬 !

**Comment by yaf** [comment]
Ça serait pertinent de bloquer la recherche dans le passé il me semble.

**Comment by francois-ferrandis** [comment]
> L'erreur semble indiquer que la borne inférieure est postérieure à la borne supérieur, je suis pas sûr que ça vienne de #2504 qui consistait à restreindre les cas où on arrondissait la borne inférieur en début de journée.

Ah mais oui, pardon @aminedhobb, l'erreur date du 12 mai alors que cette PR a été mergée le 30 mai, désolé pour la conclusion hâtive et légèrement accusatoire ! :pray:

**Comment by aminedhobb** [comment]
Haha non pas de soucis :), désolé de ne pas pouvoir investiguer + loin !

**Comment by yaf** [comment]
Il se peut que ce soit quand même lié à cette zone de code qui n'était pas super fiable justement avant les divers patchs :)

Si le problème n'est pas apparu depuis, c'est sans doute que cela a été corrigé justement.

**Comment by francois-ferrandis** [comment]
> Si le problème n'est pas apparu depuis, c'est sans doute que cela a été corrigé justement.

Visiblement le crash continue d'avoir lieu presque chaque jour, et il a été rencontré par 141 personnes différentes (je vois des agents **et** des users, je vais l'indiquer dans la description de ce ticket).
