### ISSUE TITLE
Avertir lorsqu'un motif à une durée par défaut qui dépasse celle proposée dans la plage d'ouverture

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2565]
## Actuellement

Je peux poser une plage d'ouverture sur une durée inférieure à celle par défaut annoncé dans les motifs.

## Objectif

Avoir un avertissement ou quelque chose permettant de se rendre compte qu'un truc cloche.

**Comment by damienlethiec** [comment]
Je confirme que le problème semble toujours là.

Proposition: l'ajouter aux avertissements présentés en cas de conflits entre plage d'ouverture --> 
![image](https://user-images.githubusercontent.com/8105430/190451928-8a5029e3-c20c-4aee-a17d-e61aa9d597a6.png)

**Comment by yaf** [comment]
Ça me semble une très bonne idée, dans l'esprit de ce qu'il y a aujourd'hui
