### ISSUE TITLE
Appels de FullCalendar en échec

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#2567]
Issue Sentry correspondante : https://sentry.io/organizations/rdv-solidarites/issues/3294462748

## Actuellement

* Comportement actuel : certains appels Ajax faits par FullCalendar échouent, on a alors une remontée sur Sentry et une fenêtre d'alerte qui s'affiche (voir capture d'écran ci-dessous)
* Étapes pour reproduire cette situation : nous ne connaissons pas la cause de ces échecs

<img src="https://user-images.githubusercontent.com/6357692/172901649-16657658-1ef7-4c6e-b803-93fe47c06503.png" width="400">

**Détail important : sur la vue agenda des agents, toutes les données sont rechargées [par polling toutes les 30 secondes](https://github.com/betagouv/rdv-solidarites.fr/blob/e9803eb80dcafbec0c9fbd1dc72eb493d1d13383/app/javascript/components/calendar.js#L47) (RDVs, absences, plages d'ouverture, jours fériés).**

**Les agents ont pour pratique de garder leur agenda ouvert, et donc de faire 8 appels par minute à l'appli.**
  
Il faut noter que ces erreurs surviennent de façon homogène sur l'ensemble de la journée de travail, et donc ne sauraient être attribués à des couacs de déploiement : 

<img src="https://user-images.githubusercontent.com/6357692/172901885-31f60a49-b364-42cc-93d0-fb07f7af72cf.png" width="400">

## Objectif

* Comportement attendu : faire en sorte que la boite d'alerte ne vienne plus gêner un agent qui laisse sa fenêtre ouverte en permanence et rencontre une pauvre erreur Ajax isolée
* Options envisagées, le cas échéant : 
  1. diagnostiquer la source des erreurs et la corriger (ça semble difficile)
  2. avoir une gestion d'erreur plus souple côté JS : tolérer qu'un appel puisse être en erreur si le précédent était un succès, ou alors retry immédiatement en cas d'erreur

On remarque dans les logs Sentry que les erreurs ne semblent pas survenir deux fois de suite pour le même agent :

<img src="https://user-images.githubusercontent.com/6357692/172903046-4f85e57b-3b18-4cdf-9ff7-7f80b6b49464.png" width="300">

La solution 2 semble donc la plus pragmatique.

**Comment by yaf** [comment]
Il serait peut-être intéressant d'étudier la possibilité de ne pas faire de polling sur l'agenda... Est-ce qu'ouvrir une websocket serait pertinent ? Est-ce que niveau écoconception cela serait correct ? Compatible avec des navigateurs un peu anciens ?
