### ISSUE TITLE
afficher un message d'erreur lorsque l'on tente d'inviter un agent éxistant dans un autre service

### ISSUE THREAD

**Issue by NFontelle** [betagouv/rdv-solidarites.fr#2570]
###### Comportement actuel
un message d'erreur apparait quand un agent essaye d'inviter un agent dans un service si ce dernier appartient déjà à un autre service
cf erreur sentry : https://sentry.io/organizations/rdv-solidarites/issues/3268459491.

######  Étapes pour reproduire cette situation
nous ne sommes pas parvenu à reproduire l'erreur en local. 
lien zammad : https://zammad10.ethibox.fr/#ticket/zoom/1875

######  Captures d'écran si pertinent

configuration, invitation d'un nouvel agent :
![image](https://user-images.githubusercontent.com/60173782/173364889-e46ea9fe-80d5-41ae-a5b8-6f274c6c3677.png)

######  Comportement attendu
mettre un message d'erreur comprehensible par les utilisateurs

######  Options envisagées, le cas échéant
permettre la modification du service ?

**Comment by yaf** [comment]
La modification de service, ce n'est pas au programme tant que nous n'avons pas fini de déplacer tout ce qui concerne les autorisations sur le nouveau système.

Lorsque les droits d'accès seront définis par de vraies autorisations, et non par l'appartenance à un service et une organisation, nous pourrons envisager le changement de service !

**Comment by yaf** [comment]
Alors, le ticket sentry pointé ici n'a rien à avoir avec l'invitation d'agent. 

Le ticket Sentry évoque une erreur liée à une tentative de modification d'un prénom alors que l'usager, c'est connecté avec FranceConnect, et il ne peut donc plus changer ces informations-là depuis RDv-Solidarités.

C'est lié au processus de fusion et donc à un des tickets #2391 ou #1763 


Pour le ticket Zammad, j'ai l'impression que c'est un autre souci, lié au fait que pour le moment il est impossible de changer de service et que Sophie a fini par résoudre son problème si c'est bien compris. Je ferme ce ticket alors.
