### ISSUE TITLE
bug liste déroulante des lieux dans la recherche d'un RDV

### ISSUE THREAD

**Issue by NFontelle** [betagouv/rdv-solidarites.fr#2576]
## Actuellement

la liste déroulante n'est pas triée par ordre alphabétique, contiendrait plusieurs fois un même lieu et contient des lieux fermés.
https://zammad10.ethibox.fr/#ticket/zoom/1879

**Comment by yaf** [comment]
Attention, ce n'est peut-être pas dans tous les écrans. Le signalement est sur le filtre de la liste des RDV.

Merci pour ce ticket :bow:
