### ISSUE TITLE
Ne pas modifier un RDV pour y placer un agent qui n'a pas accès au motif du RDV

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2650]
## Actuellement

Un usager à un RDV avec un agent ;
Le motif du RDV est associé au service de l'agent ;
En tant qu'admin (ou secrétaire) je peux modifier l'agent dans un RDV et mettre un agent qui n'accède pas à ce motif (pas du même service).

## Objectif

Ne pas autoriser un agent à « faire » un RDV sur un motif auquel il n'a pas accès (pour le moment, c'est lié au service)

**Comment by simkim** [comment]
Bonjour @yaf, puis je travailler sur cette issue bénévolement ?

**Comment by simkim** [comment]
Je comprends qu'on peut rajouter une validation pour vérifier que les agents ont accès au motif puis s'assurer que la liste des agents ne contient que ceux ayant accès au motif.

**Comment by simkim** [comment]
Je comprends qu'on pourrait aussi en faire éventuellement une erreur benine pour pouvoir outrepasser en cas de besoin. Ce qui produirait du code différent.

**Comment by simkim** [comment]
Il semblerait que les tests créent pour le moment des rdv avec un motif et des agents provenant de service différents, beaucoup à reprendre. Il serait utile d'en discuter.

**Comment by simkim** [comment]
Cela fait changer beaucoup de tests, j'aimerai en parler avec vous avant de changer de nombreux let

**Comment by simkim** [comment]
@yaf 
J'ai modifié la factory rdv pour mettre :

```
    motif { build(:motif, organisation: organisation) }
    users { [build(:user, organisations: [organisation])] }
    agents { [build(:agent, service: motif.service, organisations: [organisation])] }
```

Ce qui fonctionne poru les cas par défaut et ou l'on customise le motif mais pas pour le cas où l'on customise l'agent.

Je peux expliciter la création du motif aussi dans un test pour créer l'agent du test avec le service du motif. Cela convient à la recommandation d'être explicite et proche mais modifie beaucoup de test et les compliquent avec une ligne en plus. Comme dans ([spec/presenters/rdv_ending_shortly_before_presenter_spec.rb](https://github.com/betagouv/rdv-solidarites.fr/pull/2680/files#diff-4ea42e52148c58e4423d95431184337b9984717fa8c97ae6c162353ef199947a))

Avant de le faire j'aurai besoin d'un go ou d'une autre recommandation.

**Comment by yaf** [comment]
Nous pouvons peut-être prendre un temps de discussion semaine prochaine ? Je peux me rendre dispo mardi matin jusqu'à 14 h

**Comment by simkim** [comment]
Ce serait utile. Quand tu veux mardi

**Comment by simkim** [comment]
Je me dit que si on mettait un service par défaut dans la factory d'une organization on pourrait aussi remonter ce service par défaut sur l'agent / motif / rdv

**Comment by simkim** [comment]
Merci. Revenu de vacances cette semaine. Je m'en occupe

**Comment by yaf** [comment]
Finalement, nous partons sur l'ouverture... Donc je referme cette PR
