### ISSUE TITLE
Disparition du contenu de la page d'accueil

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#2665]
## Avant 

Sur la page d'accueil, on avait des explications sur l'appli dans les sections "Comment ça marche" et "Vous êtes un agent"

Elles ont disparu suite à cette PR : https://github.com/betagouv/rdv-solidarites.fr/pull/2617
Ces explications étaient utiles pour les usagers, et pour les agents.

## Objectif

Remettre le contenu sur la page d'accueil

**Comment by yaf** [comment]
Les pages sont supprimées dans #2661

**Comment by yaf** [comment]
Pour info, il faut également modifier les infos qui étaient affichées au vu du changement fait puisque nous n'avons plus besoin de choisir un service.
Je vais essayer de reprendre les images.
