### ISSUE TITLE
Ne pas vraiment supprimer les RDV (aka `soft_delete`)

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2691]
Recueil des besoins : https://pad.incubateur.net/-xZrQQ8FSum1veWgq3QJ_A
Pistes techniques : https://pad.incubateur.net/bFjCtq9GQKWZLjHcN8n6qg#
Discussions autour de la solution au problème : https://pad.incubateur.net/TqoO5pbtQdqTKH7t7SBaQw#

## Actuellement

Un RDV peut être complétement supprimé.

## Objectif

Faire en sorte que la suppression au bout des 2 années soit réelle, mais faire en sorte que les suppressions demandées depuis l'interface graphique par des agents admin ne soit en fait qu'un `soft_delete` comme pour les agents, les usagers et les motifs.

Deux pistes possibles 

- S'inspirer de ce qu'il y a déjà en place dans les motifs, les agents et les usagers en ajoutant un champ `deleted_at`
L'inconvénient c'est de devoir reprendre toutes les requêtes de RDV pour exclure les RDV supprimer...

- Déplacer le RDV supprimé dans une autre table.

Cette dernière option est plus simple, car elle ne nécessite pas de modifier TOUTES les requêtes sur les RDV (pour exclure les RDV supprimés).
Mais ça pose peut-être des problèmes pour les tables de jointure et autres (RdvsUser, AgentsRdv, ParperTrail::Version, FileAttente, Receipt).

**Comment by NFontelle** [comment]
pad associé : https://pad.incubateur.net/-xZrQQ8FSum1veWgq3QJ_A

**Comment by NFontelle** [comment]
Routes d'accès aux Rdvs :
https://pad.incubateur.net/bFjCtq9GQKWZLjHcN8n6qg

**Comment by aminedhobb** [comment]
Je veux bien être tenu au courant lorsqu'il y aura des avancées sur ce sujet svp, côté RDV-I on a une logique spécifique à la destruction du record et le webhook envoyé suite à cet event, du coup si cette logique change il faudra qu'on s'adapte aussi :).
