### ISSUE TITLE
Expliquer pourquoi la page de création de RDV Collectif est vide

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2708]
## Actuellement

Lorsque l'on souhaite créer un RDV Collectif ;
S'il n'y a pas de motif collectif ;
La page est vide, sans aucune indication pour aller créer un motif collectif.

![Screenshot 2022-08-09 at 11-45-19 Nouveau RDV Collectif - RDV Solidarités](https://user-images.githubusercontent.com/42057/183618662-cf3c0596-d50c-4a23-ab38-f5473dc06afb.png)

## Objectif

Lorsque la personne est admin : avoir un texte et un lien pour inviter à créer un motif Collectif ;
Lorsque la personne n'est pas admin : avoir un texte explicatif ;

**Comment by sebastiencarceles** [comment]
Pour une personne qui n'est pas admin ici, quel pourrait être le texte explicatif ? Un truc du genre "Demandez à un·e agent·e admin de créer un motif collectif" ? Quel vocabulaire faudrait-il utiliser pour rester homogène avec le reste de l'application ?

**Comment by yaf** [comment]
C'est une très bonne question. Il y a dans certains départements la notion de coordinateur et coordinatrice sur certains sites. Mais ce n'est pas une pratique généralisée, il me semble. Admin est peut-être assez parlant :shrug: ? Administrateur sera peut-être mieux. Voir un truc du genre « ... avec une personne ayant les droits d'accès ».

Nous ne communiquons pas assez avec l'utilisateur dans notre application. Nous le faisons un peu par-ci et un peu par là, mais nous n'avons pas encore mis en place une « cohérence » de l'ensemble.
