### ISSUE TITLE
Ignorer les erreurs de connexions au webhook de la Drôme

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2722]
## Actuellement

Ref : https://sentry.io/organizations/rdv-solidarites/issues/3183773178/?project=1811205&query=is%3Aunresolved+sdk.name%3Asentry.ruby.rails&sort=date&statsPeriod=14d

Nous recevons beaucoup d'erreur lors de l'utilisation du webhook pour la Drôme.
En ce moment, le code de retour est 401 et le message "Zimbra admin authentication failed".

## Objectif

Ignorer ces erreurs pour le moment. Il y a une série d'erreurs que nous ignorons déjà dans https://github.com/betagouv/rdv-solidarites.fr/blob/production/app/jobs/webhook_job.rb#L47

**Comment by yaf** [comment]
Nous pourrions faire évoluer l'interface des webhook pour y remonter les erreurs...

Ce n'est pas une priorité pour le moment, mais peut-être plus tard.

**Comment by damienlethiec** [comment]
Est-ce que je rescue tout quand ça vient de la drome @yaf ou tu as une liste précise des erreurs à rescue ? En ce moment il y a pas mal de 500 : `Can't create appointment.` par ex.

Merci :)

**Comment by yaf** [comment]
Une part de moi dirait bien de toute rescue si ça vient de la Drôme effectivement... Mais ça nous empêcherait de voir les vraies erreurs :thinking: 

Si tu peux identifier clairement certaines erreurs (comme `Can't create appointment` avec lesquelles nous ne pouvons de toute façon pas faire grand-chose, ça serait sans doute bien mieux. Il y a déjà des cas pris en charge normalement, il faut étoffer cette partie...

voir https://github.com/betagouv/rdv-solidarites.fr/blob/production/app/jobs/webhook_job.rb#L47

**Comment by damienlethiec** [comment]
> Une part de moi dirait bien de toute rescue si ça vient de la Drôme effectivement... Mais ça nous empêcherait de voir les vraies erreurs 🤔
> 
> Si tu peux identifier clairement certaines erreurs (comme `Can't create appointment`) avec lesquelles nous ne pouvons de toute façon pas faire grand-chose, ça serait sans doute bien mieux. Il y a déjà des cas pris en charge normalement, il faut étoffer cette partie...
> 
> Voir https://github.com/betagouv/rdv-solidarites.fr/blob/production/app/jobs/webhook_job.rb#L47

Merci :) J'avais bien vu les cas pris en charge. Je rajoute tous ceux que je croise sans la connaissance métier de ceux qui peuvent être de vraies erreurs sur lesquelles on peut faire quelque chose. Je vous laisserai confirmer ça à la review pour potentiellement ne pas rescue certains cas
