### ISSUE TITLE
Ne pas réessayer d'envoyer un SMS quand le numéro est invalide

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#2748]
## Actuellement

* Comportement actuel : lorsque le fournisseur d'envoi de SMS nous renvoie une erreur, on réessaye d'envoyer le SMS un peu plus tard. **Nous essayer d'envoyer le SMS 25 fois, la 25ème fois ayant lieu 20 jours après la première fois ([source](https://github.com/collectiveidea/delayed_job#gory-details)).**
* Étapes pour reproduire cette situation : on peut voir les jobs en échec ici : https://www.rdv-solidarites.fr/super_admins/delayed_job/failed?queues=sms

## Objectif

* Comportement attendu : ne pas réessayer l'envoi si le fournisseur nous indique que le numéro est mauvais. Par exemple, quand netsize nous renvoie une erreur `"Could not route message"`, on pourrait la rescue afin d'éviter que le job soit remis à la queue. Pour info, le receipt est alors tout de même créé, ce qui permet d'afficher sur la page RDV de l'agent que l'envoi du SMS a échoué.
* Options envisagées, le cas échéant : Nous pourrions envisager d'également envoyer un mail à l'agent pour lui signaler que le numéro n'est pas le bon. Note : une issue similaire est déjà présente côté e-mails : #2639

## Pourquoi

Les retries inutiles constitue une forme de bruit dans Sentry et dans l'interface `delayed_job`, ce qui noie potentiellement des erreurs importantes. 

Côté coût financier, il est possible qu'un envoi en échec soit tout de même facturé, et donc ce n'est pas la peine de payer 25 SMS au lieu de 1. :wink: 

## Technique

Doc netsize : https://linkmobility.it/wp-content/uploads/sites/11/2020/09/Netsize-Implementation-Guide-REST-API-1.pdf

**Comment by yaf** [comment]
Lié à #1753
