### ISSUE TITLE
Anomalie rdv à renseigner

### ISSUE THREAD

**Issue by NFontelle** [betagouv/rdv-solidarites.fr#2756]
https://zammad10.ethibox.fr/#ticket/zoom/2534

Bug remonté par le Pas-de-calais :

" le bandeau des rdv à renseigner (cf capture), il est annoncé un rdv à renseigner lorsque la liste des RDV affiche « aucun RDV »."

![image](https://user-images.githubusercontent.com/60173782/187646975-f5487cfc-20a3-4a1f-8546-b27053805436.png)

**Comment by yaf** [comment]
Le problème a l'air résolu maintenant. Il y a eu un petit décalage entre l'opération de changement de statuts et le recalcule du bandeau peut-être ?

@NFontelle attention à éviter de mettre des captures d'écran de la prod dans les tickets. Ici ça va, il n'y a pas de données sensibles, mais c'est public ici, tout le monde à le droit de voir :)
