### ISSUE TITLE
Permettre la création de plages d'ouverture sans lieu 

### ISSUE THREAD

**Issue by guillett** [betagouv/rdv-solidarites.fr#2770]
## Actuellement

* Comportement actuel

Aujourd'hui on ne peux pas créer de plage d'ouverture sans lieu. Pour des RDV téléphoniques cela devrait être possible.

* Étapes pour reproduire cette situation

* Captures d'écran si pertinent

![Capture d’écran 2022-09-01 à 17 08 52](https://user-images.githubusercontent.com/1410356/188123388-1a7aa2f5-47e0-49ae-8cec-0be847537495.png)

## Objectif

* Comportement attendu
Pouvoir créer une plage d'ouverture sans lieu.

* Options envisagées, le cas échéant

**Comment by sebastiencarceles** [comment]
Note : c'est possible aussi pour les motifs **à domicile**, cf #2860
