### ISSUE TITLE
Environnement de dev : Bug avec la variable d'environnement "SENTRY_DSN_RAILS"

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#2783]
## Actuellement

En mettant en place mon environnement de développement sur ma machine j'ai eu l'erreur suivante :

![Sentry_bug](https://user-images.githubusercontent.com/28594222/188584609-16858dbf-960b-47e0-9db4-9c5cb186465c.jpg)

Cette erreur provoquait des bugs avec certaines library JS dans mon environnement de dev (Select2 ou le Geocoding de la home par exemple)
J'ai résolu le problème en supprimant la valeur 'change_me' de la variable d'environnement SENTRY_DSN_RAILS et en la laissant vide.

## Objectif

Modifier la variable de .env.sample qui est copié dans .env lors du setup.
Y aurait il des effets de bords ?

## Technique

Informations techniques :

Même problème avec Chrome et Firefox.

**Comment by francois-ferrandis** [comment]
Bien vu, en effet on peut mettre une valeur vide, d'après ce que je vois dans la doc Sentry ça désactive simplement Sentry silencieusement (pas d'erreur).

> If you do not wish to send events in an environment, we suggest you unset the SENTRY_DSN variable in that environment.

https://docs.sentry.io/platforms/ruby/configuration/options/
