### ISSUE TITLE
Les notifications de création de RDV collectifs ne partent pas vers les usagers ajoutés après la création du RDV

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#2784]
## Actuellement

Description du problème utilisateur : 
"Je constate un "problème" sur RDV-Solidarités lors de la création d'ateliers collectifs. Quand je créé l'atelier pour le premier participant, celui ci revoit bien la notif de RDV.
Mais quand j'ajoute des participants à un RDV existant ils ne reçoivent pas la notif de "création", uniquement la notification de relance (si j'en crois les notifications envoyées)."

## Objectif

Reproduire en local.
Modifier le fonctionnement des envois des notifications pour les ateliers collectifs quand l'agent ajoute des participants après la création de l'atelier. Le participant ajouté doit recevoir une notification de création et pas une relance.

**Comment by Holist** [comment]
J'ai tenté de reproduire le problème en local mais les notifications fonctionnent correctement que ce soit l'annulation quand on enlève un usager d'un rdv avec motif collectif ou l'ajout d'un nouvel usager dans un rdv avec motif collectif existant. (c'est bien une notification de 'Création' qu'il reçoit. Tout est visible dans l'historique des notifications : 
![Capture d’écran 2022-09-07 à 16 12 20](https://user-images.githubusercontent.com/28594222/188900331-ed096e89-f67e-473c-b7e9-21add59bd6de.png)
Par contre effectivement pour des RDV avec motif **individuel** les notifications se font uniquement à la création ou à la relance. L'ajout ou la suppression d'usagers supplémentaires (dans le cas des différents membres de la familles j'imagine) ne déclenche pas de nouvelle notification pour les rdv individuels (Est ce voulu ?).
@victormours A priori c'est toi qui a été contacté par la CNFS. Est elle certaines d'avoir utiliser un motif collectif ? (c'est pas facile de faire la différence entre les 2 quand on choisi le motif, d'ailleurs j'ai ouvert une issue à ce sujet : https://github.com/betagouv/rdv-solidarites.fr/issues/2788)

**Comment by victormours** [comment]
Discussion en visio : on a retrouvé le compte qui a remonté le bug et le rdv qui a posé problème, on continue les recherches à partir de là.

**Comment by Holist** [comment]
Les agents ont 2 façons d'ajouter des usagers à un rdv collectif : 
- Via l'edit d'un rdv (qu'il soit collectif ou non) en modifiant les usagers (ajout/suppression) directement. (Notifs OK)
- Via le bouton "Ajouter un participant" sur un rdv dans l'index des rdv collectifs. (Notifs KO)

Effectivement le comportement de l'edit d'un rdv collectif via le contrôleur rdvs puis le service rdv_updater et le service  rdv_collectifs_participations fonctionne correctement. 
Ce qui ne fonctionnait pas (à cause d'une variable mal assignée : previous_participants) c'était le contrôleur rdvs_collectifs qui utilise le service rdv_collectifs_participations directement.
Dés que le rdv était update la variable n'était plus cohérente et le service ne trouvait pas de différence entre les participants avant et aprés modification du rdv donc pas de notif.
