### ISSUE TITLE
Paramétrage de la réservation en ligne

### ISSUE THREAD

**Issue by sebastiencarceles** [betagouv/rdv-solidarites.fr#2804]
Ajouter dans l’interface agent une section qui fournit le lien ainsi que des explications sur comment proposer des RDVs sans sectorisation (option de motif “Réservable par les usagers dans l'ensemble du département”).

## Objectif

On souhaite rendre visible aux agents l’état de la réservation en ligne pour leur organisation (leur permettre de savoir à quel point c’est possible de réserver en ligne, sous quelles conditions).

On souhaite également rendre claires les actions nécessaires pour augmenter ou diminuer le nombre de réservations en ligne.

## Solution proposée

Créer une page de paramétrage pour la réservation en ligne, accessible aux agent·es. Cette page, placée dans `Paramètres > Réservation en ligne`, synthétise : 
- les motifs
- les plages d'ouverture
- le lien à partager

Cette page est visible pour les agents basiques et les admin. 

### Motifs

Pour les admin :

- Lorsqu'il n'y a pas de motif, un CTA invite l'agent·e à en ajouter, avec des instructions qui concerne la réservation en ligne.
- Lorsqu'il y a des motifs, leur édition est possible.

### Plage d'ouverture

Lorsqu'il n'y a pas de plage d'ouverture, un CTA invite l'agent·e à en ajouter, ou mettre un texte d’explication qui indique comment en ajouter (planning, puis sélectionner agent, puis plages d’ouvertures).

Lorsqu'il y a des plages d'ouverture, leur édition est possible.

On peut proposer un agenda des plages d'ouverture.

Ajouter un texte d’aide qui indique que toutes les plages d’ouvertures pour ces motifs seront réservables en ligne.

### Lien vers la réservation publique de l'organisation

> Activer la réservation publique "à la calendly" pour les cnfs :
> - lien scopé par organisation, avec l'external id s'il est présent, et l'id normal sinon, visible sur le organisation#show s'il y a des réservations possibles (plage d'ouverture). En arrivant sur ce lien, on choisit un motif, puis un lieu (sauf s'il n'y en a qu'un de dispo), puis un créneau

Il s'agit du lien proposé dans la PR #2798.

Ce lien devrait être immédiatement visible, afin que l'agent·e comprenne tout de suite quelle est la finalité de la page. Toutefois, il n'est accessible ou utilisable qu'à partir du moment où les motifs et les plages d'ouvertures sont renseignés.

Enfin, il faut proposer un moyen (ou expliquer à l'agent·e) comment ouvrir ce lien en tant qu'usager·ère, afin de vérifier son usage.

## Technique

Repartir du prototype proposé par @victormours : https://github.com/betagouv/rdv-solidarites.fr/compare/production...spike-online-booking

![image](https://user-images.githubusercontent.com/1193334/190106225-75f4a94d-8506-48ba-a697-b86e29a2cefb.png)

### Références

https://juvenile-limburger-f93.notion.site/Prise-de-RDV-par-des-usagers-227911452f5645e3bb5599a51a6da746

**Comment by sebastiencarceles** [comment]
@yaf j'attire ton attention ici pour qu'on en discute ultérieurement, dans le cadre du médico-social :)

**Comment by yaf** [comment]
Je pose ici une surprise de voir cette entrée de menu dans le menu paramètre, surtout si elle est ouverte à tous les agents. Mais peut-être que vous avez de bonnes raisons de le faire pour les CNFS (qui effectivement sont de toute façon tous des admin).

> Ajouter un texte d’aide qui indique que toutes les plages d’ouvertures pour ces motifs seront réservables en ligne.
Il est possible de faire des plages d'ouvertures avec des motifs qui ne sont pas ouverts en ligne (très utile pour la recherche de créneau « interne »). Aussi, je ne suis pas sûr de comprendre ce point.

En l'état, ce n'est pas vraiment ok pour le medSoc. Le visuel sur les plages d'ouverture serait intéressant (voir #1919 qui évoque déjà ce point). Si le visuel est sur l'index des plages d'ouverture, ça pourrait être un point intéressant pour le medsoc.

**Comment by sebastiencarceles** [comment]
> Je pose ici une surprise de voir cette entrée de menu dans le menu paramètre, surtout si elle est ouverte à tous les agents. Mais peut-être que vous avez de bonnes raisons de le faire pour les CNFS (qui effectivement sont de toute façon tous des admin).

Faudrait-il que cette entrée soit accessible : 
- seulement aux agent·es admin
- ou bien seulement aux agent·es CNFS
?

Je ne comprends pas bien ton point sur les plages d'ouverture @yaf . Peux-tu le détailler ici stp, ou bien on en discute à l'oral lundi ?

**Comment by yaf** [comment]
Pour l'histoire du paramétrage, c'est un menu qui pour moi devrait être déplacé dans le module de configuration, et surtout rester accessible à un nombre réduit d'agent. C'est un menu qui n'est pas visible aujourd'hui aux agents sans droit d'administration de l'organisation. Bref, tout ça pour dire que c'est un accès restreint et ça fait bizarre d'envisager de l'ajouter pour d'autres.

Je pense donc que pour le moment, ça serait mieux de faire l'exploration que pour les CNFS. J'aimerais bien mettre en place une sorte de page d'accueil (ou une évolution de la page d'embarquement ?) pour amener ce genre de chose (voir le ticket #1403 )



Pour les plages d'ouvertures, dans la page d'index actuel des plages d'ouvertures, nous avons une liste textuelle, trié sur la date de dernières modifications (discutable). Cette visualisation n'apporte pas grand-chose, et particulièrement l'information manquante sur la répartition d'occupation dans la semaine, voir le mois à venir. Aussi, afficher un index « visuel » des plages d'ouverture serait super top #1919 

C'était en réaction à ta phrase
> On peut proposer un agenda des plages d'ouverture.
que j'ai interprété comme une vue agenda des plages d'ouvertures, qui correspondrait plutôt bien à ce que j'évoque pour modifier la page index des plages d'ouvertures...

Est-ce que c'est plus clair ?

**Comment by sebastiencarceles** [comment]
> Pour l'histoire du paramétrage, c'est un menu qui pour moi devrait être déplacé dans le module de configuration

Je suis un peu embêté avec ça. Il me semble que le module de configuration agit au niveau du territoire. Mais ici, on parle de motifs et de plages d'ouverture, donc on est plutôt au niveau de l'organisation, non ?

> et surtout rester accessible à un nombre réduit d'agent

> Je pense donc que pour le moment, ça serait mieux de faire l'exploration que pour les CNFS

Dans ce cas affichons cette entrée de menu seulement pour les agents CNFS, ok ? En tout cas dans un premier temps.

> Aussi, afficher un index « visuel » des plages d'ouverture serait super top https://github.com/betagouv/rdv-solidarites.fr/issues/1919

OK je comprends mieux, merci pour les détails ! Effectivement ça serait mieux. À voir si c'est à faire dans le cadre de cette issue, ou bien si on le fait dans un deuxième temps, de façon coordonnées avec #1919.

**Comment by yaf** [comment]
> > Pour l'histoire du paramétrage, c'est un menu qui pour moi devrait être déplacé dans le module de configuration
> 
> Je suis un peu embêté avec ça. Il me semble que le module de configuration agit au niveau du territoire. Mais ici, on parle de motifs et de plages d'ouverture, donc on est plutôt au niveau de l'organisation, non ?

Oui, tu as complétement raison.

> > et surtout rester accessible à un nombre réduit d'agent
> 
> > Je pense donc que pour le moment, ça serait mieux de faire l'exploration que pour les CNFS
> 
> Dans ce cas affichons cette entrée de menu seulement pour les agents CNFS, ok ? En tout cas dans un premier temps.

Oui, ça me semble ok. Merci.

**Comment by sebastiencarceles** [comment]
D'ailleurs j'ai une question ici pour toi @victormours , par rapport à ton commit https://github.com/betagouv/rdv-solidarites.fr/commit/fe9462f885b1011e2656b32f2009b916b1951931

Faudrait-il ajouter les motifs réservables en ligne au setup des conseillers numériques, comme pour les autres agents ?

**Comment by victormours** [comment]
Il y a une erreur sur la section `Objectif` de l'issue : notre objectif n'est pas de créer une page de paramètrage pour la réservation. Notre objectif dans le cadre de cet issue est :
- rendre visible aux agents l’état de la réservation en ligne pour leur organisation (leur permettre de savoir à quel point c’est possible de réserver en ligne, sous quelles conditions)
- rendre claires les actions nécessaires pour augmenter ou diminuer le nombre de réservations en ligne
(ce sont les besoins qui apparaissent sur le notion)


L'ouverture d'une page de paramétrage est un moyen possible pour atteindre cet objectif. On pourra trouver d'autres implémentations en fonction des recherches et des retours terrain.

J'insiste sur la distinction entre l'objectif métier et la solution technique pour deux raisons :
- si on oublie pourquoi on fait ça, on dévie et on part sur des solutions qui ne répondent plus à ce besoin. Par exemple, le besoin des agent non admin de savoir quels sont les rdvs qui peuvent être pris en ligne, et à quel moment, nous donne du contexte sur la présence potentielle de cette page dans le menu paramètres
- pour l'historique, dans un an quand on se demandera si cette page est encore pertinente, on aura besoin de savoir pourquoi elle est là. Il nous faut cette info dans l'issue.

**Comment by victormours** [comment]
Par ailleurs, dans la direction stratégique notée dans notion, il y a "faciliter la prise de rendez-vous entre l'usager et les services de proximité", et cette fonctionnalité rentre complètement dans ce cadre. Il faut qu'on fasse un peu de recherche auprès des référentes dans le cadre de ce ticket et de https://github.com/betagouv/rdv-solidarites.fr/pull/2798 pour voir comment on peut rendre ça adapté au médico social

**Comment by sebastiencarceles** [comment]
OK merci pour la distinction objectif / solution @victormours , c'est important en effet. J'ai modifié l'issue en ce sens.

**Comment by victormours** [comment]
Nickel !

Pour la liste des motifs, c'est probablement important de distinguer les motifs pour lesquels la réservation en ligne est activée des autres (c'était peut-être sous-entendu dans la description de l'issue, mais je voulais être sûr que ça soit clair). Dans la pratique, il n'y aura quasiment jamais d'organisation sans motif, mais il y en a beaucoup qui n'ont que des motifs qui ne sont pas réservables en ligne.

Pour la liste des plages d'ouverture, là aussi c'est pertinent d'afficher uniquement les plages d'ouvertures pour les motifs qui ont de la réservation en ligne.

**Comment by yaf** [comment]
Pour le médico-social, elles savent déjà faire l'ensemble (motifs et plage d'ouverture) depuis 2 ans. Le truc en plus ici serait le lien pour inviter un usager à prendre un RDV, mais il faudrait que ce soit pour le service et non pour l'organisation (comme déjà évoqué).

Pour que ce soit intéressant pour le médico-social, il faudrait donc avoir une action, à priori plutôt autour de l'usager, pour l'inviter à prendre RDV (voir  #1972 qui était en gros une envie de proposer ce qu'a mis en place RDV-I, mais depuis RDV-Solidarités).

À noter que ce n'est clairement pas un besoin exprimé, c'est un truc que l'on pousse de notre côté. Et l'invitation / lien me semble une bonne proposition s'il permet de le faire dans un contexte médsoc.

**Comment by sebastiencarceles** [comment]
Hello tout le monde

Voici une démo du périmètre en cours de développement. Je suis preneur de vos avis SVP (vous pouvez aussi intervenir directement sur la PR #2825).

Lorsqu'un agent CNFS arrive sur la page de paramétrage et qu'il n'y a pas encore de motif ouvert à la réservation, voici ce qu'on affiche : 

![image](https://user-images.githubusercontent.com/1193334/191757433-53d1a604-7b63-47d4-b40f-30cc33fd6746.png)

J'espère que les explications sont claires et je suis naturellement intéressé par vos retours, notamment pour adopter le vocabulaire le plus commun possible dans l'application.

J'ai un gros doute sur le footer de la partie "Plages d'ouverture" : est-ce très utile d'avoir ici un raccourci rapide pour accéder à mes propres plages d'ouverture ?

Ensuite, lorsqu'on a des motifs ouverts à la réservation en ligne : 

![image](https://user-images.githubusercontent.com/1193334/191758056-9fc88704-8f90-4b9d-bfbd-5af22d0735dc.png)

J'ai récapitulé les infos qui me semblaient les plus pertinentes uniquement.

Lorsqu'on a des plages d'ouverture liées aux motifs ouverts à la réservation : 

![image](https://user-images.githubusercontent.com/1193334/191758621-0cf3ba0b-43d0-422d-a945-4a5421612be2.png)

(il y a une faute d’orthographe, je vais corriger)

Là encore j'ai essayé de rester succinct pour éviter de surcharger la page d'informations.

Enfin, lorsqu'il y a des motifs réservables en ligne et des plages d'ouverture, le lien à partager devient copiable : 

![image](https://user-images.githubusercontent.com/1193334/191758929-5000464f-5fb6-4433-a202-277226d1bc7d.png)

Je pense qu'il y a un petit travail d'amélioration de l'UI ici, et peut-être des explications, les suggestions sont les bienvenues.

Merci !

**Comment by sebastiencarceles** [comment]
@victormours j'ai vu dans la feuille de route la mention suivante : 

> Cette page est visible pour les agents basiques et les admin. La version pour les admins inclut des CTA supplémentaires pour gérer les motifs

Pourtant, il me semble qu'on a dit au contraire qu'on voulait limiter la feature aux agent·es CNFS admin. J'ai peut-être mal compris. Peut-être faut-il : 
- limiter l'accès à "Paramètres > Réservation en ligne" aux CNFS

Mais toutefois : 
- laisser les admin accéder à tout
- limiter les basic à de la visualisation

Dit autrement, les basic n'auraient pas les CTA pour gérer les motifs et les plages d'ouverture. Qu'en penses-tu ? Est-ce que c'est ce qu'on souhaite ici ?
