### ISSUE TITLE
Lisibilité des motifs : extraire la réservation en ligne

### ISSUE THREAD

**Issue by sebastiencarceles** [betagouv/rdv-solidarites.fr#2808]
## Actuellement

Sur l'affichage et l'édition des motifs, on comprend mal ce qui est du domaine de la réservation en ligne.

### Affichage

![image](https://user-images.githubusercontent.com/1193334/190111582-13ccf1ce-4ebe-46e7-a84c-7c1ea5e23b3c.png)

### Édition

![image](https://user-images.githubusercontent.com/1193334/190111652-c6009da3-76a1-4a81-8392-151f1eb8b3c6.png)

## Objectif

Améliorer la lisibilité des motifs, en ce qui concerne la réservation en ligne.

### Affichage

Trouver un moyen de rendre plus lisible la partie “réservation en ligne”.

### Édition

Faire une édition séparée des champs qui concernent la réservation en ligne.

=> proposer à l'équipe un prototype, même non fonctionnel, pour en discuter.

## Références

Lié à #2721

**Comment by yaf** [comment]
Merci d'avoir écrit ça, c'est excellent !

J'ajoute un petit point de méfiance sur le fait d'essayer d'avoir une cohérence entre les différents formulaires du service.
Il y a aujourd'hui déjà pas mal d'écart d'un formulaire à l'autre : sur plusieurs pages pour les RDV, via une « popup » pour la mise à jour des usagers dans certain cas de figure, après une vue « show » pour d'autres... 

Ce ticket est une opportunité de plus de parler de tout ça et de trouver une orientation générale cohérente.
