### ISSUE TITLE
Changement visuel pour les listes de RDVs

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#2816]
Pré-requis d'UX pour les futurs fonctionnalités avec un tableau des participants (Participations individualisées, futures modifications du système de "proche" et de "responsable")
Le figma est disponible dans le pad.
La modification d'interface concernera tous les RDV (Collectifs et Individuels) dans la liste des RDVs.
On réutilise le travail de #2805 

Question : @yaf Quel serait le comportement attendu du switch 'Afficher les participants' dans la nouvel UX ?
Info : Le bouton "détail usager" a été enlevé car il n'est plus pertinent en terme d'UX et très peu utilisé.

## Actuellement

![Capture d’écran 2022-09-15 à 12 01 06](https://user-images.githubusercontent.com/28594222/190376031-2d8556c9-2b39-4c02-ad28-4e7c2c091ef3.png)

## Objectif

![ListeRDV](https://user-images.githubusercontent.com/28594222/190376069-052857db-bae2-48ef-91f2-b3d956dc55cd.jpg)

**Comment by yaf** [comment]
Le switch proposé par Anne-Sophie affichait le tableau des participants. Ce qui veut dire que par défaut, il n'est pas affiché et qu'il faut changer le switch pour les voir (contrairement à la copie d'écran qui est là)
