### ISSUE TITLE
Problème de SMS non délivrés ("Invalid campaign name")

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2822]
Issue Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3611921205

## Edit du 20 octobre 2022

Nous avons reçu une réponse de netsize : 

> Le problème est que notre plateforme limite à 200 le nombre de noms de campagne possibles chaque 24h pour un seul et même compte technique. A vrai dire, cette limitation n’est habituellement jamais atteinte. En effet, il n’est pas nécessaire de créer un nouveau nom de campagne pour chaque envoi. Est-ce ce que vous faites ?
>
> Si vous réutilisez plusieurs fois le même nom de campagne pour vos envois de messages, vous ne devriez plus rencontrer de blocage de votre compte.

Source : https://zammad10.ethibox.fr/#ticket/zoom/2989

Il paraît donc judicieux de limiter la variabilité des noms de campagne.

## Actuellement

_ref https://zammad10.ethibox.fr/#ticket/zoom/2666_

Le 12 septembre, une situation a amené les services médico-sociaux de la Drôme à annuler les RDV du lendemain (13 septembre) pour un certain nombre de personnes.

Certaines ont bien reçu le SMS d'annulation, d'autres non...

## Objectif

Comprendre ce qu'il s'est passé, et, si possible, apporter une correction pour s'assurer que la situation ne se reproduise pas.

À priori, aucun problème sur les numéros, certaines de ces personnes ont reçu des SMS pour d'autres RDV et pour la création du RDV annulé.

**Comment by francois-ferrandis** [comment]
Quand j'aurai trouvé le temps de publier ma PR pour #2748, on aura une meilleure visibilité sur les échecs d'envois de SMS.

Bien sûr rien n'empêche d'investiguer cette issue entre temps.

**Comment by francois-ferrandis** [comment]
Une seconde PR ajoute encore plus de logging sur les envois, j'espère qu'elle nous permettra de mieux enquêter : https://github.com/betagouv/rdv-solidarites.fr/pull/2866

**Comment by yaf** [comment]
Nous venons de poser un ticket sur linkmobiliy/netsize pour avoir des explications sur le problème « invalid campaign name » qui est assez incompréhensible au vu des analyses que nous avons faites cette après-midi.
