### ISSUE TITLE
Erreur d'interconnexion avec la Drôme : changement d'organisateur dans les event ICS et mailer ?

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2823]
## Actuellement

Il y a de nombreux problèmes d'interconnexion avec la Drôme.

La DSI de la Drôme et leur prestataire en charge de l'interconnexion avec Zimbra ont analysé les logs d'erreurs de leur côté.

>  (1) organisateur = "secretariat-auto@rdv-solidarités.fr"
> Dans nos logs, les erreurs liées à un changement d'organisateur de rdv sont récurrentes. Zimbra n'accepte pas la modification de l'organisateur (comportement normal) et génère un rejet de la demande.
> Ce changement d'organisateur concerne le compte "secretariat-auto@rdv-solidarités.fr" (modifié pour le compte d'un agent @ladrome.fr), et les rdv impactés sont des créations ou des modifications de rdv.
> Si les développements de notre prestataires sont peut-être à améliorer, ce que nous ne comprenons pas c'est l'apparition de ces erreurs (cf log en bas de ce message).
> Pourquoi et depuis quand ce compte est-il utilisé ?
> Il y a t-il eu d'autres modifications sur la plateforme depuis ces 20 derniers jours ?

et

> Ci-dessous un exemple de bug lié à l'organisateur :
>  
> 2022-09-14 14:49:13,189 INFO app uWSGIWorker4Core0 : Mise à jour d'un rdv
> [...]
> 2022-09-14 14:49:13,189 INFO app uWSGIWorker4Core0 : Mise à jour d'un rdv pour example@ladrome.fr
> 2022-09-14 14:49:13,189 INFO app uWSGIWorker4Core0 : Authentification admin Zimbra
> 2022-09-14 14:49:13,230 INFO app uWSGIWorker4Core0 : Authentification admin Zimbra fonctionnelle
> 2022-09-14 14:49:13,259 INFO app uWSGIWorker4Core0 : Session valide.<zimsoap.client.ZimbraAdminClient object at 0x7fc4d
> 35db940>
> 2022-09-14 14:49:13,260 INFO app uWSGIWorker4Core0 : Création du token d'authentification Zimbra pour le user jbonhoure
> @ladrome.fr
> 2022-09-14 14:49:13,291 INFO app uWSGIWorker4Core0 : Token créé pour le user example@ladrome.fr
> 2022-09-14 14:49:13,292 INFO app uWSGIWorker4Core0 : Connexion via authtoken
> 2022-09-14 14:49:13,319 INFO app uWSGIWorker4Core0 : Test de validité de la session
> 2022-09-14 14:49:13,320 INFO app uWSGIWorker4Core0 : Récupération des infos du rdv: 3b35e8c1-7c5f-4ddf-8f43-cb1aa4f50f3
> 6
> 2022-09-14 14:49:13,355 INFO app uWSGIWorker4Core0 : Génération d'un id valide pour 6672
> 2022-09-14 14:49:13,355 INFO app uWSGIWorker4Core0 : Maj du rdv : 3b35e8c1-7c5f-4ddf-8f43-cb1aa4f50f36
> 2022-09-14 14:49:13,407 INFO app uWSGIWorker4Core0 : Can't update appointment.service.INVALID_REQUEST: Removing ORGANIZER 'secretariat-auto@rdv-solidarites.fr' for an appointment is not allowed
>  

## Objectif

Réduire le nombre d'erreurs.

## Technique

C'est peut-être lié au changement apporté par le commit https://github.com/betagouv/rdv-solidarites.fr/commit/02f470b7490cfdad7a58181b15459d173bb6da71 ?

**Comment by francois-ferrandis** [comment]
Je viens de merger https://github.com/betagouv/rdv-solidarites.fr/pull/2831 ; est-ce que l'on peut demander si ça a corrigé l'erreur de leur côté ? Est-ce qu'on a un ticket Zammad @yaf ? :slightly_smiling_face:

**Comment by yaf** [comment]
Il semblerait que ce soit bon. Je ferme ce ticket.
