### ISSUE TITLE
Dans les statistiques, Compter une seule fois les agents travaillant dans plusieurs organisations

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2826]
## Actuellement

ref https://zammad10.ethibox.fr/#ticket/zoom/2680

Dans la page des [statistiques](https://www.rdv-solidarites.fr/stats), nous comptons plusieurs fois les mêmes agents.

```
irb(main):005:0> Territory.where(departement_number: "26").first.organisations.map(&:agents).flatten.count
=> 639
irb(main):006:0> Territory.where(departement_number: "26").first.organisations.map(&:agents).flatten.uniq.count
=> 450
```

![Screenshot 2022-09-16 at 21-34-27 Statistiques pour le Drôme - 26 - RDV Solidarités](https://user-images.githubusercontent.com/42057/190716884-0cdf3da3-04c3-4126-9cf3-68dfaeaf6650.png)

## Objectif

Compter une seule fois les agents qui travaillent dans plusieurs organisations (cas fréquent en médico-social).

**Comment by DanteZ5** [comment]
pas encore contributeur, mais je suis dessus. 
hypothèse du `joins()` sur `def scope_rdv_to_territory` du `StatsController`
