### ISSUE TITLE
Afficher le bon nombre de personnes participantes à un RDV collectif

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2828]
## Actuellement

Côté agents ;
Lorsque j'ajoute un usager à un RDV collectif ;
Le compteur affiche 2 participants alors qu'il n'y en a qu'un

![Screenshot 2022-09-20 at 09-45-09 RDV Atelier Collectif - RDV Solidarités](https://user-images.githubusercontent.com/42057/191198287-5d789111-e10c-41f9-85cf-a32784e61d3b.png)

## Objectif

Afficher le bon nombre de personnes participantes

**Comment by Holist** [comment]
@yaf Je suis sur la branche concernant la refonte de la show et j'ai vu ce bug. Tu ne l'as pas constaté en prod ?
A priori ce n'est rien et seulement lié au seed qui démarre le counter users_count à 1 pour les rdv collectif seedé au lieu de 0. Je règle ca dans la PR de la nouvelle interface.
https://github.com/betagouv/rdv-solidarites.fr/blob/6bc024ec4932468671286ed55827af67f271e0aa/db/seeds.rb#L888

**Comment by Holist** [comment]
https://github.com/betagouv/rdv-solidarites.fr/pull/2834
