### ISSUE TITLE
Supprimer la plage d'ouverture sans attendre 

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2841]
## Actuellement

ref https://zammad10.ethibox.fr/#ticket/zoom/2733

Lors de la suppression d'une plage d'ouverture, celle-ci semble ne pas avoir été supprimé (elle reste visible dans l'index après avoir appuyé sur le bouton).

Si on clique sur la plage que l'on vient de supprimer, nous arrivons sur une page 404.

## Objectif

Il y a un mécanisme de délai qui est mis en place dans le contrôleur pour s'assurer qu'au moment de l'envoi de la notification de suppression de plage, nous accédons encore à la plage d'ouverture (pour construire le mail).

Il y a sans doute moyen de préparer le mail et de ne l'envoyer que si la suppression a fonctionné.

**Comment by francois-ferrandis** [comment]
Entré Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3527661990
