### ISSUE TITLE
Permettre la prise de RDV via un lien public vers le service

### ISSUE THREAD

**Issue by sebastiencarceles** [betagouv/rdv-solidarites.fr#2855]
## Actuellement

Depuis #2798, on permet la prise de RDV sans sectorisation grâce à un lien public. Ce lien permet de prendre RDV auprès d'une organisation, ce qui est utile aux agent·es CNFS.

## Objectif

Permettre la prise de RDV grâce à un lien public **auprès d'un service** (et non d'une organisation). C'est une première étape vers la réservation en ligne pour le médico-social.

## Solution

À la manière de #2798, on se propose d'ajouter la route : `/ser/:territory_slug/:service_id`.

Cette route redirige vers la recherche, filtrée sur le service et le territoire indiqués.

![image](https://user-images.githubusercontent.com/1193334/192512465-9907c05c-123a-44ad-a094-3ac4ee42c71e.png)

**Comment by sebastiencarceles** [comment]
@victormours @yaf @francois-ferrandis pour votre aimable relecture SVP.

**Comment by francois-ferrandis** [comment]
D'un point de vue métier, est-ce qu'on ne va pas aussi avoir besoin de spécifier un département ?

**Comment by yaf** [comment]
Ça dépend. Il y a un projet de « libérer les services » pour que chaque service soit lié à un département (et non général) #1807 

Parce que là, effectivement, est-ce qu'on affiche la liste des motifs pour toute la France ?

**Comment by sebastiencarceles** [comment]
Merci pour vos retours. Je vous invite à review ma proposition ici : https://github.com/betagouv/rdv-solidarites.fr/pull/2859

Ensuite, comment va-t-on donner accès à cette info aux agent·es du médico-social ? Spontanément, j'aurais envie d'enrichir le paramétrage de la réservation en ligne, notamment la partie "lien de réservation".

![image](https://user-images.githubusercontent.com/1193334/192731175-d74fb8f0-24c7-495d-8879-940efcd35030.png)

Je pense à : 
- donner accès à cette page à tous·tes les agent·es
- proposer dans cette section _plusieurs_ lien de réservation à partager : celui vers l'organisation, mais aussi ceux vers les services

On aurait ainsi un peu de réconciliation entre le MedSoc et le CNFS. Qu'en pensez-vous ? Est-ce que ça fonctionnerait ?

**Comment by yaf** [comment]
Autant, je pense que l'idée de modifier un peu le parcours est bonne, mais en médico-social, les agents, pour beaucoup, savent faire leurs plages d'ouvertures depuis 2 ans et très peu ont le droit de toucher aux motifs.
Le menu « paramètre » d'une organisation est à accès très restreint (invisible pour les autres agents) et c'est à garder comme ça. 

Le paramétrage serait à placer ailleurs, je pense.

Pour moi, ce qui serait intéressant dans le médico social, c'est d'avoir, dans une fiche usager, un bouton pour « inviter » l'usager à prendre RDV, et donc d'avoir, à partir de là, une page permettant de préciser sur quel motif l'inviter (un ou plusieurs ?) et d'afficher les plages qui vont être proposé du coup (et s'il n'y en a pas, orienter sur l'écran des plages).

Bref, le même écran globalement si j'ai bien compris (ou à peu près), mais depuis la fiche usager, et avec l'envoi d'une invitation plutôt qu'un lien à copier (les personnes en médico-social ne sont pas toujours à l'aise avec le numérique contrairement aux CNFS)

Je ne sais pas si je suis très clair. En tout cas, je suis dispo pour en parler.

**Comment by sebastiencarceles** [comment]
Super intéressé pour en parler, je te mattermoste à ce sujet.

**Comment by sebastiencarceles** [comment]
Suite à discussions, il apparaît que le besoin est mal formulé ici. Le médico-social bénéficierait plutôt d'un mécanisme d'invitations. C'est synthétisé ici : https://github.com/betagouv/rdv-solidarites.fr/issues/1972
