### ISSUE TITLE
Travaux sur les statistiques (visuel sur l'URL de stats : avoir un deuxième tableau)

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#2863]
Travaux sur les statistiques (visuel sur l'URL de stats : avoir un deuxième tableau)
L'idée est de modifier les différentes pages de statistiques pour prendre en compte le champ de participation aux rdv (rdvs_users.status)
Dans un premier temps on va ajouter de nouveaux charts dédiés à la participation.
Ex :
![Capture d’écran 2022-10-04 à 09 29 26](https://user-images.githubusercontent.com/28594222/193760323-7cf46ff1-10b9-4b91-abe6-b21604853740.png)
![Capture d’écran 2022-09-29 à 17 09 20](https://user-images.githubusercontent.com/28594222/193069347-4271bd75-c413-4afa-97f0-9b07fb8fea29.png)

**Comment by DanteZ5** [comment]
Hello @Holist 
Est ce un travail sur lequel tu codes ?
Vu avec @victormours, j'aimerais amorcer un travail sur l'enrichissement des statistiques, notamment pour monitorer l'usage de la prise de rdv public / réservables en ligne. Si tu ne travailles pas sur cette issue directement, je peux l'intégrer au passage.. tu me dis ^^

**Comment by yaf** [comment]
Attention, je pense que ce n'est pas le bon tableau dans la copie d'écran...

**Comment by yaf** [comment]
Je pensais à celui-ci surtout.

![Screenshot 2022-10-03 at 20-39-40 Statistiques - RDV Solidarités](https://user-images.githubusercontent.com/42057/193653562-48ccee18-cf02-4f28-821f-e136d0dc7d9a.png)


Mais tu as raison, la question se pose aussi pour ce premier tableau.

**Comment by Holist** [comment]
> 

j'ai mis à jour l'issue avec la capture de ce que j'ai déjà fait (mais que je n'ai pas encore eu le temps de vraiment tester/debug)

**Comment by Holist** [comment]
> 



> 

@DanteZ5 Tu peux travailler sur les stats sans problème.
Le travail que j'ai fait ici est assez simple (j'ai juste adapté l'existant en changeant la cible du **status**).
Si besoin je le referai une fois qu'on aura terminé avec les status de participation des usagers et l'ouverture au public.
