### ISSUE TITLE
:broom: supprimer l'utilisation de `api_options`

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#2870]
## Actuellement

Dans les webhooks, nous avions eu à maintenir deux versions des statuts pendant un temps... 

## Objectif

Vérifier que nous n'utilisons plus `territory.api_options` et si oui, supprimer ce champ et les mécanismes associés.

@aminedhobb il me semble que c'est un truc que nous avions mis en place pour le temps que le 92 change son code pour intégrer les nouveaux statuts. Est-ce qu'il y a ou avait un autre usage à cela ? Tu es le dernier à avoir bricolé avec ça il me semble : https://github.com/betagouv/rdv-solidarites.fr/commit/d4078b9ea863dca7c2aea5772094054bc2005176

**Comment by aminedhobb** [comment]
> @aminedhobb il me semble que c'est un truc que nous avions mis en place pour le temps que le 92 change son code pour intégrer les nouveaux statuts. Est-ce qu'il y a ou avait un autre usage à cela ? Tu es le dernier à avoir bricolé avec ça il me semble : [d4078b9](https://github.com/betagouv/rdv-solidarites.fr/commit/d4078b9ea863dca7c2aea5772094054bc2005176)

Ça a été mis en place avant que j'arrive, mais oui il me semble que vous aviez mis ça en place pour répondre aux demandes d'un département. En tous cas nous sur RDVI on utilise pas ces options, donc ça ne nous dérange pas de les supprimer.
