### ISSUE TITLE
Rendre plus lisible plages d'ouverture / indisponibilité dans la vue Agenda 

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#2893]
## Actuellement

Lorsqu'un utilisateur pose des plages d'ouvertures et des indisponibilités, le visuel n'est pas très lisible. Les blocs d'indisponibilités et les plages d'ouverture s'entreposent dans la vue principale de l'agenda. Cette remontée est à la demande des utilisateurs (agents et CnFS).   

<img width="1240" alt="Capture d’écran 2022-10-05 à 11 48 13" src="https://user-images.githubusercontent.com/103633345/194032437-5ed820dd-4089-4405-9352-d644390fd4f8.png">

## Objectif

Nous souhaitons avoir un affichage plus lisible. Solutions envisagées : 
- des blocs côte à côte ?
- jeu de transparence ? (cf image ci-dessous)

<img width="859" alt="Capture d’écran 2022-10-05 à 10 30 07" src="https://user-images.githubusercontent.com/103633345/194029971-d37951f2-b1be-465b-8cde-51ce5ec71aca.png">

**Comment by yaf** [comment]
C'est amusant parce que je trouve que c'est moins lisible comme ça....

L'indisponibilité qui vient par-dessus le reste montre clairement que c'est elle qui prend le dessus. Le reste « n'existe » plus. Alors que là, avec la transparence, on se demande si la plage d'ouverture est encore disponible pour de la prise de RDV ? Est-ce que les RDV en dessous sont annulés ? C'est flou :)
