### ISSUE TITLE
Rediriger la suppression des RDV vers la page la plus pertinente

### ISSUE THREAD

**Issue by damienlethiec** [betagouv/rdv-solidarites.fr#2924]
## Actuellement

Aujourd'hui, la suppression d'un RDV redirige forcément à l'index des RDV individuels.

## Objectif

Au minimum, rediriger la suppression des RDV collectifs à l'index des RDV collectifs.
Dans l'idéal, si un RDV est supprimé depuis sa show, rediriger vers la page à partir de laquelle l'utilisateur a accédé à la show.

**Comment by yaf** [comment]
En fait, il y a un bout de ticket lié déjà, je crois #2838
