### ISSUE TITLE
Passer l'API en v2 pour faire évoluer la convention sur les réponses

### ISSUE THREAD

**Issue by sebastiencarceles** [betagouv/rdv-solidarites.fr#2957]
# Actuellement

Aujourd'hui les différents points de terminaison qui retournent des listes répondent par un hash de deux éléments.

```
{
  items: [
    {
      // item1
    },
    {
      // item2
    }
  ],
  meta: {
    // pagination data
  }
}
```

Ceux qui retourne une ressource unique encapsulent la réponse : 

```
{
  item:
    {
       // item data
    }
}
```

- le nom "items" varie en fonction de ce qu'on retourne, ça peut être "motifs" ou "organisations" par exemple
- à la base de la réponse, j'aimerais avoir directement les éléments que j'ai requêté, sans avoir à descendre d'un niveau dans un truc dont je dois connaître le nom au préalable

# Objectif

Toutes les réponses, de tous les points de terminaison qui retournent des listes, devraient avoir la même tête, celle-ci :

```
[
  {
    // item1
  },
  {
    // item2
  }
]
```

Et pour ceux qui retournent une ressource unique : 

```
    {
       // item data
    }
```

Les infos de pagination devraient être passées dans les headers de la réponse.

Comme on ne peut pas changer ce qui est déjà publié dans la v1, on peut le faire dans une v2 de l'API.

Par ailleurs, avoir une deuxième version de l'API va permettre l'introduction d'autres changements, en réduisant les risques pour la version 1 (donc pour les clients qui la consomment déjà). Par exemple, on peut limiter le nombre d'éléments maximum renvoyés par une page (ce n'est actuellement pas le cas de la V1, ce qui représente un danger potentiel pour l'application). On peut également décider d'introduire l'authentification par API KEY dans l'API publique (ce n'est pas le cas de `public_links`, seul point de terminaison public de la V1). Ou encore, on peut introduire le rate limiting, tout en garantissant qu'il n'y aura pas de changement pour les clients actuels de la V1.

**Comment by yaf** [comment]
Je ferme le ticket pour le moment, je vois que c'est fermé dans le tableau Aides Jeunes...
