### ISSUE TITLE
Limiter le nombre d'éléments retournés par les points de terminaison paginés

### ISSUE THREAD

**Issue by damienlethiec** [betagouv/rdv-solidarites.fr#2977]
# Actuellement

Lorsque le paramètre `per` n'est pas renseigné, on renvoie une page de 100 éléments.

# Objectif

Dans l'**API V2** :
- [ ] pour des raisons de perf, je propose de réduire à 25 par défaut
- [ ] pour des raisons de sécurité, je propose de limiter au maximum à 50 ; ainsi, si un·e client demande une page de 50000 entrées, le serveur se limite à 50 et ne risque pas de tomber

**Comment by sebastiencarceles** [comment]
Je propose de faire cette amélioration dans le cadre de l'API V1. Pour réduire les risques d'impact sur les clients actuels, on pourrait : 
- laisser le défaut à 100
- mettre la limite supérieure à 100

Ça m'étonnerait que beaucoup de clients demandent plus de 100 éléments par page, non ?

**Comment by damienlethiec** [comment]
Ma PR se focalise sur la V2 pour le coup. A voir si nécessaire d'adapter
