### ISSUE TITLE
Mettre en oeuvre un rate limiting dans RDV Solidarités

### ISSUE THREAD

**Issue by damienlethiec** [betagouv/rdv-solidarites.fr#2979]
Pour protéger l'API publique des abus, mais aussi potentiellement toute l'application, on propose à l'équipe l'installation du gem de rate limiting, comme par exemple [rack-attack](https://github.com/rack/rack-attack).

Pour éviter l'ajout d'une nouvelle dépendance, il serait aussi possible de se baser sur Redis pour écrire notre propre mécanisme de rate limiting. Je ne sais pas si c'est souhaitable, mais c'est a priori faisable : 
- https://blog.kiprosh.com/rate-limiting-using-redis/
- https://medium.com/@pebneter/fast-and-simple-rate-limiting-with-ruby-on-rails-and-redis-68e76ba38ca4

**Comment by sebastiencarceles** [comment]
Ça peut être fait dans le cadre de la V1, si on n'est pas trop stricts sur les critères de limitation :)

**Comment by damienlethiec** [comment]
Oui, j'ai changé mon fusil d'épaule au milieu de la PR. Je pensais la faire que sur la V2 et en fait ça avait du sens de l'avoir aussi sur la V1 (et c'est donc ce que propose la PR). Mais du coup je n'aurai peut être pas dû tirer ma branche depuis la branche qui s'occupe de la V2

**Comment by guillett** [comment]
Ça pourrait être bien mais est ce que cela vient répondre à un problème vécu pour le moment ?

Suite à l'échange que j'ai eu avec l'équipe Lapins (Victor & Yannick), ce n'est pas un problème pour eux pour le moment et ils n'auront pas le temps de faire une revue même si une PR était faite.

Je me dis donc que ce n'est pas un sujet sur lequel investir du temps.

**Comment by damienlethiec** [comment]
C'était un risque mis en avant par Victor au moment de la réflexion sur l'ouverture de endpoints publics (dont public_links qui est dans le scope actuel du projet)
