### ISSUE TITLE
Finaliser la documentation de l'API

### ISSUE THREAD

**Issue by damienlethiec** [betagouv/rdv-solidarites.fr#3013]
Plusieurs sujets à discuter ou vérifier:

- [x] Erreurs documentées sur tous les endpoints (401 et 429 notamment)
- [x] Documentation générique et non tech
- [x] Documentation des webhooks

> - [x] https://rdv-solidarites.gitbook.io/guides-pour-rdv-solidarites/tech/api-interconnexions-sortantes
> - [x] https://rdv-solidarites.github.io/rdvs-tech-doc/api-interconnexions-sortantes/

- [x] ~Adaptation de la doc si API V2 validée~
- [x] Schéma de réponse et d'erreur bien vérifié dans le test
- [x] Enlever les `run_test` inutiles quand la doc n'est pas générée et qu'on n'a pas de raison de vérifier le schéma
- [x] Ne plus utiliser le schéma `error_generic`, trop peu explicite.
- [x] Intégrer la [documentation sur l'authentification ](https://rdv-solidarites.gitbook.io/guides-pour-rdv-solidarites/tech/api-interconnexions-entrantes/authentification-and-permissions)
- [x] Intégrer d'[autres généralités](https://rdv-solidarites.gitbook.io/guides-pour-rdv-solidarites/tech/api-interconnexions-entrantes/details-techniques) le cas échéant
- [x] Route (ou tag) User : ajouter [les explications](https://rdv-solidarites.gitbook.io/guides-pour-rdv-solidarites/tech/api-interconnexions-entrantes/api-usagers)
- [x] Voir s'il y a d'autres éléments à intégrer depuis l'ancienne documentation

> https://github.com/rdv-solidarites/rdvs-tech-doc
> https://rdv-solidarites.github.io/rdvs-tech-doc/
> https://rdv-solidarites.gitbook.io/guides-pour-rdv-solidarites/tech/api-interconnexions-entrantes

**Comment by sebastiencarceles** [comment]
À la réflexion, il ne me semble pas pertinent d'ajouter la doc des webhooks dans cette documentation de l'API générée par swagger. C'est vraiment pas fait pour ça, ça va nous obliger à écrire beaucoup de choses à la main et c'est potentiellement difficile à maintenir.

Je propose plutôt l'organisation suivante : on crée le sous domaine https://doc.rdv-solidarites.fr. Il dirige vers [le gitbook](https://rdv-solidarites.gitbook.io/guides-pour-rdv-solidarites/), c'est à dire vers toute la documentation de la plateforme.

Dans cette doc, au niveau de l'entrée "API de requête", on redirige vers la documentation au format swagger.

![image](https://user-images.githubusercontent.com/1193334/201871149-ab9626f1-01f8-4765-acab-d8be5c7fc33f.png)

Il me semble que ce serait la meilleure façon d'organiser la documentation. Elle serait ainsi toujours maintenue sur gitbook, toujours à jour grâce à swagger en ce qui concerne l'API, et facile d'accès grâce au sous domaine.

**Comment by sebastiencarceles** [comment]
Dans #3080 , @yaf demande :

> J'aimerais bien voir comment nous allons pouvoir inclure la doc pour les webhook là-dedans thinking . Je vois qu'il y a les formats en bas, peut-être que nous pouvons ajouter un fichier markdown ou bien modifier l'existant. Nous pourrons faire des essais plus tard (si tu as un avis, une piste, ça m'intéresse).

Je n'ai pas trouvé le moyen de mettre un markdown supplémentaire.

Du coup, la première option que j'ai envisagée, c'est de documenter les webhooks directement dans `description_api.md` (c'est la doc qui apparaît _avant_ les endpoints). Cependant, je trouve que ce n'est pas vraiment sa place. On parle ici d'une doc ultra normée, et relativement automatisée. J'ai l'impression que les webhooks s'inscrivent dans ce cadre.

La deuxième option que j'ai envisagé est celle que j'ai décris ci-dessus : 
- faire un sous-domaine tech.rdv-solidarites.fr et le faire pointer sur le gitbook
- dans le gitbook, avoir la doc transverse, la doc sur les webhooks et un lien vers la doc de l'API 

Qu'en penses-tu ?

**Comment by yaf** [comment]
La doc Gitbook est obsolète. Nous avons migré la doc « orienté utilisateur / métiers » sur notion, et l'idée, c'était de faire une doc technique à part, regroupant la doc de l'api, des webhooks et des infos sur des mécanismes techniques de l'application (connecteur SMS disponible par exemple). Voir mettre en place un blog tech...

Alors peut-être que l'on peut « utiliser » l'organisation github « RDV Solidarités » pour fabriquer un site statique. Faire une redirection vers la doc de l'API ou bien générer la doc de l'API là-bas directement (ou la dupliquer ...). 

Ça revient un peu à ce que tu évoques il me semble.

Ce qui m'ennuie, ou plutôt ce qui me faisait penser que nous pourrions avec webhook et API ensemble, c'est que l'API utiliser les blueprints (documenté dans les formats en bas de la doc) et que les webhooks aussi... Il ne manque donc pas grand-chose à mon avis. Est-ce qu'il serait envisageable de « dupliquer automatiquement » la partie format pour faire une page spécifique sur les Webhook ?

Bref. Mon avis, c'est que c'est très chouette ce qui est là ; que je suis ok avec toi (sauf pour gitbook, mais c'est simplement une histoire d'outil); mais qu'il manque le plus important pour les départements du médico-social : la doc des webhook.

**Comment by sebastiencarceles** [comment]
> La doc Gitbook est obsolète. Nous avons migré la doc « orienté utilisateur / métiers » sur notion, et l'idée, c'était de faire une doc technique à part, regroupant la doc de l'api, des webhooks et des infos sur des mécanismes techniques de l'application (connecteur SMS disponible par exemple). Voir mettre en place un blog tech...

Merci pour les détails, je n'avais pas compris que le gitbook était obsolète, même si tu me l'avais peut être déjà dit, désolé :thinking: 

> Alors peut-être que l'on peut « utiliser » l'organisation github « RDV Solidarités » pour fabriquer un site statique. Faire une redirection vers la doc de l'API ou bien générer la doc de l'API là-bas directement (ou la dupliquer ...).

Absolument, on peut tout à fait utiliser GitHub Pages par exemple : https://pages.github.com

Il faudrait quand même créer un repo. Ce sera automatiquement servi par GitHub Pages. Avec Jekyll on doit pouvoir faire des jolies choses.

Je ne pense pas qu'on puisse générer ou servir la doc de l'API directement depuis ce nouveau repo en revanche. Il faut le projet rails pour cela.

> Ce qui m'ennuie, ou plutôt ce qui me faisait penser que nous pourrions avec webhook et API ensemble, c'est que l'API utiliser les blueprints (documenté dans les formats en bas de la doc) et que les webhooks aussi... Il ne manque donc pas grand-chose à mon avis. Est-ce qu'il serait envisageable de « dupliquer automatiquement » la partie format pour faire une page spécifique sur les Webhook ?

Étant donné que les webhooks utilisent la même sérialisation que l'API, grâce aux blueprints, je comprends mieux la pertinence d'avoir les deux docs ensemble, ou du moins très proches.

La proposition que j'aurais envie de faire est la suivante : 
- on crée un repo de documentation technique servi grâce à GitHub Pages
- on fait pointer le sous domaine tech.rdv-solidarites.fr dessus
- on fait une page sur la doc de l'API, avec un lien vers www.rdv-solidarites.fr/api-docs
- on fait une page (ou un ensemble de pages) sur les webhooks, et pour les schémas on renvoie vers www.rdv-solidarites.fr/api-docs
- on fait une page (ou un ensemble de pages) par sujet technique, comme les connecteurs SMS

Qu'en penses-tu ?

**Comment by yaf** [comment]
Il y a déjà une page avec le projet associé https://github.com/rdv-solidarites/rdv-solidarites.github.io. Nous avions essayé une forme de communication qui n'a pas vraiment fonctionné. Je peux récupérer les fichiers markdown historique et le reste peut être repris à 0.

Ta proposition me semble intéressante. Et peut-être que le wiki est la meilleure solution, surtout si c'est un point d'accueil qui pointe vers d'autres URL ensuite.  Les deux options me vont, c'est à discuter avec toute l'équipe.

Le wiki aurait l'avantage d'être plus « proche » du code.

Est-ce que l'on peut faire pointer un sous domaine sur le wiki ? :thinking:  (C'est peut-être le point technique qui nous fera décider :))

Je n'ai pas trouvé d'ancre qui permette de pointer sur un schéma en particulier. :-/ Tu sais s'il y a moyen d'avoir ce genre de chose ?

**Comment by sebastiencarceles** [comment]
On a discuté de ce sujet hier en réunion technique avec l'équipe. Plusieurs choses intéressantes sont à retenir : 

# Emplacement de la doc technique

Que ce soit dans le wiki, sur un gitbook, sur un repo dédié ou ailleurs, il est difficile de maintenir cette documentation technique à jour. La "distance" avec le code joue pour beaucoup. Par ailleurs le wiki souffre de défauts d'organisation (impossible d'avoir une arborescence, par exemple).

Il semble préférable d'avoir cette documentation _au sein_ du projet, comme c'est d'ailleurs déjà partiellement le cas. L'équipe estime qu'il sera plus facile de maintenir la documentation si elle est au plus proche du code. Elle permet en outre d'avoir un commit unique, qui contienne à la fois la modification du code et la modification de la documentation associée.

# Découvrabilité

Pour accéder à cette documentation technique, il est nécessaire d'ajouter un lien dans le readme. On a déjà un certain nombre de liens qui concernent de la doc technique dans le readme. L'emplacement est donc tout désigné, en prenant garde de rester cohérent et bien organisé.

# Sous-domaine

De même qu'on a doc.rdv-solidarites.fr, qui mène vers le notion qui contient la doc utilisateur·rice, l'équipe pense qu'il est pertinent d'avoir tech.rdv-solidarites.fr, qui mène vers la documentation technique.

Considérant ce qui est dit ci-dessus, cela signifie que ce sous-domaine mène en fait vers le readme du repo, et plus précisément vers : https://github.com/betagouv/rdv-solidarites.fr#documentation

**Comment by sebastiencarceles** [comment]
> Je n'ai pas trouvé d'ancre qui permette de pointer sur un schéma en particulier. :-/ Tu sais s'il y a moyen d'avoir ce genre de chose ?

Malheureusement non, je n'ai pas trouvé :( On n'a pas beaucoup la main, mais je vais explorer plus avant pour voir s'il y a [quelque chose à faire avec rswag-ui](https://github.com/rswag/rswag#customizing-the-swagger-ui).

**Comment by yaf** [comment]
Il sera sans doute intéressant de proposer un lien depuis le « site » RDV-Solidarités aussi.
