### ISSUE TITLE
Déployer une instance de RDV-S sur un nouveau domaine pour les besoins d'Aides Jeunes

### ISSUE THREAD

**Issue by damienlethiec** [betagouv/rdv-solidarites.fr#3043]
> ça serait cool d'avoir une instance du code de RDV-S, qui tourne sur un nouveau domaine par exemple rdv.incubateur.net ou/et (demo.rdv rdv-demo, etc.).incubateur.net et sur une application Scalingo dédiée

Parce que :

- il faut plus de personnes qui puissent savoir comment la partie de la généralisation (nouveau domaine, nouveau nom) fonctionne
- c'est compliqué de parler de généralisation avec des domaines si chargés (même si c'est moins le cas avec aide-numérique).
- on (je) voudrait pouvoir construire un discours rassurant sur la réutilisabilité de la base de code (potentiellement uniquement), et faire ça c'est du eat your own dog food.
- je voudrais tester une offre de service vraiment simple sur la prise de RDV (à la calendly ? ). Avoir un espace de moindre contact avec RDV-S et RDV-AN me parait être un outil en plus dans notre sac.

Notes : 
- on ne forke pas
- on a une DB par domaine

Changement du 26/10/2022 : on forke

Plus d'info ici : https://pad.incubateur.net/9GaayOyYTuKPu9XTQKIKxw

**Comment by damienlethiec** [comment]
Il me semble que je ne peux pas créer une instance moi même (message "manque un moyen de paiement").

Aussi, il y a de la config dans le code qui dépend des domaines utilisés. J'aimerais savoir quelle est la meilleur méthode selon vous pour cette nouvelle instance:
- Basculer ces configs en DB pour les rendre modifiables par des non techs notamment?
- Mettre en place une config minimal par défaut qu'on peut overrider par domaine ?
- Rajouter tout simplement une 3ème config avec des conditions de plus ?
- Une autre idée ?

Je suis preneur des avis ;)

**Comment by victormours** [comment]
Pour rendre l'appli disponible sous un nouveau domaine, il faut faire une branche de code avec les modifs suivantes : 
- une nouvelle valeur pour `Domain::ALL`, en fonction de ce que vous voulez utiliser comme domaine
- ajouter un template pour la recherche et la homepage (voir `app/views/search/_banner.html.slim` et `app/views/search/_address_selection.html.slim`)
- mettre à jour la ligne 13 de `app/views/static_pages/cgu.html.slim`

**Comment by damienlethiec** [comment]
Oui, c'était bien repéré. Mais ça ne répond pas vraiment à mon interrogation initiale je crois (désolé ;) ).

En gros, tu me proposes mon option 3 ici: pour rajouter un domaine, vous rajoutez une config. Je me demandais si c'était la meilleure option pour un 3ème domaine différent. Est-ce que ça ne commence pas à perdre de la lisibilité. Si oui, je voulais votre avis sur les options 1 et 2.

Mais si l'option 3 est la mieux pourquoi pas. C'est une prise d'avis

**Comment by yaf** [comment]
Je crois que l'instance et le nom de domaine sont différents.

Et je crois que l'option 3 est la plus simple pour le moment. Ensuite, nous apprendrons sans doute de nouvelle chose avec cette expérimentation supplémentaire. Ça nous amènera certainement à faire des évolutions !

(J'ajoute ici option supplémentaire : une configuration qui pourrait être dans les variables d'environnement, en imaginant qu'il y ait une instance par nom de domaine, et je pense que pour l'instant, c'est mieux d'y aller doucement, en petit pas).

**Comment by francois-ferrandis** [comment]
Mon petit avis : le problème principal étant de déterminer quelles sont les logiques qui dépendent du domaine, le plus pragmatique pour déclarer un nouveau domaine est de le faire directement dans le fichier `domain.rb` car c'est simple et explicite. Une fois ce travail fait, vous aurez probablement une bien meilleure perspective sur les enjeux de configurabilité des domaines. :wink:

**Comment by damienlethiec** [comment]
Ca me va pour commencer ;)

**Comment by yaf** [comment]
Je me permets de poser un avis par ici, mais ça rejoint sans doute une discussion plus large à avoir : le domaine est à placer sur le « territory » plutôt que sur l'organisation d'après moi.
