### ISSUE TITLE
Augmenter la visibilité des compteurs de RDV

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#3055]
Référence ticket : https://zammad10.ethibox.fr/#ticket/zoom/3293 

## Actuellement
Actuellement, la fiche usager est constituée de 2 parties : une partie information usager (partie gauche) et une partie information RDV (partie droite). 

La partie information usager est visible par tous les agents d'une même organisation (voire partagée par plusieurs organisations). 

Pour la partie RDVs, dans notre cas de figure, l'usager n'a que des RDV en PMI. 
Les personnes du secrétariat + les admins peuvent accéder à l'intégralité des infos de la fiche usager. 
Les agents de services sociaux (ou autre service que PMI) ne voient aucun RDVs. 

Problème rencontré : l'assistante sociale qui souhaite vérifier si un enfant à des RDVs PMI ne verra aucun RDV. Alors que l'enfant aura bien des RDVs de pris. 

## Objectif

Nous souhaiterions : 
- rendre visible le nombre de RDV dans le compteur existant 
- ajouter des compteurs de nombre de RDV selon le service

Rendre cette fonctionnalité optionnelle depuis le module de configuration.

**Comment by yaf** [comment]
Fermer par le biais de #3142

Il reste sans doute pas mal de chose à revoir sur les droits d'accès, mais il existe plusieurs tickets déjà existant à ce propos.
