### ISSUE TITLE
Synchronisation RDV Solidarités / Outlook

### ISSUE THREAD

**Issue by damienlethiec** [betagouv/rdv-solidarites.fr#3064]
## Actuellement

La synchronisation outlook est possible via un flux ical mais les pings du service sont trop espacés pour qu'elle soit vraiment utilisable.

## Objectif

Synchroniser Outlook pour les RDV via Oauth + API. Envoyer les RDV par API à Outlook au moment de la création, de l'update et de la suppression

**Comment by yaf** [comment]
Les départements suivants utilisent les webhooks pour synchroniser avec les agendas (voir plus) :
- Le 92 synchronise RDV-S avec le CRM Dynamics ;
- le 26 a un outil pour synchroniser uniquement les RDV avec leur outil Zimbra
- le 62 a développé un connecteur en C# (?) pour la synchro avec les agendas en Microsoft
- le 64 a développé un connecteur en PHP pour synchroniser avec les agendas Microsoft

Il y a sans doute moyen de leur demander le code source ?

_Nous pourrions documenter ça dans le notion_ :thinking:

**Comment by damienlethiec** [comment]
@victormours @yaf Je serai chaud pour un point pour être sûr d'aller dans la bonne direction alors. Aujourd'hui voilà où j'en suis et où je pensais aller:

- [X] Mise en place d'un Oauth microsoft pour connecter son compte Outlook à RDV Solidarités
- [X] Mise en place d'un système de refresh de token pour s'assurer qu'un call à l'API Microsoft peut être fait
- [X] Création d'un concern permettant la communication avec l'API Microsoft pour réaliser les actions nécessaires
- [ ] Création d'un calendrier Outlook dédié à la connexion avec RDV Solidarités lors du Oauth (en cours)
- [ ] Création d'un événement Outlook lors de la création d'un RDV
- [ ] Update d'un événement Outlook lors de l'update d'un RDV
- [ ] Suppression d'un événément Outlook lors du delete d'un RDV

Le code sera très isolé car quasi exclusivement dans un Concern appelé par quelques jobs

**Comment by yaf** [comment]
Je suis en train de penser que ça concerne les personnes qui utilise un logiciel Outlook sur leur machine Windows ?
J'ai en tête l'utilisation d'un serveur exchange par les DSI départemental... Ce n'est pas pareil et donc ça ne concerne pas vraiment le medsoc ? Ou je n'ai pas bien compris ?

Bref, je suis partant pour un échange histoire de clarifier :)

**Comment by damienlethiec** [comment]
On fait un point jeudi @yaf @victormours ? Soit avant 11h soit après 15h30 pour moi

**Comment by damienlethiec** [comment]
Quelques microdonnées en plus en vrac:
- Rajouter une config dans la page de config des territoires pour savoir si un territoire donné peut accéder à cette fonctionnalité
- Mettre en place une page avec un collapsible qui décrit les 3 méthodes de synchro
- Permettre de se déconnecter de la synchro Outlook
- Explorer le sujet d'un module séparé à terme ?
- Mettre les mêmes infos que dans ICS en temps 1
- Feature flag basique pour déploiement

**Comment by victormours** [comment]
On va mettre en ligne ce ticket en trois étapes :

### Changement de l'affichage de la page Synchronisation d'agenda

Dans un premier temps, il n'y a pas de changement de fonctionnalités, mais juste sur l'affichage de la page de synchro d'agenda.
Avant, cette page était directement la configuration de la synchro par lien Webcal. Après, ça devient une page d'explication des différent modes de synchronisation, qui pour le moment ne propose que la synchro par mail et la synchro webcal

Avant : 
![Capture d’écran 2023-01-02 à 14 01 21](https://user-images.githubusercontent.com/1840367/210246180-13b6d6e3-93b6-4ca0-9367-82aad932e22e.png)

Après : 

![Capture d’écran 2023-01-02 à 14 01 02](https://user-images.githubusercontent.com/1840367/210246195-f01cbf17-7483-4f79-98ea-5a36ceadcfbc.png)

### Ouverture sur RDV Aide Numérique

### Ouverture sur RDV Solidarités

**Comment by victormours** [comment]
Après discussion avec Myriam et Nesserine, voici une interface légèrement différente qui rend la navigation plus cohérente :

Sans outlook :
<img width="1092" alt="Capture d’écran 2023-01-03 à 15 43 16" src="https://user-images.githubusercontent.com/1840367/210381409-0280b3eb-8249-4c59-a675-a9e41b393b12.png">

Avec outlook :
<img width="1071" alt="Capture d’écran 2023-01-03 à 15 43 27" src="https://user-images.githubusercontent.com/1840367/210381402-23373ca7-7855-4b6d-822f-c1687895eb99.png">

Les liens qui mènent vers des pages qui ne sont pas accessibles depuis le menu de gauche sont maintenant à un niveau différent de celui qui mène aux Préférences de notifications.
Le texte a aussi été légèrement remanié pour être plus concis.
