### ISSUE TITLE
Bug: milliers de notifs de rappel non envoyées si l'une plante

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3065]
# Historique du bug

Hier, le lundi 14 novembre 2022, nous avons eu des remontées au support indiquant qu'une majorité des e-mails et SMS de rappel des RDV du lendemain (mardi 15 novembre) n'étaient pas partis. Ces notifications aurait dû être envoyées dimanche matin à 9H dans le job `CronJob::ReminderJob`.

Ce job a le code suivant : 

```ruby
def perform
  Rdv.not_cancelled.day_after_tomorrow.each do |rdv|
    Notifiers::RdvUpcomingReminder.perform_with(rdv, nil)
  end
end
```

Cela signifie que si le code du `RdvUpcomingReminder` plante pour un RDV, l'exécution s'interrompt, et les RDVs suivants ne sont pas traités ! Et nous avons justement eu [une remontée Sentry indiquant un crash à cet endroit](https://sentry.io/organizations/rdv-solidarites/issues/3737392029) (passée inaperçue dans le flot des autre remontées Sentry).

## Actuellement

* Comportement actuel : la boucle crash si une itération crashe

## Objectif

* Comportement attendu : si une itération crashe, les appels suivants sont quand-même faits
* Options envisagées, le cas échéant : chaque itération est faite dans un job séparé

## Technique

Je vois deux solutions possibles : 
- ajouter un `rescue` dans la boucle, et logger vers Sentry manuellement dedans
- introduire un job qui prend en argument un RDV et appelle `Notifiers::RdvUpcomingReminder` ; en cas d'exception prévenir Sentry et ne pas retry

**Comment by yaf** [comment]
En termes de lisibilité, c'est peut-être plus simple que de tout éparpiller :-/ Je suis du côté de ton cœur du coup :smile:
