### ISSUE TITLE
Export CSV des RDV : `552 Mail size too large. Maximum mail size limit is 14MB`

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3069]
Issue Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3677544045

## Actuellement

* Comportement actuel : sur certains exports, le fichier CSV généré dépasse les 14 Mo (ex: `Agents::ExportMailer#rdv_export`, agent 12765 et organisation 106)
* Étapes pour reproduire cette situation : difficile à reproduire car l'erreur nous est donnée par Sendinblue, il me semble bien

## Objectif

* Comportement attendu : zipper le fichier CSV à la volée, ce qui devrait diviser sa taille par 10
* Options envisagées, le cas échéant : faire apparaître une erreur si l'on demande un export de plus de X lignes de `Rdv` / `RdvsUser`

**Comment by yaf** [comment]
Le nombre de lignes est intéressant.

Je pense qu'il est possible de mettre en place une période limitée. Sans doute à discuter avec les référentes... Mais a minima un an me semble complètement ok. Pour l'export ET pour la liste à l'écran. Elle est paginée, mais à quoi bon lister l'ensemble des RDV depuis le début par défaut...

**Comment by francois-ferrandis** [comment]
En effet, côté données personnelles, la limite de 1 an semble pertinente ! Si t'es chaud pour un PR n'hésites pas. :slightly_smiling_face: 

J'aimerais aussi jeter un rapide cup d'œil au ZIP, car nos CSV ont beaucoup de répétition, et donc la compression est très efficace.

**Comment by yaf** [comment]
Bien sûr, c'est une bonne idée. Pour la limite, nous allons vérifier avec les référentes sur quoi se baser. Merci !
