### ISSUE TITLE
Bug : Des SMS de rappels sont envoyé lors d'annulation d'un RDV

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#3144]
Une utilisatrice a annulé le matin un atelier qui se déroulait l’âpres-midi même (capture 1). Après avoir renseigné l’annulation du RDV sur RDV Aide numérique, des SMS de rappels ont été envoyés aux usagers (capture 2) 

<img width="598" alt="Capture d’écran 2022-12-02 à 15 11 21" src="https://user-images.githubusercontent.com/103633345/205312001-3125dd0f-c13c-4631-934b-0589b36da527.png">

<img width="606" alt="Capture d’écran 2022-12-02 à 15 11 30" src="https://user-images.githubusercontent.com/103633345/205312129-79aded84-bcd3-4b6a-97cb-5d985879a4c5.png">

**Comment by yaf** [comment]
Le problème, c'est que c'est une notification de rappel qui est partie au lieu d'une notification d'annulation.

**Comment by Holist** [comment]
En investiguant sur cette issue j'ai découvert un bug plus important (réglé) : https://github.com/betagouv/rdv-solidarites.fr/pull/3182
Je ne m'explique pas comment une notif de rappel a pu être envoyé lors d'une annulation donc à voir si ce problème se reproduit maintenant que le code a été revue et corrigé plus généralement dans la PR au dessus.
