### ISSUE TITLE
Ajouter les motifs spécifiques à la Meuse en production

### ISSUE THREAD

**Issue by guillett** [betagouv/rdv-solidarites.fr#320]
Motifs PMI :
- Atelier massage
- Bilan  avant équipe éducative
- Consultation 0-6 ans
- Consultation enfant confié
- Entrée classe passerelle
- Suite bilan école maternelle

Email du 24/12/2019 à 15:54, de Anne-Sophie P.

**Comment by guillett** [comment]
@beg sais-tu si cela est faisable en production ? Je n'ai pas trouvé comment faire ?
Y-a-t-il une limitation technique ? Merci !

**Comment by beg** [comment]
Tu peux y accéder dans l'admin, menu 'Libellé de motif'. 
C'est fait pour la Meuse.

**Comment by guillett** [comment]
Mais j'ai l'impression que tous les motifs sont listés quand les usagers veulent prendre des RDVs sur https://www.rdv-solidarites.fr

Il n'y a pas de filtres par département.

En cas de validation, on arrive sur une page avec le message suivant « Nous n'avons pas trouvé de créneau pour votre motif ».

N'est-ce pas problématique ?

**Comment by beg** [comment]
Yes c'est un bug qui est corrigé dans la prochaine Mep par @mmagn

**Comment by beg** [comment]
cf : https://trello.com/c/DVJ7fATV/303-usagersearch-les-motifs-et-les-services-sont-disponibles-depuis-la-home-page-des-13 

Remonté par Aude

**Comment by guillett** [comment]
Ça a été fait, je ferme.
