### ISSUE TITLE
Revoir la configuration SPF et DMARC

### ISSUE THREAD

**Issue by yaf** [betagouv/rdv-solidarites.fr#3219]
ref https://zammad10.ethibox.fr/#ticket/zoom/3806

## Actuellement

> Il semble qu’il y ait une erreur dans la configuration SPF et DMARC de votre domaine. Cela provoque, aujourd’hui, le rejet automatique des emails provenant des adresses de vos utilisateurs.
> 
> Pour le moment, les emails sont récupéré et distribué manuellement mais cette manipulation n’est pas garantie et nous ne pourrons pas l’assurer indéfiniment.
> 

## Objectif

Vérifier la configuration ;
Faire un point avec Send In Blue  ?

**Comment by Holist** [comment]
Je suis en train de vérifier la configuration.

**Comment by Holist** [comment]
La semaine dérniére nous avons enlever le spf sendinblue de la racine du domaine (rdv-solidarites.fr) avec Francois, le domaine utilisé étant mail.rdv-solidarites.fr. On ne peut pas avoir 2 enregistrements spf différents pour un seul domaine par contre on peut mettre plusieurs valeurs dans un enregistrement (à faire si finalement on a besoin du spf de sendinblue sur la racine aussi)
Le problème semble réglé.
