### ISSUE TITLE
Clarification des états des RDV Collectifs

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3232]
Cette issue est une proposition pour répondre aux problèmes vus dans #3231

Le changement dans l'interface serait principalement au niveau de la dropdown de changement d'état d'un RDV Collectif.
(à voir s'il faut reformuler l'issue pour la clarifier)

A discuter avec @Holist à son retour :
- Pour les rendez-vous collectifs, ne jamais autoriser les statuts "excused" et "noshow" sur le rdv.
- Il est possible qu'il soit utile de distinguer les rdv collectifs annulés au démarrage du rdv (soit parce que tout le monde a annulé, soit parce que personne ne s'est inscrit, soit parce que les participants inscrits ont fait un noshow, ou un mélange de ces raisons, ou pas assez de participants sont venus), de ceux annulés à l'avance par le service (parce qu'il y a un changement de plan). Dans ce cas, on pourrait imaginer un statut `revoked_at_starting_time`. Pour le moment, on peut se contenter de toujours utiliser le statut `revoked` pour les rendez-vous collectifs annulés, que ça soit à l'avance ou au démarrage du rdv. Il faudrait mettre à jour le texte d'explication du dropdown revoked pour les rdv collectifs
- On considère qu'un rendez-collectif `seen` a eu lieu, même si tous les participants ne sont pas forcément venus. Il faudra légèrement modifier le texte d'explication. On pourrait appeler cet état `Effectué` dans l'interface. On pourrait même imaginer de faire cette modif pour les rendez-vous individuels aussi, et toujours parlé de rendez-vous `Effectué`, et renommer `seen` en `done`. Il faudra sans doute communiquer sur ce changement de wording.
- Mettre à jour les textes d'explications des changements d'état des rdv collectifs pour qu'ils aient plus de sens.
- Avoir un endroit qui centralise la logique de changement d'état pour les rdv (un concern state machine ?), et qui fournit les textes d'explications (dans le style de `Agent::RdvPolicy#explain`) des dropdown de manière cohérente. Le bug qu'on corrige ici est dû à une incohérence entre les différentes implémentations de la state machine. Si c'est centralisé, on peut espérer éviter ce type de bug à l'avenir.
- La logique pour mettre à jour le statut du rdv en fonction des participations devient beaucoup plus simple : on le passe en `seen` si au moins une participation est `seen`, et en `revoked` si aucune participation n'est `seen` ou `unknown`. Peut-être que ça permet d'éviter le `after_touch` et de simplifier du code. Au final on répond à [cette question]( https://github.com/betagouv/rdv-solidarites.fr/pull/2898#issuecomment-1289222709) qui est à l'origine de cette fonctionnalité ainsi : 
  - le premier screenshot devrait être rendez-vous `Annulé` (revoked en base), et participation `Non excusée`
  - le deuxième devrait être rendez-vous `Effectué` (seen en base), et participation `Present`.

**Comment by Holist** [comment]
Ok pour la logique "ascendante" depuis les participations, cela semble effectivement plus simple et plus proche des règles métiers.

Concernant la logique "descendante" du status du rdv sur les participations : 
- Quand l'agent passe le rdv en `seen` toutes les participations `unknown` passent en `seen`. Cela évite de faire la manip pour chaque participant.
- Quand l'agent passe le rdv en `revoked` comment devraient alors réagir les status des participations ?
Au niveau métier, y a t'il un intérêt de savoir qui ne s'est pas présenté et qui est venu si le rdv collectif ne s'est pas fait par manque de participant ou annulé à la dernière minute par l'agent ? Cela signifierai que l'on pourrait avoir un rdv `revoked` avec des participations `seen` et `noshow` ?
Ou alors, le plus simple, quand l'agent passe le rdv en `revoked` on assume de passer toutes les participations qui ne sont pas `excused` en `revoked` ?
