### ISSUE TITLE
Les RDV supprimés apparaissent dans les "prochains rendez-vous" des fiches usagers

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#3284]
Ticket Zammad en lien : https://zammad10.ethibox.fr/#ticket/zoom/4126

## Actuellement

Un RDV supprimé (soft deleted) continue à apparaître dans la fiche de l'usager dans les rdv à venir tant qu'un autre rdv n'est pas créé. Il reste clicable et renvoi vers une page d'erreur (not found)

![Capture d’écran 2023-01-24 à 17 31 18](https://user-images.githubusercontent.com/28594222/214351513-ec1df6a4-e431-441b-9ae6-1d1949b08169.png)

## Objectif

Le RDV ne doit plus apparaître dans les RDV

## Tech

Voir pourquoi le scope par défaut ne s'applique pas.

**Comment by mekaidmekaid** [comment]
- [ ] vérifier que la requête qui pose problème n'est pas utilisée ailleurs dans le code
- [ ] vérifier que quand un RDV est supprimé, il n'est plus compté dans les stats
