### ISSUE TITLE
Mettre à jour le bouton InclusionConnect

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3296]
Le bouton InclusionConnect a changé de design, il faut le mettre à jour. La dernière version est ici :

https://betagouv.github.io/itou-theme/content-ic.html

Note : il ne suffit pas de remplacer le fichier SVG, il y a aussi du CSS à ajouter.

**Comment by yaf** [comment]
duplicate #3239
