### ISSUE TITLE
Crash de l'édition de RDV lorsque le motif a changé de type (téléphone -> sur place)

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3316]
Occurrences Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/19433/?environment=production&project=74

## Actuellement

* Comportement actuel : lorsqu'un RDV est créé pour un motif "Au téléphone" ou "À domicile", puis que le motif est modifié pour passer au type "Sur place", alors le formulaire d'édition du RDV crashe
* Étapes pour reproduire cette situation : 
  1. Créer un motif "Au téléphone"
  2. Créer un RDV avec ce motif
  3. Modifier le motif pour qu'il devienne "Sur place"
  4. Tenter de modifier le RDV

## Objectif

* Comportement attendu : bonne question ! Faut-il empêcher de modifier le type d'un motif qui a déjà des RDVs ? Sinon on va forcément se retrouver avec cette incohérence de données.

## Technique

Changement introduit dans #2568.

**Comment by yaf** [comment]
Ça me semble une bonne contrainte oui.

**Comment by yaf** [comment]
Il y a une option plus longue et plus de fond qui consisterait à extraire le `location_type` du motif pour l'associer au RDV. 

Nous avons parlé de ça avec les référentes (il doit y avoir quelques réf dans les CR de réunion référente que je peux chercher). Il y a beaucoup de doublon de motif dans une même orga parce qu'il y a la « consultation » au tel, puis celle sur place et celle à domicile...

Pour éviter ça, nous avons évoqué l'idée de préciser :
- les type de localisation accepté pour motif (choix multiple dans la config de motif)
- sur la plage d'ouverture pour chaque motif quel type de localisation ça concerne (choix multiple limité par la config du motif)
- sur le RDV le type de localisation (en fonction des limites du motif)

Mais c'est un chantier plus gros. Peut-être à voir dans un second temps (voir le ticket #2177)
