### ISSUE TITLE
Prise de rdv en ligne ouverte par défaut aux invitations

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3385]
# Problème

Actuellement pour RDV Insertion, quand on a besoin d'envoyer des invitations pour des rdv, il faut aussi ouvrir le motif de rdv au public. Cela a deux inconvénients :
- il arrive que des usagers prennent rdv pour un motif qui n'est pas pertinent pour eux, parce qu'ils prennent rendez-vous depuis la page d'accueil de rdv solidarités, ou un lien de prise de rdv pour leur département
- si un agent fait une erreur de configuration et ferme le motif à la réservation au public, les usagers ne peuvent plus prendre rendez-vous avec leur invitation

# Contexte

On fait l'hypothèse que la prise de rdv par invitation va progressivement être réintégrée à rdv services publics. C'est lié à notre coeur de métier, et ça pourrait être utile dans des contextes autres que celui de rdv insertion.

# Solution envisagée

### Toujours ouvrir la prise de rdv par invitation au public

Quand un usager prend un rendez-vous avec une invitation, plutôt que de montrer uniquement les motifs ouverts à la réservation au public, on affiche tous les motifs liés à la catégorie de motif de son invitation, indépendamment de si c'est ouvert en ligne ou non.
Autrement dit, le niveau d'ouverture par défaut des motifs passe de "uniquement les agents de l'organisation" à "agents de l'organisation et usagers avec une invitation".
(d'un point de vue technique, on s'attend à ce que ce changement soit quasi-exclusivement à faire dans le fichier `app/services/users/geo_search.rb`)

### Inconvénient

L'inconvénient de ce fonctionnement est que les champs du formulaire de motif liés à l'ouverture à la réservation en ligne doivent maintenante toujours s'afficher, puisqu'on voudra par exemple pouvoir configurer le délai minimum de prise de rdv pour les rdv pris via invitation, même s'ils ne sont pas ouverts au public.

On pense qu'à terme les invitations existeront explicitement dans RDV Services Publics, mais pour le moment ça ajouterait de la confusion pour les agents qui n'utilisent pas RDV Insertion qu'on se mette à parler d'invitation uniquement dans cette partie du formulaire des motifs et nulle part ailleurs dans l'application.

### Solution temporaire

Pour le moment, on peut afficher les champs de prise de rdv en ligne pour les rdv fermés au public uniquement si le département utilise des catégories de motifs. C'est une approximations raisonnable pour savoir s'ils utilisent les invitations de rdv insertion en attendant que ça soit ajouté.

**Comment by Holist** [comment]
close here : https://github.com/betagouv/rdv-solidarites.fr/pull/3568
