### ISSUE TITLE
Augmentation mémoire REDIS

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#3389]
**Description**
La quantité de données que l'on stocke dans redis est en train d'augmenter rapidement depuis plusieurs semaines, et on se retrouve à avoir des instances qui swappent, puis qui mettent longtemps à répondre, ce qui cause un failover vers une autre instance pendant lequel on est en read-only, ce qui lève des erreurs quand les serveurs web essayent de mettre à jour des sessions.

Pour résoudre le problème temporairement nous avons augmenté le plan Redis de Business 2g à Business 4g

**To Reproduce**
On a des logs à ce sujet le 16 mars à 10h43 dans Scalingo
https://pad.incubateur.net/jOv-hx8wRRKkF-QKbjHdpw

On peut aussi voir la taille des backups redis qui augmente.

**A faire**
Trouver pourquoi la taille des données augmente (expirations manquantes pour certaines clés ?), et voir comment on peut corriger ça

**Comment by Holist** [comment]
Retour de la part de Scalingo : 

"En attendant votre réponse, j'ai obtenu un retour de notre équipe en interne: Le changement de plan tout à l'heure a fait du bien à la base, on constate qu'elle "respire" mieux, cela se traduit par une consommation d'IOPS plus importante (cf. capture d'écran ci dessous). Le manque de mémoire limitait les performances de la base.
On constate à présent que votre base semble très sollicitée (ce qui conduit aux bascules que vous constatez) et contient un nombre très important de clefs: 3333558 ce qui a pour impact de ralentir Redis, notamment lors de l'utilisation de certaines commandes (set ou exists). On aurait tendance à vous recommander d'utiliser des hashes et de supprimer des clefs qui ne sont plus utilisées (ou positionner un TTL )."

**Comment by victormours** [comment]
il faut qu'on fasse un petit nettoyage manuel. Pour une première passe, je suis tenté qu'on essaye ça : 
```ruby
redis = Redis.new(url: Rails.configuration.x.redis_url)

cursor, session_keys = redis.scan(0, match: "session:*", count: 100)

while cursor != 0
  session_keys.each do |session_key|
    session = Marshal.load(redis.get(session_key))
    if session.keys == ["_csrf_token"]
      redis.delete(session_key)
    end
  end
  cursor, session_keys = redis.scan(0, match: "session:*", count: 100)
end
```
