### ISSUE TITLE
Améliorer les perfs de la recherche usager

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3403]
Pré-requis : lire la PR #2791 pour comprendre le système de recherche actuellement en place. TLDR : on a cessé d'utiliser des colonnes de termes en vrac pour passer à un système pondéré, aux résultats beaucoup plus pertinents mais moins performant.

Pour résumer : le système en place fait une recherche sur des colonnes de façon pondérée en utilisant la recherche full-text Postgres. Cette recherche doit être insensible aux accents, et pour ce faire elle exécute la fonction Postgres `unaccent` **à chaque recherche**. Ceci a pour conséquence d'empêcher l'usage d'index, ce qui est très peu performant. 

# Solution envisagée

Il faudrait donc idéalement ajouter un index sur `unaccent(last_name)` plutôt que d'indexer seulement `last_name`, **mais** c'est compliqué d'indexer un résultat de `unaccent` car il dépend d'un dictionnaire On trouve des explications et des solutions pas simples si on cherche "postgres unaccent index" sur un moteur de recherche.

Pour rester simple, je pense donc que l'on pourrait nous-même gérer la création d'une version sans accent, et introduire des colonnes :

- `users.unaccented_last_name`
- `users.unaccented_first_name`
- `users.unaccented_birth_name`

On peut les compute dans un callback de `User`, puis se baser sur eux pour la recherche.

Edit : encore mieux, on pourrait utiliser les Generated Columns pour éviter d'avoir des callbacks dans l'app.

https://blog.saeloun.com/2022/01/25/rails-7-postgres-support-for-generated-columns/
https://www.postgresql.org/docs/current/ddl-generated-columns.html

# La requête actuelle

Pour info, voici la requête SQL qui est faite actuellement :

```sql
SELECT 
  "users".* 
FROM 
  "users" 
  INNER JOIN (
    SELECT 
      "users"."id" AS pg_search_id, 
      (
        ts_rank(
          (
            setweight(
              to_tsvector(
                ?, 
                unaccent(
                  coalesce("users"."last_name" :: text, ?)
                )
              ), 
              ?
            ) || setweight(
              to_tsvector(
                ?, 
                unaccent(
                  coalesce("users"."first_name" :: text, ?)
                )
              ), 
              ?
            ) || setweight(
              to_tsvector(
                ?, 
                unaccent(
                  coalesce("users"."birth_name" :: text, ?)
                )
              ), 
              ?
            ) || setweight(
              to_tsvector(
                ?, 
                unaccent(
                  coalesce("users"."email" :: text, ?)
                )
              ), 
              ?
            ) || setweight(
              to_tsvector(
                ?, 
                unaccent(
                  coalesce(
                    "users"."phone_number_formatted" :: text, 
                    ?
                  )
                )
              ), 
              ?
            ) || setweight(
              to_tsvector(
                ?, 
                unaccent(
                  coalesce("users"."id" :: text, ?)
                )
              ), 
              ?
            )
          ), 
          (
            to_tsquery(
              ?, 
              ? || unaccent(?) || ? || ?
            )
          ), 
          ?
        )
      ) AS rank 
    FROM 
      "users" 
    WHERE 
      (
        (
          setweight(
            to_tsvector(
              ?, 
              unaccent(
                coalesce("users"."last_name" :: text, ?)
              )
            ), 
            ?
          ) || setweight(
            to_tsvector(
              ?, 
              unaccent(
                coalesce("users"."first_name" :: text, ?)
              )
            ), 
            ?
          ) || setweight(
            to_tsvector(
              ?, 
              unaccent(
                coalesce("users"."birth_name" :: text, ?)
              )
            ), 
            ?
          ) || setweight(
            to_tsvector(
              ?, 
              unaccent(
                coalesce("users"."email" :: text, ?)
              )
            ), 
            ?
          ) || setweight(
            to_tsvector(
              ?, 
              unaccent(
                coalesce(
                  "users"."phone_number_formatted" :: text, 
                  ?
                )
              )
            ), 
            ?
          ) || setweight(
            to_tsvector(
              ?, 
              unaccent(
                coalesce("users"."id" :: text, ?)
              )
            ), 
            ?
          )
        ) @@ (
          to_tsquery(
            ?, 
            ? || unaccent(?) || ? || ?
          )
        )
      )
  ) AS pg_search_7dfb4cf67742cb0660305e ON "users"."id" = pg_search_7dfb4cf67742cb0660305e.pg_search_id 
WHERE 
  "users"."deleted_at" IS ? 
  AND "users"."id" IN (
    SELECT 
      DISTINCT "user_profiles"."user_id" 
    FROM 
      "user_profiles" 
    WHERE 
      "user_profiles"."organisation_id" = ?
  ) 
  AND "users"."id" IS NOT ? 
ORDER BY 
  pg_search_7dfb4cf67742cb0660305e.rank DESC, 
  users.updated_at desc 
LIMIT 
  ?
```

**Comment by victormours** [comment]
ça serait bien de réfléchir à la recherche des usagers d'un point de vue produit pour voir s'il y a des simplifications qui nous épargneraient de la complexité technique. On passe le sujet en to discuss

**Comment by francois-ferrandis** [comment]
Je suis tombé sur un bon article sur le full-text search dans PG, ça peut nous aider à comprendre les mécanismes utilisés par la gem `pg_search` : 

https://xata.io/blog/postgres-full-text-search-engine

**Comment by francois-ferrandis** [comment]
Fixed in #3878 and #3879
