### ISSUE TITLE
Faire en sorte que toutes les entrées de cache aient un TTL

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3412]
## Actuellement

Comportement actuel : certaines entrés de cache sont stockées dans Redis sans TTL.

À ce que je vois ça concerne notamment les 2 appels qu'on fait à `render cached: [...]` [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/c85441a7b9311bcd40e00d6a178ae9e4d9f2d662/app/views/admin/receipts/_receipts.html.slim#L9) et [là](https://github.com/betagouv/rdv-solidarites.fr/blob/c85441a7b9311bcd40e00d6a178ae9e4d9f2d662/app/views/admin/users/index.html.slim#L40).

Il est possible qu'il y en ait d'autre, Victor a trouvé une petite stratégie pour les détecter : https://github.com/betagouv/rdv-solidarites.fr/compare/production...raise-error-for-redis-leaks--la-branche-de-francois

## Objectif

* Comportement attendu : toutes les entrées Redis ont un TTL

## Technique

L'objectif est d'éviter que la RAM et le disque de notre Redis n'augmentent sans fin de taille, ce qui peut nous causer de sérieux problèmes, voir #3389.

**Comment by victormours** [comment]
D'après l'augmentation de la taille des dump redis, il faut qu'on règle ça avant fin avril si on veut éviter d'avoir à nouveau des interruptions de service, donc je passe ce ticket en ready
