### ISSUE TITLE
Afficher les instructions avant prise de RDV au moment du choix du lieu pour qu'ils restent visibles

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-solidarites.fr#3424]
## Contexte

Aujourd'hui lorsque l'on crée un motif nous avons deux champs d'instructions que l'on peut remplir : 
* Les instructions à accepter avant la prise de rdv (colonne `restriction_for_rdv` en base)
* Indications affichées après la confirmation du rendez-vous (colonne `instruction_for_rdv` en base)
<img width="959" alt="image" src="https://user-images.githubusercontent.com/7602809/228900739-789d42cd-f746-47da-8ef6-d293e876a4fb.png">

### Avant le rdv

Les instructions à accepter avant la prise de rdv sont affichés dans les cas suivant: 

* Au moment de la sélection du motif
<img width="938" alt="image" src="https://user-images.githubusercontent.com/7602809/228900871-a373601d-4b8b-41af-9fd4-d68064a1402e.png">

* Sur la page du rdv après la prise du rdv

<img width="647" alt="image" src="https://user-images.githubusercontent.com/7602809/228900925-a7e5fea7-4884-47dc-b5fa-15fac37d85d9.png">

### Après le rdv 

Les indications affichées après la confirmation de rdv sont affichés dans les cas suivant: 

* Sur la page du rdv après la prise du rdv 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/7602809/228904485-f5145f97-5fe1-430c-bff5-40f5a53bc0ed.png">

* Dans le mail de confirmation du rdv

<img width="435" alt="image" src="https://user-images.githubusercontent.com/7602809/228904967-1de7a89e-a2a3-443b-91a6-da9e1f1ea052.png">

* Lors de l'étape de confirmation de prise de rdv par un prescripteur 

## Problème 

Lorsqu'une personne arrive depuis une invitation RDV-Insertion, il se peut qu'il arrive directement sur la page de sélection du lieu ou du créneau s'il n'y a pas un choix à faire entre plusieurs motifs. Du coup, il ne verra pas les instructions à accepter avant la prise de rdv.

## Solution 

Victor et Mehdi en backlog refinement : On va mettre "la popup d'instructions avant prise de rdv" **au moment du choix du lieu (ou du choix de l'organisation pour les rdv téléphonique)**. Ça permet de mettre le message le plus tôt possible (ce qui avait motivé le changement de https://github.com/betagouv/rdv-solidarites.fr/issues/1790), mais d'avoir quand même des messages spécifiques à chaque organisation.

Ça a aussi probablement l'avantage d'être plus facile à implémenter, puisqu'on a toujours une étape de choix de lieu, même s'il n'y a qu'un seul lieu disponible.

## Sur le plus long terme 

J'ai l'impression qu'on pourrait tout de même rendre plus clair ce que l'on affiche et quand on l'affiche. Voici quelques propositions pour y arriver dont on pourrait discuter: 

* On pourrait avoir des textes plus explicatifs lors de la création du motif
* Avoir des noms de colonnes en db plus descriptives (pour éviter la confusion aux développeurs)
* Peut-être ne garder qu'un seul des 2 champs, que l'on afficherait à la sélection du créneau, dans le mail de confirmation et dans la page récapitulative du rdv. Cette solution a ma préférence parce qu'elle a l'avantage de ne pas devoir écrire 2 fois le même message si on veut qu'il apparaisse à la prise de rdv et dans le mail de confirmation. Mais il y a peut-être des cas d'usage que je n'ai pas.

**Comment by victormours** [comment]
Vu avec Mehdi : les restrictions devraient peut-être plutôt être des descriptions, et on pourrait les afficher en dessous du motif pour faciliter le choix de motif, plutôt que dans une modale.

**Comment by mekaidmekaid** [comment]
Vu avec Vic : 

Après avoir parcouru les contenus des champs "avant" et "après" RDV des différents départements, on constate 3 grands usages : 

* un usage qui fait presque l'unanimité pour le champs "après" : indiquer les pièces / pré-requis du RDV
* deux usages pour le champs "avant" : 
** utilisé comme description du rdv : 

> Vous prenez rendez-vous dans un CSS (Centre de Santé Sexuelle). Ce service est gratuit.
> 
> L’autorisation des parents n’est pas nécessaire pour les mineurs.
> 
> En cas de demande complémentaire, n'hésitez pas à appeler le standard du CSS au 02 14 47 50 47

** utilisé comme restriction / warning : 

> Ce rendez-vous est réservé aux enfants de moins de 6 ans.
> Il est réalisé par l’infirmière puéricultrice.
> Pour toutes urgences ou en cas de maladie, merci de contacter votre médecin traitant ou d’appeler directement le 15.

Nous préconisons d'abord de préciser la fonction que nous voulons donner au champs "avant" soit description soit restriction et d'afficher le contenu de celui-ci directement au niveau du motif. 

Quand un usager arrive directement sur une étape autre que le motif, celui s'affiche quand même en haut. Nous voyons-là une opportunité pour afficher le contenu du champs "avant" à ce niveau là. 



![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/122271472/36a3cf49-9657-4891-a6ef-7fc1e179b5a3)

**Comment by mekaidmekaid** [comment]
@Teodora-Stanki chaud pour avoir ton avis

**Comment by victormours** [comment]
On va mettre la popup d'instructions avant prise de rdv au moment du choix du lieu (ou du choix de l'organisation pour les rdv téléphonique). Ça permet de mettre le message le plus tôt possible (ce qui avait motivé le changement de https://github.com/betagouv/rdv-solidarites.fr/issues/1790), mais d'avoir quand même des messages spécifiques à chaque organisation.

Ça a aussi probablement l'avantage d'être plus facile à implémenter, puisqu'on a toujours une étape de choix de lieu, même s'il n'y a qu'un seul lieu disponible

**Comment by aminedhobb** [comment]
Dans certains cas, l'usager est invité à prendre rdv sur un lieu précis, et ne voit donc que la page de sélection de créneaux.
Ces cas sont marginaux pour l'instant (il n'est possible d'inviter sur un lieu que via l'API RDV-I), mais il est pas impossible que ce soit plus étendu un jour.

**Comment by mekaidmekaid** [comment]
Merci beaucoup pour la précision Amine, nous envisagerons quand ces cas-là ne seront plus marginaux, cette piste décrite par Victor ici : https://github.com/betagouv/rdv-solidarites.fr/issues/3424#issuecomment-1550040511
