### ISSUE TITLE
Erreur lors du chargement d'un rdv pour un usager

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3427]
voir https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/d042f5b23f8348afaedf826427c0c873/?environment=production&project=74&query=is%3Aunresolved

Il semble qu'il y ai des liens morts dans l'appli qui font que des usagers ont une erreur 404 lorsqu'ils essayent d'accéder à certains rendez-vous.

volume : entre 5 et 10 fois par jour

**Comment by francois-ferrandis** [comment]
**J'investigue les dernière occurrences pour voir quels cas peuvent déclencher cette 404.**

## Cas d042f5b23f8348afaedf826427c0c873

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/d042f5b23f8348afaedf826427c0c873/events/?environment=production&project=74

-> Usager qui se connecte par FranceConnect, ce qui le connecte sur le compte d'un usager qui n'est pas l'usage du RDV.

## Cas 7a7136a2b0424fc09414b591932c9b70

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/7a7136a2b0424fc09414b591932c9b70/?environment=production&project=74

Usager qui se connecte avec son compte 666491 (email présent) mais c'est un profil doublon 517206 (email absent) qui est lié au RDV.

## Cas 53d97b99f0634b8399b079331b519e23

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/53d97b99f0634b8399b079331b519e23/?environment=production&project=74

Idem, que ci-dessus, usager en doublon.

## Cas 30afab3930da44c396bf4fc94b06936f

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/30afab3930da44c396bf4fc94b06936f/?environment=production&project=74

Sur ce cas, c'est la responsable du proche du RDV qui a un profil en doublon.

## Cas 81489e8249b946688508860545e07b99

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/81489e8249b946688508860545e07b99/?environment=production&project=74

Ici, le motif a comme visibilité `visibility_type: "invisible"`. Cette visibilité semble avoir été définie avant la création du RDV, donc il y a peut-être un bug qui fait qu'on envoie par mail un lien vers un RDV invisible.

## Cas 565c61a8a979472fae71d628efc70bff

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/565c61a8a979472fae71d628efc70bff/?environment=production&project=74

Le RDV a été soft deleted.

## Cas 1542dbea7b2241659893dd3c546e4ca9

https://sentry.incubateur.net/organizations/betagouv/issues/18543/events/1542dbea7b2241659893dd3c546e4ca9/?environment=production&project=74

Doublon de profil usager, ça semble être un cas fréquent.

**Comment by francois-ferrandis** [comment]
Pour résumer les différents cas : 
- la majorité des cas sont des soucis de doublon, j'ai donc ajouté le ticket à la milestone https://github.com/betagouv/rdv-solidarites.fr/milestone/36
- un cas intéressant est sorti, j'ai créé un ticket pour ce cas : https://github.com/betagouv/rdv-solidarites.fr/issues/3473

@mekaidmekaid Est-ce qu'on ferme cette issue ? À mes yeux, l'enjeu est de garder une explication adjointe à des occurrences Sentry, pour savoir pourquoi on ignore ces occurrences.

**Comment by francois-ferrandis** [comment]
Je ferme et je passe dans la colonne "Done", si tu veux faire autrement tu pourras toujours réouvrir @mekaidmekaid. :wink:
