### ISSUE TITLE
Bug France Connect (Omniauth failed : {:error=>:csrf_detected, :reason=>"Invalid 'state' parameter"})

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#3437]
Log sentry : https://sentry.incubateur.net/organizations/betagouv/issues/17938/?project=74

Problème lors de l'authentification omniauth France Connect.
On a des logs récurrents 10 à 20 jours.
A voir quel est l'impact (les usagers france connect ne peuvent pas du tout se connecter ?)

Peut-être faut-il [ajouter du log](https://stackoverflow.com/questions/10173833/devise-omniauth-failure-how-to-debug-it) pour mieux débugger ?

**Comment by francois-ferrandis** [comment]
Je ferme car doublon de #3330. :wink:
