### ISSUE TITLE
ETQA, quand je synchronise mon agenda avec Outlook, je souhaite y retrouver mes RDV passés de 30 jours ainsi que l'intégralité de ceux à venir

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#3446]
### Définition du problème

En testant la synchro Outlook, on s'est rendu compte qu'au moment de la synchro, les RDV futures n'apparaissent pas d'emblée sur l'agenda. Pour les faire apparaitre, il faut soit en créer, soit editer et republier un RDV existant. 

On souhaite, qu'une fois que l'agent ait établie la synchro de son agenda avec Outlook, il puisse voir tout de suite sur son agenda ses rdv passés d'un mois ainsi que l'intégralité de ses rdvs futurs.

**Comment by mekaidmekaid** [comment]
lien de recette : https://www.rdv-aide-numerique.fr/agents/calendar_sync/outlook_sync

**Comment by NesserineZarouri** [comment]
Le contexte du RDV n'apparait pas (aussi bien pour les RDV individuels que pour les ateliers collectifs) lors de la synchro, est-ce un choix ?
