### ISSUE TITLE
Bug: les champs "remarque" n'apparaissent pas dans l'agenda

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3451]
Demande Zammad : https://zammad10.ethibox.fr/#ticket/zoom/4907

D'après la demande ci-dessus, l'agenda affichait les remarques (colonne `users.notes`) mais plus maintenant.

Ce ticket consiste à trouver depuis quand ce changement est apparu, afin de soit le justifier auprès du demandeur, soit le remettre en question.

**Comment by victormours** [comment]
J'ai cherché, et il n'y a pas eu de changement là dessus. J'ai répondu au ticket zammad pour indiquer ça.
