### ISSUE TITLE
Une fiche usager est rattaché à un l'ancien agent référent avec une impossibilité de retirer cet agent

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#3475]
Ticket Zammad : https://zammad10.ethibox.fr/#ticket/zoom/4836
Persona concerné : l'ancien agent référent (agent A) + le nouveau agent référent (agent B) et l'usager (X). 

Situation : 
L'agent A était l'agent référent de l'usager X. L'usager X a changé de référent et s'est retrouvé avec l'agent B. Sur le compte de l'agent A, il n'y pas t-plus aucune trace de l'usager X (impossible de trouver le fiche usager ou les anciens RDV). 
En revanche, sur le compte de l'agent B, lorsqu'on recherche l'usager X et que l'on accède à sa fiche usager, il est indiqué que l'usager X est rattaché à deux agents : l'agent A et l'agent B. Ensuite, lorsqu'on souhaite modifier cette liste d'agent référent, l'agent A n'est pas présent. 

![Image](https://user-images.githubusercontent.com/103633345/234233529-ecc2b86c-9c4d-44a2-8327-06f6609c5d7f.png)

![Image](https://user-images.githubusercontent.com/103633345/234233568-77c03b70-8705-4dcc-80f8-dcd0b4e0434d.png)

Résultat attendu : 
Nous souhaiterions retirer l'agent A de la fiche de l'usager X

**Comment by francois-ferrandis** [comment]
J'ai creusé le souci et nous sommes dans une situation d'**incohérence des autorisations entre différentes actions**.

La condition d'affichage d'un agent sur la première page (l'affichage du profil usager) est la suivante : *l'agent doit faire partie du même territoire que l'orga courante* :
https://github.com/betagouv/rdv-solidarites.fr/blob/cf387c7ca58acc42b3cf699bd70d59dcb3af36c8/app/policies/agent/referent_assignation_policy.rb#L5

La condition d'affichage d'un agent sur la seconde page (édition des référents d'un usager) est : *l'agent doit faire partie de l'orga courante ET de mon service si je ne suis pas admin de l'orga* :
https://github.com/betagouv/rdv-solidarites.fr/blob/cf387c7ca58acc42b3cf699bd70d59dcb3af36c8/app/controllers/admin/referent_assignations_controller.rb#L8
https://github.com/betagouv/rdv-solidarites.fr/blob/cf387c7ca58acc42b3cf699bd70d59dcb3af36c8/app/policies/agent/agent_policy.rb#L46

Là où ça devient drôle, c'est qu'on a des conditions différentes sur les droits d'ajout et retrait d'un référent (ceux appliqués quand on clique sur "Ajouter" ou "Retirer" dans le second écran). En effet, pour autoriser à ajouter/retirer, on regarde si l'agent a le "droit de modifier" l'usager. *Ce droit se résume à savoir si l'usager est dans l'orga courante.*
https://github.com/betagouv/rdv-solidarites.fr/blob/cf387c7ca58acc42b3cf699bd70d59dcb3af36c8/app/controllers/admin/referent_assignations_controller.rb#L27
https://github.com/betagouv/rdv-solidarites.fr/blob/cf387c7ca58acc42b3cf699bd70d59dcb3af36c8/app/policies/agent/user_policy.rb#L26
