### ISSUE TITLE
En tant qu'usager, je ne peux pas prendre de RDV avec mon agent référent depuis mon espace

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#3476]
Ticket Zammad : https://zammad10.ethibox.fr/#ticket/zoom/5112

Le 26 entame l'ouverture en ligne pour les usagers de service social. Cette ouverture se fera progressivement et commencera par l'ouverture en ligne des RDV de suivi pour les usagers ayant un référent. 

Infos : le 26 compte ouvrir la réservation en ligne pour le service sociale pour septembre 

**L'espace agent** a été configuré convenablement : l'usager TEST est bien rattaché à un agent. L'agent à ouvert des motifs ouvert à la réservation en ligne (aux agents et aux usagers) + des plages d'ouvertures. 

**L'espace usager** : l'usager test retrouve bien son agent référent avec la possibilité de prendre RDV avec lui. Cependant, lorsque l'usager appuie sur le bouton "prendre un RDV", il est indiqué que l'agent n'a pas de créneaux de disponibilités. 

![Image](https://user-images.githubusercontent.com/103633345/234240009-ccd5d645-0287-4a3e-bca6-63e96fa62daf.png)

![Image](https://user-images.githubusercontent.com/103633345/234240019-70508e83-dcec-44a2-be07-2545eafadf24.png)

Résultat attendu : afficher les créneaux de disponibilités de l'agent côté usager

**Comment by ousmanedev** [comment]
# Investigation

Le fonctionnement de la prise de RDV auprès d'un référent ( bouton "Prendre un RDV" situé sous la section "Vos référents") est différent du fonctionnement de la prise de RDV générale (bouton "Prendre un RDV" situé sous la section "Vos rendez-vous").

## Description du problème

Lorsque l'usager tente de prendre RDV auprès d'un référent, la recherche de créneaux considère les paramètres suivants:
- Rechercher un RDV dans le territoire du référent
- Rechercher un RDV pour un service identique à celui de l'agent
- Rechercher un RDV de Suivi

Les résultats de la recherche de RDV auprès d'une référent doivent répondre à tous les trois critères précités.

Dans le cas présenté, aucun créneau n'est retrouvé après recherche de RDV auprès d'un référent, parce que:
- soit il n'existe pas de motif dans le département de l'agent
- soit les services des motifs créés ne correspondent pas au service de l'agent
- soit il n'existe pas de motif pour RDV de suivi

## Solution adoptée

Nous choisissons comme solution d'améliorer l'expérience utilisateur en renommant le bouton "Prendre un RDV" en dessous de la section "Vos référents", par "Prendre un RDV de Suivi" ; qui se veut un peu plus explicite de la fonctionnalité.

**Comment by mekaidmekaid** [comment]
@ousmanedev vu avec Téo. 

"Votre référent n'a pas de créneaux disponibles. Voulez-vous prendre rendez-vous avec un autre agent ? 

CTA positionné en bas "Prendre un RDV"

A ajuster avec Téo via screenshare sur ton local ou sur la review app via un lien de test 👍

**Comment by ousmanedev** [comment]
@mekaidmekaid 

La modification est faite et visible sur la review app: https://demo-rdv-solidarites-pr3496.osc-secnum-fr1.scalingo.io/users/rdvs

Je te laisse visualiser en pièce jointe, un screenshot du nouveau wording:

<img width="1404" alt="Screenshot 2023-05-11 at 15 12 19" src="https://github.com/betagouv/rdv-solidarites.fr/assets/11911945/5260a716-8104-4106-ad1c-2b86fcc65b7a">
