### ISSUE TITLE
Vérifier notre app auprès d'outlook

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#3479]
### Contexte 

Nous pensons que le fait que Microsoft affiche "App non vérfiée" dessert nos utilisateurs dans leur octroiement des droits pour se brancher à nous. 

L'objectif est de vérifier notre application auprès de Microsoft pour que nous puissions valider ou invalider cette hypothèse.

![Blur-image-online](https://user-images.githubusercontent.com/122271472/234604564-7b6bcb2f-9977-4148-9991-922a663386c1.png)

**Comment by victormours** [comment]
voir https://learn.microsoft.com/en-us/azure/active-directory/develop/publisher-verification-overview
