### ISSUE TITLE
La suppression d'un agent rend inaccessible l'index des rdv des usagers qui ont eu des rdv avec lui

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3481]
bug sur le soft delete d'un agent : on ne peut plus accéder à l'index des rdv des usagers qui ont eu des rdvs avec cet agent

voir https://sentry.incubateur.net/organizations/betagouv/issues/19389/activity/?environment=production&project=74&query=is%3Aunresolved

https://zammad10.ethibox.fr/#ticket/zoom/5225

Les usagers ne peuvent pas annuler leur rdv non plus.

**Comment by victormours** [comment]
Dans l'immédiat, il faudrait corriger les rdvs qui n'ont plus d'agents pour rendre l'application utilisable suite à la suppression d'un agent la semaine dernière

**Comment by francois-ferrandis** [comment]
De ce que j'ai vu, les crashes étaient causés par le [template de RDV](https://github.com/betagouv/rdv-solidarites.fr/blob/d86b0780c29e4eb12ad9ffd1ac3440813b5aae85/app/views/admin/rdvs/_rdv.html.slim#L22) qui propose un lien vers l'agenda de lagent. Ce template crashe lorsque l'agent a été supprimé via hard delete. La seule façon de hard delete un agent est de le faire depuis le super admin et dans les cas que j'ai vu c'est @NesserineZarouri qui avait supprimé ces agents alors qu'ils avaient des RDVs.

Il y a donc deux questions : 
- Est-ce que l'on doit afficher le lien `"voir dans l'agenda"` si l'agent a été soft deleted ? Actuellement on affiche ce lien, mais que voit-on si on clique dessus ?
- Est-ce qu'il faut empêcher le hard delete d'un agent depuis le super admin ? Seulement si iel a des RDVs ? Actuellement les absences, plages, rôles, etc sont [destroyed en cascade](https://github.com/betagouv/rdv-solidarites.fr/blob/d86b0780c29e4eb12ad9ffd1ac3440813b5aae85/app/models/agent.rb#L54).

**Comment by victormours** [comment]
Vu avec Mehdi : pour le moment on arrête d'afficher le lien `voir dans l'agenda` si l'agent n'existe plus, et on fera un autre ticket de follow up plus général pour la suppression d'agents

**Comment by francois-ferrandis** [comment]
> Vu avec Mehdi : pour le moment on arrête d'afficher le lien `voir dans l'agenda` si l'agent n'existe plus, et on fera un autre ticket de follow up plus général pour la suppression d'agents

OK, je fais la PR tout de suite. :zap:
