### ISSUE TITLE
Proposition de template

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#3482]
## ℹ️ Contexte 

* Ticket Zammad :
* Issue Sentry :
* Comportement actuel : 
  * Étapes pour reproduire cette situation
  * Captures d'écran si pertinent
  * Environnement (version du navigateur / du téléphone…)

## ❓ Définition du problème

* Ce que nous pensons qu'est le problème

## 💡 Solution envisagée

* Comportement attendu
* Options envisagées, le cas échéant
* Technique
* Pistes d’investigation ou d’implémentation

## 🧪 Scénarios de test

* Étapes pour aboutir sur le comportement attendu
* Lien de la review app pour tester :

**Comment by francois-ferrandis** [comment]
Cette proposition a été intégrée dans la branche principale. :wink: :tada:
