### ISSUE TITLE
Lancer une nouvelle vague d'invitations Conseiller numérique 

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#3487]
* Ticket Zammad : Ticket#515262

Cet agent Conseiller numérique ne parvient pas à se connecter RDV Aide Numérique car il n'a pas de compte.  Pouvez-vous envoyer des invitations aux nouveaux agents labellisées Conseillers numériques  ? 

Merci 🙏

**Comment by victormours** [comment]
c'est fait, et j'ai répondu au cnfs dans le ticket zammad (et fermé le ticket)
