### ISSUE TITLE
Récolter le numéro de pré-demande ANTS lors de la prise de rdv et l'afficher à l'agent de mairie

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3523]
## ℹ️ Contexte 
Review app: https://demo.rdv-mairie.fr/

En tant qu'agent de mairie, je veux avoir accès au numéro de pré-demande ANTS pour accélérer le rendez-vous pour un passeport et/ou une carte d'identité.
Cette info sera aussi utile pour se brancher au système de dédoublonnage de l'ANTS.

On veut ajouter un champs pour ce numéro de pré-demande pour les trois cas différents :
- prise de rdv par l'usager
- prise de rdv par l'agent
- prise de rdv par prescripteur

Il faut l'afficher dans la page de détail des rdv pour que l'agent puisse vérifier avant le rdv s'il manque des pièces au dossier.

Précision confirmée par notre contact technique ANTS : dans le cadre d'un rdv pour 2 personnes, il y a 2 numéros de dossier

Le numéro de dossier est 10 caractères alphanumériques

### Evolutions envisagées sur la page "Vos informations" côté usager :

- ajouter le champs "Numéro de pré-demande" (à la place de date de naissance), avec un texte d'explication sur ce champs
- supprimer les champs nom de naissance, date de naissance, adresse et complément d'adresse
- rappeler l'adresse mail pour être sûr qu'on n'envoie pas de notifs dans des adresses "poubelles" (voir si on applique ça à tous les domaines, et pas juste pour RDV Mairie ?)
- Enregistrer le numéro de pré-demande sur la table users plutôt que rdv_users pour simplifier les changements de rendez-vous, et l'implémentation

### Côté agent

- sur la page de détail des rendez-vous : mettre le numéro de pré-demande dans la liste des participants, en deuxième colonne après le nom de l'usager
- Lors de la prise de rendez-vous : faire les mêmes changements que côté usager

**Comment by victormours** [comment]
Evolutions envisagées sur la page "Vos informations" côté usager :
- ajouter le champs "Numéro de pré-demande" (à la place de date de naissance)
- supprimer les champs nom de naissance, date de naissance, adresse et complément d'adresse
- rappeler l'adresse mail pour être sûr qu'on n'envoie pas de notifs dans des adresses "poubelles"

**Comment by victormours** [comment]
Côté agent, mettre le numéro de pré-demande dans la liste des participants, en deuxième colonne après le nom de l'usager

**Comment by mekaidmekaid** [comment]
Reçu de la part @Teodora-Stanki feedback agent, préférable d'ajouter la commune

**Comment by mekaidmekaid** [comment]
@ousmanedev on it 👍

**Comment by mekaidmekaid** [comment]
**Mes retours @ousmanedev ** 

Pour le parcours agent : 

*  Mettre en place un controle pour les 10 caractères alphanumériques du N° de dossier
* Je me dis qu'il serait opportun est plus logique de remettre le numéro à cet endroit là de la page aussi

![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/122271472/2050e210-2f1e-4cc5-ba6d-416e660b7474)

Pour le parcours usager : 

* Faire pointer le CTA `Prendre RDV` vers le moteur de recherche de l'ANTS

Le reste difficilement testable en l'état, j'attend ton coup de maguette magique comme discuté ensemble, sinon ok pour moi de tester en prod et de réagir dans la foulée

**Comment by victormours** [comment]
Pour ce qui est du champs commune, il faut prendre en compte les autres stakeholders, et la politique de l'ANTS est celle de la déterritorialisation : tous les citoyens peuvent faire leur demande dans toutes les communes, et il ne doit pas y avoir de "favoritisme" pour les résidents de la commune.
On doit appliquer cette politique, et donc on ne va pas demander l'adresse de l'usager (et comme ça on a moins de friction)
