### ISSUE TITLE
Le mail de confirmation de compte ne part pas du bon domaine / bonne adresse ?

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#3578]
Je n'ai pas eu le temps de tester le comportement donc ça demande confirmation, mais voici ce que je viens de constater nous avons 2 % de nos e-mails qui utilisent le mailer `ActionMailer::MailDeliveryJob`  plutôt que notre `CustomDeviseMailer`.

![image](https://github.com/betagouv/rdv-solidarites.fr/assets/6357692/41a62752-a1ba-46b1-af28-203224ee367b)

![image](https://github.com/betagouv/rdv-solidarites.fr/assets/6357692/1fd5d906-9e2d-42ce-9dd2-ca671c91c52d)

Or, c'est dans le `CustomDeviseMailer` que nous gérons certaines choses, dont la résolution du bon domaine à utiliser.

Il faut donc trouver pourquoi c'est le `ActionMailer::MailDeliveryJob` qui est utilisé et faire en sorte que ce soit toujours `CustomDeviseMailer` qui soit utilisé.

**Comment by victormours** [comment]
C'est bon, c'est juste une fausse alerte : il y a eu une confusion entre le __job__ et le __mailer__ qui gèrent l'envoi d'un mail.
Dans la plupart des cas on utilise le __job__ `CustomMailerDeliveryJob` pour envoyer des mails, mais pour les mails devise, le job est effectivement  `ActionMailer::MailDeliveryJob`, qui appelle ensuite le __mailer__ `CustomDeviseMailer` (c'est d'ailleurs le cas dans le screenshot donné en exemple).

On peut d'ailleurs vérifier en base que le mailer est le bon pour ces jobs :
```
GoodJob::Job.where("serialized_params @> '{\"job_class\": \"ActionMailer::MailDeliveryJob\"}'").count # 1316
GoodJob::Job.where("serialized_params @> '{\"job_class\": \"ActionMailer::MailDeliveryJob\"}'").where("(serialized_params -> 'arguments' ->> 0) = 'CustomDeviseMailer'").count # 1316 aussi
```

J'ai vérifié parmis la liste des mails envoyés via `ActionMailer::MailDeliveryJob` : j'ai trouvé un mail qui devait être envoyé depuis RDV Aide Numérique, et c'était bien l'adresse utilisée dans les logs Brevo.
