### ISSUE TITLE
Refonte DSFR - Footer et pages statiques

### ISSUE THREAD

**Issue by julieSalha** [betagouv/rdv-solidarites.fr#3585]
## ℹ️ Contexte 

Ce ticket concerne la refonte grâce au [DSFR - Système de Design de l'État](https://www.systeme-de-design.gouv.fr/elements-d-interface) du footer et des pages statiques disponibles depuis le footer (dans la mesure du possible) : 

- [x] [Déclaration d'accessibilité](https://demo.rdv-mairie.fr/accessibility)
- [x] [Mentions légales](https://demo.rdv-mairie.fr/mentions_legales)
- [x] [CGU](https://demo.rdv-mairie.fr/cgu)
- [x] [Politique de confidentialité](https://demo.rdv-mairie.fr/politique_de_confidentialite)
- [x] [Gestion des cookies](https://demo.rdv-mairie.fr/politique_de_confidentialite#cookies)
- [ ] [Statistiques](https://demo.rdv-mairie.fr/stats)

La refonte comprend l'affichage responsive des pages (mobile - tablette - bureau).

## ❓ Définition du problème

La structure HTML et styles CSS sont actuellement gérés par Bootstrap.

## 💡 Solution envisagée

* Comportement attendu : 
Les modifications se baseront sur les documentations DSFR suivantes : 

- [ ] [Espacement](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/espacement)
- [ ] [Grilles et points de rupture](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/grille-et-points-de-rupture)

## 🧪 Scénarios de test

* Étapes pour aboutir sur le comportement attendu
* Lien de la review app pour tester : 

Un ou plusieurs tests utilisateurs seront demandés avant de mettre en production les modifications apportées.

**Comment by victormours** [comment]
On n'a pas besoin d'un footer pseudo dsfr. Si les pages statiques sont déjà modifiées dans le cadre de #3606, on peut fermer ce ticket (et de toutes façons les pages statiques sont beaucoup moins importantes à passer au dsfr que le parcours de prise de rdv)

**Comment by julieSalha** [comment]
> On n'a pas besoin d'un footer pseudo dsfr. Si les pages statiques sont déjà modifiées dans le cadre de #3606, on peut fermer ce ticket (et de toutes façons les pages statiques sont beaucoup moins importantes à passer au dsfr que le parcours de prise de rdv)

Les pages ont été modifées surtout pour déplacer le titre principal h1 du header vers le contenu principal. On peut privilégier le parcours de rendez-vous en effet. Les pages statiques sont quand même importantes et rentrent en compte dans le cadre de l'audit (CGU, Mentions légales, Déclaration d'accessibilité...). Elles ont déjà été travaillées sur une autre branche [optimization-footer-and-static-pages](https://github.com/betagouv/rdv-solidarites.fr/tree/optimization-footer-and-static-pages). On en reparle :-)
