### ISSUE TITLE
Gérer inclusion Connect pour RDV Service Public

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3586]
Il faut soit masquer le bouton inclusion connect, soit faire marcher le SSO

**Comment by Holist** [comment]
Je peux m'en occuper. Pour info, c'est pas bien compliqué de faire fonctionner le SSO, il manque les variables d'env sur scalingo. (il faut demander à IC un client_id et un secret pour rdv-service-public)
Cela étant dit, je me demande si c'est ok de mettre à dispo un SSO qui concerne "Tous les professionnels de l’inclusion" sur ce sujet ? (je vois que ça a été déployer sur rdv-aide-numerique)

**Comment by Holist** [comment]
J'ai désactivé IC avec la variable d'environnement "INCLUSIONCONNECT_DISABLED" dans scalingo.
L'issue ou on peut discuter de la pertinence ou pas de la mise en place d'IC pour rdv-service-public et les mairies : 
https://github.com/betagouv/rdv-solidarites.fr/issues/3590
