### ISSUE TITLE
Passer le header et la police de l'interface usager au dsfr

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3606]
On va commencer par changer juste le header et la police sur toutes les pages du front usager, pour faire en sorte d'avoir une meilleure continuité entre les pages legacy et les pages DSFR. On pourra ensuite faire des migrations pages par pages ou parcours par parcours.

**Comment by julieSalha** [comment]
Pour la recette, voici le lien vers la PR : [Refonte DSFR progressive - Header transition redesign #3633](https://github.com/betagouv/rdv-solidarites.fr/pull/3633)
