### ISSUE TITLE
[SSI] Mettre en œuvre une procédure de suppression des comptes inactifs

### ISSUE THREAD

**Issue by Scttpr** [betagouv/rdv-solidarites.fr#3623]
## ℹ️ Contexte 

Dans le cadre de l'homologation il est demande de :

> Mettre en œuvre une procédure de suppression des comptes inactifs

A definir ce qu'est un utilisateur inactif mais la suppression rentre aussi dans le respect de la RGPD. A voir techniquement mais cela semble indispensable dans tous les cas.

**Comment by victormours** [comment]
Consigne complète sur Mon Service Sécurisé : 
> Configurer le service en vue de prévoir la suppression régulière des comptes d'accès inactifs, en priorisant la suppression des comptes d'administration. Informer les personnes concernées avant toute suppression de compte.
Cette mesure permet d'éviter en priorité que des comptes demeurent actifs sans raison valable, afin de réduire le nombre de comptes susceptibles d'être usurpés par un acteur malveillant.

Dans notre cas, les comptes usagers qui sont inactifs sont ceux qui n'ont pas fait de rdv au bout de 2 ans, et qu'on n'ont pas de proche actifs. Je pense qu'on peut se passer des les notifier pour deux raisons :
- leurs rdvs ont été supprimés, et il n'y a pas d'autre infos utiles liées à leur compte, ce sont des "coquilles vides". RDV Service Public est fait pour organiser les rdv, pas pour garder des informations à long terme sur le dossier de quelqu'un (ça doit être fait dans un logiciel métier séparé).
- dans certains cas du médico-social, on évite explicitement d'envoyer des notifications pour des motifs de rdv sensibles (rdv dans les centre de santé sexuelle par exemple). C'est sans doute moins dangereux dans ces cas de ne pas envoyer une notification qui pourrait amener quelqu'un d'autre que l'usager à savoir qu'il ou elle a eu ces rdv.
