### ISSUE TITLE
Mettre à jour la fiche beta.gouv

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#3627]
### Contexte ℹ️ 

Notre page bêta nous sert aujourd'hui de page vitrine, l'objet de cette issue est de la mettre à jour en enlevant les "S" et modifiant le contenu comme noté sur ce pad : https://pad.numerique.gouv.fr/QraYEmoPSeaH9R-wLwGZGg

**Comment by victormours** [comment]
fait ! https://beta.gouv.fr/startups/rdv-service-public.html
