### ISSUE TITLE
Décourager la création d'usagers en doublons côté agents et proposer de nouveaux critères de détection

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#3653]
suite du ticket sur les doublons pour le 92 (voir #3429)

Sur ces deux écrans côté agent, on veut faire que l'action la plus simple ne soit pas de créer un usager en doublon, mais de réutiliser le profil existant.

<img width="833" alt="Screenshot 2023-06-27 at 16 36 05" src="https://github.com/betagouv/rdv-solidarites.fr/assets/1840367/65be00e7-6e3e-4179-80cf-f4604c350a74">

<img width="1677" alt="Screenshot 2023-06-27 at 16 37 06" src="https://github.com/betagouv/rdv-solidarites.fr/assets/1840367/e937f24a-0047-4447-bef6-9a8b3649be4d">

Nos trois conditions de détection des doublons :
- nom, prénom et date de naissance identiques
ou
- adresse email identique
ou
- numéro de téléphone identique.

Attention au cas où les infos entrées par l'agent ne correspondent pas aux infos sur le profil du doublon potentiel (par exemple même adresse mail mais numéros de téléphone différents.

**Comment by victormours** [comment]
maquettes : https://www.figma.com/file/4VxZPNNrn6uow4KGqWiOJw/Dissuasion-de-doublons?type=design&node-id=1%3A34&mode=design&t=3dDLC3hkMUMEFI3t-1

**Comment by victormours** [comment]
Contrairement à ce que j'espérais, c'est assez galère de faire une analyse du niveau de différences entre deux doublons potentiels (à cause de variance de politique d'un territoire à l'autre, de la complexité de distinguer et comptabiliser les doublons dans une orga, ou dans un territoire, ou dans toute la base, et de "biais du survivant" puisqu'on peut juste voir les doublons créés malgrés notre système de détection et d'avertissement actuel). Du coup on peut pas trop faire d'hypothèse sur à quel point les deux fiches qu'on proposera seront similaire ou différentes.

**Comment by victormours** [comment]
autre ticket zammad : https://zammad10.ethibox.fr/#ticket/zoom/7938

**Comment by victormours** [comment]
Récap sur les différents cas :

|Action de départ|      Doublon potentiel sur numéro de téléphone ou nom, prénom et date de naissance    | Doublon potentiel sur email||
|-|-|-|-|
|Création d'un usager lors de la création d'un rdv||||
|Modification d'un usager lors de la création d'un rdv||||
|Création d'un usager depuis la liste des usagers||||
|Modification d'un usager existant||||

### Création d'un usager lors de la création d'un rdv

Cas possible :
- usager similaire dans l'organisation

**Comment by victormours** [comment]
Changements au formulaire de recherche : 
- ajouter un label "Rechercher un usager"
- placeholder "Nom, Prénom, téléphone, ou email
- changer le format de résultat d'autocomple par "FACTICE Francis - 0611223344 - ff@cool.com"
- supprimer le "Commencer à taper pour rechercher" par "Renseignez le prénom, le nom, l'adresse email ou le numéro de téléphone de l'usager"
- déplacer le lien de création d'un usager à droite de la barre de recherche 
- faire cette recherche à l'échelle de tout le territoire et pas uniquement l'organisation courante

**Comment by victormours** [comment]
Il y a deux possibilités d'implémentation : une qui transforme le select en un vrai autocomplete, et l'autre qui continue d'utiliser un select (moins joli, mais plus rapide à faire)

**Comment by victormours** [comment]
<img width="1438" alt="Screenshot 2023-10-25 at 12 31 54" src="https://github.com/betagouv/rdv-solidarites.fr/assets/1840367/264ca2b5-1709-4d9c-a6b2-0be8a3c3ccba">
<img width="1425" alt="Screenshot 2023-10-25 at 12 32 13" src="https://github.com/betagouv/rdv-solidarites.fr/assets/1840367/45df248d-2bb6-47b4-b891-cb1f93648664">
<img width="1428" alt="Screenshot 2023-10-25 at 12 32 25" src="https://github.com/betagouv/rdv-solidarites.fr/assets/1840367/e133e844-9899-4f03-a33d-582ec4a6f3b8">

**Comment by Teodora-Stanki** [comment]
**Point avec Clarisse le 7.11 :**
Nous avons évoqué avec elle la dissuasion de doublons, et elle nous a reconfirmé que la date de naissance était une information primordiale dans sa recherche d'usagers, et pour différencier les homonymes, alors que le numero de telephone et l'adresse email restent des informations secondaires et pas nécessairement utilisées :

- La date de naissance est une information immuable et liée à l'individu, et ne risque donc pas de changer contrairement au numero de telephone, et l'adresse email
- Les numero et adresses email sont beaucoup moins renseignés que la date de naissance
- Les collègues ont tendance a rajouter le numero sous divers formats (0606, 06.06, 06 06 etc.) ce qui ne facilite pas la lecture
- Par habitude elle se base sur la date de naissance pour différencier des usagers, et encourage ses agents a en faire de meme.

**Conclusion :** nous aurions potentiellement une regression UX si nous enlevions l'info "date de naissance" dans la ligne usager. **Il serait donc préférable de garder la ligne usager sous ce format : NOM-Prenom-JJ/MM/AAA-numero-email.**
Quant à la recherche par date de naissance, nous pourrions l'envisager dans une version ultérieure en tant qu'amélioration.

**Comment by victormours** [comment]
Ça marche, j'ai fais la mise à jour pour qu'on ai le format "NOM Prenom - JJ/MM/AAA - numero - email"

Un point positif : on a normalisé les format de numéro de téléphone pour qu'ils soient toujours affiché au format "06 11 22 33 44", peut importe comment l'agent l'a entré.
