### ISSUE TITLE
Refonte pages de connexion

### ISSUE THREAD

**Issue by Teodora-Stanki** [betagouv/rdv-solidarites.fr#3708]
Dans le cadre de la création du [tunnel d'onboarding](https://github.com/betagouv/rdv-solidarites.fr/issues/3654), il serait nécessaire de refondre la page de première connexion Agent, et tant qu'à faire, les pages de connexion / inscription pour les agents et usagers.

## Problèmes constatés pour la connexion / inscription :
- Depuis la Landing Page, les CTA du header "Connexion Agent" et "Connexion Usager" portent à confusion pour l'utilisateur ;
- Les pages de connexion / inscription ne sont pas homogènes graphiquement pour les deux personae ;
- Certains champs se retrouvent en dessous de la ligne de flottaison selon les résolutions.

## Solutions envisagées 
- Garder l'actuel avec une page de connexion 'particulier' ([Figma](https://www.figma.com/file/0er4UN7N3R37Ag34Aq1GTX/Refonte-LP?type=design&node-id=525%3A35506&mode=design&t=jvpMMhvqJKkNC72k-1)) et une page connexion 'professionnel' ([Figma](https://www.figma.com/file/0er4UN7N3R37Ag34Aq1GTX/Refonte-LP?type=design&node-id=644%3A18065&mode=design&t=jvpMMhvqJKkNC72k-1))
- Concevoir une page unique de connexion, avec 2 onglets "[particulier](https://www.figma.com/file/0er4UN7N3R37Ag34Aq1GTX/Refonte-LP?type=design&node-id=644%3A17527&mode=design&t=jvpMMhvqJKkNC72k-1)" et onglet "[professionnel](https://www.figma.com/file/0er4UN7N3R37Ag34Aq1GTX/Refonte-LP?type=design&node-id=644%3A17786&mode=design&t=jvpMMhvqJKkNC72k-1)"
- Concevoir une seule page, avec un formulaire unique qui puisse permettre la detection du type de connexion (pro ou particulier) en fonction de l'adresse email renseignée ([Figma](https://www.figma.com/file/0er4UN7N3R37Ag34Aq1GTX/Refonte-LP?type=design&node-id=552%3A34823&mode=design&t=jvpMMhvqJKkNC72k-1))
- Mettre le tout au DSFR

## Solution retenue

Concevoir une seule page, avec un formulaire unique qui puisse permettre la detection du type de connexion (pro ou particulier) en fonction de l'adresse email renseignée ([Figma](https://www.figma.com/file/0er4UN7N3R37Ag34Aq1GTX/Refonte-LP?type=design&node-id=552%3A34823&mode=design&t=jvpMMhvqJKkNC72k-1))

**Comment by victormours** [comment]
@mekaidmekaid @Teodora-Stanki @francois-ferrandis  c'est dommage parce que dans la solution retenue :
- il manque un cas d'usage assez important
- on introduit une régression en UX (et on passe juste à côté d'une solution plus simple)
- certains textes sont faux, d'autres sont manquants

et dans le diagnostic du problème, la solution existante déjà en place n'apparait pas.

J'aimerais bien que vous identifiez ces différents points avant de commencer du développement.
