### ISSUE TITLE
Invitation d'agent en erreur pour des maries

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#3719]
Nous avons cette remontée sentry qui semble indiquer que certaines invitations d'agents rdv mairie via le script super admin sont en erreur et ne sont pas envoyées.

https://sentry.incubateur.net/organizations/betagouv/issues/41669/events/7770539650594b778f9d543c5beb51f3/?project=74

Le problème semble se situer sur le model `current_super_admin` qui est la personne qui invite l'agent pour l'attribut `invited_by.full_name` dans le template de mail.

**Comment by victormours** [comment]
corrigé par https://github.com/betagouv/rdv-solidarites.fr/pull/3739
