### ISSUE TITLE
Rendre plus lisible sur l'agenda les créneaux de 15min

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#3727]
### Définition du problème ❓ 

Les créneaux de 15min sont la normale pour les RDV en mairie. 

On a eu plusieurs remarques d'utilisateurs en phase d'adoption qui se plaignent du fait que le contenu des créneaux est illisible. Voir capture : 

![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/122271472/80c2fa3d-d456-46d3-8260-604400a16f30)

### Solution proposée 💡 

Je propose de doubler la taille des cases et de passer de 1.5em a 3em comme ci-dessous, et adapter ensuite la taille des cellules de rdv

![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/129159292/40ffac2c-a52f-4260-ad30-f3676627f891)

**Comment by Teodora-Stanki** [comment]
Je propose de doubler la taille des cases et de passer de 1.5em a 3em comme ci-dessous


![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/129159292/40ffac2c-a52f-4260-ad30-f3676627f891)

**Comment by mekaidmekaid** [comment]
Il est possible de tester sur cette url : https://rdv.anct.gouv.fr/admin/organisations/62/agent_agendas/61

**Comment by Teodora-Stanki** [comment]
Voici ce que ca donne avec l'agenda d'un agent de mairie :

Vue semaine :
![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/129159292/d1e68754-adca-4987-93bd-5b822321491c)

Vue planning : 
![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/129159292/5cd888fd-39f7-4331-a11f-7872af7dd74f)

**Comment by Holist** [comment]
C'est vraiment simple à faire, il s'agit effectivement que d'un ligne de css à ajouter.
Mais je me pose la question des conséquences pour tout les autres agents des autres verticales.
En effet aujourd'hui sur un écran relativement "grand" ils peuvent voir toute leur semaine de rdv et les jours en entier.
Après cette modification il ne verront plus que les matinées de leur semaine de travail.
Et je ne pense pas que ce soit une bonne idée d'appliquer des différences de css pour certaines verticales.
Dans ce cas est ce qu'un bouton "Zoom" (Loupe) entre les boutons Planning et Aujourd'hui ne serait pas une solution ? Sachant que les agents mairie devraient penser à l'utiliser au moins une fois (on pourrait stocker la valeur de cette "préférence" dans leur session)
Qu'en pensez vous ? (et j'en profites pour te demander @victormours )

**Comment by Holist** [comment]
réglé ici https://github.com/betagouv/rdv-solidarites.fr/pull/3735
