### ISSUE TITLE
Merger 2 agents d'une meme organisation

### ISSUE THREAD

**Issue by ousmanedev** [betagouv/rdv-solidarites.fr#3793]
Il faudrait exporter les infos de l'agent Marjorie BROUX [#2223](https://www.rdv-solidarites.fr/super_admins/agents/2223) sur l'agent #15924

## Contexte

> Il s'agit d'une demande remontée par référente du 62. Une même agent dans un même service d'une même organisation s'est vue ouvrir deux comptes. Le premier est celui qu'elle utilisait jusqu'alors, le second a été créé par erreur car l'agent a change de nom de famille. L'hypothèse est que ce compte a été créé par la seconde référente du 62 qui n'a pas connaissance de tous les process. Dans les faits, l'agent se retrouve donc avec deux comptes. De fait, elle a des RDV dispatchés dans deux plannings différents. Pour ces collègues, cette situation porte également à confusion car ils répartissent les RDV dans les deux agendas de manière aléatoire. Cette confusion est assez importante car les impacts ne sont pas négligeables et durent depuis 4 mois.
> Permettre la "fusion agent" permettrait de rétablir l'ordre dans cette organisation

**Comment by NesserineZarouri** [comment]
Pour le contexte : il s'agit d'une demande remontée par référente du 62. Une même agent dans un même service d'une même organisation s'est vue ouvrir deux comptes. Le premier est celui qu'elle utilisait jusqu'alors, le second a été créé par erreur car l'agent a change de nom de famille. L'hypothèse est que ce compte a été créé par la seconde référente du 92 qui n'a pas connaissance de tous les process. Dans les faits, l'agent se retrouve donc avec deux comptes. De fait, elle a des RDV dispatchés dans deux plannings différents. Pour ces collègues, cette situation porte également à confusion car ils répartissent les RDV dans les deux agendas de manière aléatoire. Cette confusion est assez importante car les impacts ne sont pas négligeables et durent depuis 4 mois. 
Permettre la "fusion agent" permettrait de rétablir l'ordre dans cette organisation
