### ISSUE TITLE
Rdv en Binome Multi-service

### ISSUE THREAD

**Issue by ousmanedev** [betagouv/rdv-solidarites.fr#3850]
## ℹ️ Contexte 
Quand on tente de modifier un Rdv, il est possible d'y rajouter un autre agent.

A ce stade, la liste des agents qu'on peut ajouter est limitée aux agents du même service que celui de l'agent opérant la modification.

## ❓ Définition du problème
Il n'est actuellement pas possible de prendre donc un RDV en binôme, lorsque les 2 agents font partie de services différents.

## 💡 Solution envisagée
Le but de ce ticket pouvoir modifier ce comportement, en élargissant la liste des agents aux agents des autres services que celui de l'agent connecté.

Lien de test : https://demo-rdv-solidarites-pr3854.osc-secnum-fr1.scalingo.io/

**Comment by mekaidmekaid** [comment]
@ousmanedev premiers tests très positifs, merci à toi, voici ce qu'il en ressort : 

* Créer un RDV avec deux agents de services différents 🆗 
* Editer un RDV existant pour y ajouter un agent différent 🆗 
* L'affichage du rdv suite aux différentes opération sur les deux agendas 🆗 
* Affichage sur la liste des usagers 🆗 
* Nom du service à côté du prénom et nom de l'agent 🆗 
* Affichage sur la liste des RDV ❌ 
la liste m'indique 3 RDV alors qu'il n y en a que deux (voir capture) 🤷 

![Image](https://github.com/betagouv/rdv-solidarites.fr/assets/122271472/4c92cd15-23b6-4c0c-a78d-5e89f38a5132)



Des questions : 

* Difficile de tester les notifications sur la review app, est ce que les deux agents recoivent bien les modifications suivant ce qu'ils ont configuré sur les préférences de notifs ? https://demo-rdv-solidarites-pr3854.osc-secnum-fr1.scalingo.io/agents/preferences

* La Drôme comme plein d'autres départements utilisent la synchro avec Zimbra à base de webhooks, est ce que l'affichage du RDV sur les deux agendas dans Zimbra sera effectif à la création comme à la modification ?

* Sur quel base s'affiche le message d'indispo que tu as mis quand on ajoute un agent et que celui-ci n'est pas dispo ? J'ai mis une plage d'indispo à Gina et quand Bruno l'ajoute là où elle a indiqué avoir une indispo, mais rien ne m'indique cette info au niveau de l'interface. Très chaud pour m'expliquer que je puisse tester et très chaud aussi pour remettre cela à la V1 si c'est trop compliqué.

**Comment by ousmanedev** [comment]
> @ousmanedev premiers tests très positifs, merci à toi, voici ce qu'il en ressort :
> 
> * Créer un RDV avec deux agents de services différents 🆗
> * Editer un RDV existant pour y ajouter un agent différent 🆗
> * L'affichage du rdv suite aux différentes opération sur les deux agendas 🆗
> * Affichage sur la liste des usagers 🆗
> * Nom du service à côté du prénom et nom de l'agent 🆗
> * Affichage sur la liste des RDV ❌
>   la liste m'indique 3 RDV alors qu'il n y en a que deux (voir capture) 🤷
> 
> ![Image](https://user-images.githubusercontent.com/122271472/280083667-4c92cd15-23b6-4c0c-a78d-5e89f38a5132.png)
> 
> Des questions :
> 
> * Difficile de tester les notifications sur la review app, est ce que les deux agents recoivent bien les modifications suivant ce qu'ils ont configuré sur les préférences de notifs ? https://demo-rdv-solidarites-pr3854.osc-secnum-fr1.scalingo.io/agents/preferences
> * La Drôme comme plein d'autres départements utilisent la synchro avec Zimbra à base de webhooks, est ce que l'affichage du RDV sur les deux agendas dans Zimbra sera effectif à la création comme à la modification ?
> * Sur quel base s'affiche le message d'indispo que tu as mis quand on ajoute un agent et que celui-ci n'est pas dispo ? J'ai mis une plage d'indispo à Gina et quand Bruno l'ajoute là où elle a indiqué avoir une indispo, mais rien ne m'indique cette info au niveau de l'interface. Très chaud pour m'expliquer que je puisse tester et très chaud aussi pour remettre cela à la V1 si c'est trop compliqué.

## Réponses aux questions
1 - Je confirme que les notifications sont bien reçues par les 2 agents
2 - Je confirme la synchro des agendas via les webhooks fonctionne parfaitement pour les 2 agents
3 - Le message d'indisponibilité est normalement affiché lorsqu'il y a conflit entre l'intervalle de temps du Rdv et la plage de disponibilité d'un agent. Dispo pour en discuter, en profondeur.
