### ISSUE TITLE
Message indiquant l'indisponibilité d'un agent disponible 

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#3974]
## ℹ️ Contexte 

* Remontée utilisateur : 
- CD 26 : [téléphone le 12.01] nous a fait des remontées à sujet. Plusieurs agents seraient impactés par ce bug. 

* Description : 
Un agent créé une plage d'ouverture dont les disponibilités sont visibles sur le moteur de recherche de créneau. Lorsqu' un agent entame le formulaire de prise de RDV, un message d'erreur s'affiche indiquant l'indisponibilité de l'agent (qui est pourtant bien disponible)

* Reproduction du bug 
- Un agent a créé une plage d'ouverture (https://www.rdv-solidarites.fr/admin/organisations/3194/agents/11222/plage_ouvertures) nommée PPA de 9h à 9h45 pour un motif de 45 min

- La journée du 25.01 indique bien la disponibilité de l'agent <img width="953" alt="Capture d’écran 2024-01-12 à 14 34 19" src="https://github.com/betagouv/rdv-service-public/assets/103633345/59d9707d-c802-4d82-93ec-1ea7e2eaed6b">

- En effectuant une recherche de créneau pour la prise de RDV depuis la fiche usager ou l'agenda "Trouver un RDV", le créneau disponible est visible
<img width="801" alt="Capture d’écran 2024-01-12 à 14 36 35" src="https://github.com/betagouv/rdv-service-public/assets/103633345/f758614b-6dcc-406f-9531-4a5b13a48e39">

- On sélectionne le créneau et entamons le formulaire de prise de RDV avec un usager test

- A l'étape ""Agent, horaire et lieux", un message affiche que l'agent "n'est pas disponible pendant la période du RDV"

## ❓ Hypothèse 
Les remontées sont faites par les agents multi-services. Un rapport peut-être ?

**Comment by ousmanedev** [comment]
Update: Je pense qu'il s'agit d'une indisponibilité récurrente de l'agent. Toutefois, du fait de l'indisponibilité, la recherche de créneaux ne devrait pas proposer un slot indisponible pour Rdv.

J'attends de reproduire le bug en live avec Nesserine.

**Comment by ousmanedev** [comment]
Fixed by https://github.com/betagouv/rdv-service-public/pull/4072
