### ISSUE TITLE
Modifier mentions légales et ajouter logos ANCT et Dinum

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#4016]
#### Contexte 

> Hello Team, je vous partage une demande de la Communication ANCT, pouvez-vous me confirmer la bonne prise en compte de votre côté ? 
> 
> Un grand merci
>  
> *"Pourriez-vous mettre à jour les informations de cette plateforme :*
> Directeur de la publication : Stanislas Bourron et non Yves Breton.*
> Par ailleurs, vous indiquez que cette plateforme est éditée par L’ANCT mais aucun logo ANCT n’apparait…. 
> En bas de page les logos ne sont pas dans le bon ordre : D’abord la Marianne de l’Etat et ensuite le logo Beta.gouv.fr"

#### Attendu #1

Remplacer `Yves Breton` par `Stanislas Bourron` sur les mentions légales : 

* https://rdv.anct.gouv.fr/mentions_legales
* https://www.rdv-solidarites.fr/mentions_legales
* https://www.rdv-aide-numerique.fr/mentions_legales

#### Attendu #2

Revoir les logos dans les footers front de tous nos sites (visibles par tous les utilisateurs non connectés)

* Ajouter le logo de l'ANCT (déjà présent sur rdv.anct.gouv.fr)
* Ajouter le logo de la Dinum
* Placer les logo dans l'ordre suivant : La Marianne, le logo Beta.gouv.fr, le logo de l'ANCT et enfin le logo de la DINUM.

**Comment by Teodora-Stanki** [comment]
Nous pouvons conserver le footer actuel de rdv-solidarites.fr et changer les élements pour y faire figurer dans l'ordre et sur une ligne :
- Le logo de l'Etat (marianne)
- le logo de l'ANCT
- le "logo" de la dinum (ils n'ont pas de logo a proprement parlé)
- le logo beta.gouv

Dans le kit de communication de l'ANCT il y a dejà un logo libellé "financé par" avec la marianne et le logo de l'ANCT (en pièce jointe) : ![ANCT_FinancePar](https://github.com/betagouv/rdv-service-public/assets/129159292/cd14fc42-b0f3-42d3-bf98-75e4c7d4b645)

Pour la dinum, il s'agit juste d'indiquer "Direction ministerielle du numérique" (ce que fait Demarches Simplifiees par exemple) ->
![Logo DINUM](https://github.com/betagouv/rdv-service-public/assets/129159292/4de8e640-8ce0-497c-9ce7-b9245418f046)

**Comment by mekaidmekaid** [comment]
@Teodora-Stanki le png du logo officiel récupéré par Matis de la Dinum 

![Logo_Gouvernement-DINUM_RVB](https://github.com/betagouv/rdv-service-public/assets/122271472/55865755-3bd5-4246-9605-21709fae169b)

**Comment by mekaidmekaid** [comment]
Du coup selon ce que fait Matis, il place le logo de la Dinum en premier car Marianne puis ANCT. Je te confirme qu'il n y a aucune obligation pour le logo bêta c'est facultatif.

**Comment by mekaidmekaid** [comment]
Le logo officiel de la Dinum tel que communiqué par eux à Matis : 

![Image](https://github.com/betagouv/rdv-service-public/assets/122271472/a6a73148-9e77-4bd0-8f93-8fb9a2b25380)

Je ne pense pas qu'on ait le droit d'utiliser que la partie droite.

Peut être qu'il faudrait dans ce cas là l'afficher lui en premier car il inclu la Marianne, puis celui de l'ANCT sans afficher celui de bêta.
