### ISSUE TITLE
2 admins d'une même orga voient des informations différentes sur le planning du même agent

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-solidarites.fr#4074]
## ℹ️ Contexte 

Mail d'une admin du Var qui utilise rdv-s et rdv-i qui a remarqué qu'elle ne voyait pas les mêmes infos sur l'agenda d'un agent que son collègue également admin qui regarde le même agenda.

## ❓ Définition du problème

En tant qu'admin A, sur l'orga CAF du Var - La Garde, je souhaite consulter l'agenda de l'agent "CAF LAGARDE". Je me rends donc sur son planning et je consulte l'agenda du 5 au 9 fevrier.

En tant qu'admin B, sur l'orga CAF du Var - La Garde, je souhaite consulter l'agenda de l'agent "CAF LAGARDE". Je me rends donc sur son planning et je consulte l'agenda du 5 au 9 fevrier.

L'admin A et B se rendent comptent qu'ils ne voient pas les mêmes infos apparaître sur le planning.

Vue de l'admin A

Vue de l'admin B

## 💡 Solution envisagée

* Comportement attendu

Etant donné que les 2 admins ont le même niveau de droit et qu'ils consultent le même planning, ils devraient voir apparaître les mêmes infos.

**Comment by victormours** [comment]
Ces deux admins n'ont pas les mêmes préférences pour l'option "Afficher les rdv annulées" (visible en bas à droite du calendrier), ce qui explique que l'un voit les rdv annulés et pas l'autre.
Dans les deux cas on voit des rdv où le nom de l'usager est barré, ce qui indique des absences non excusées, et qui est donc affiché même si l'agent a choisi de ne pas afficher les rdv annulés
