### ISSUE TITLE
RDV Mairie : incohérence entre les plages d'ouvertures et les disponibilités affichées sur l'ANTS

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#4158]
## ℹ️ Contexte 

* Ticket Zammad : Ticket#5112123

* Comportement actuel : 
  
Sur RDVSP, une mairie établie des plages d'ouverture de 10h15 à 11h45 à partir de mars 

Sur l'ANTS, les disponibilités s'affichent à partir de 10h jusqu'à 12h45

<img width="483" alt="Capture d’écran 2024-03-12 à 17 24 45" src="https://github.com/betagouv/rdv-service-public/assets/103633345/da270fa6-665d-4806-bd27-61a71fd996e1">

**Comment by victormours** [comment]
Je n'arrive pas à reproduire le bug pour Wavignies, et je remarque le l'équipe de l'ANTS vient de passer un correctif qui s'appelle "fix: issue on saeson hour", qui consiste à enlever un décalage d'une heure sur les horaires des dispos. (voir https://gitlab.com/france-titres/rendez-vous-mairie/rendez-vous-mairie/-/merge_requests/838/diffs)
Autrement dit : ça a l'air d'être un bug du côté de l'ANTS qui a été résolu.

**Comment by victormours** [comment]
J'arrive maintenant à reproduire le bug pour wavignies : les créneaux avant le passage à l'heure d'été (31 mars) sont les bons, mais ceux après sont décalés d'une heure.

Je confirme que le correctif de l'ants résoudrait le problème. J'ai écris à leur PM pour demander quand il sera en ligne (voir https://zammad10.ethibox.fr/#ticket/zoom/12242)

**Comment by victormours** [comment]
Je confirme que c'est donc un bug du côté ANTS, et qu'ils devraient le résoudre bientôt.

**Comment by victormours** [comment]
Le bug a été résolu par l'ants ! https://gitlab.com/france-titres/rendez-vous-mairie/interaction-avec-les-editeurs/-/issues/37#note_1813298300

Maintenant ça serait bien de faire en sorte que la prochaine fois on aille directement vois sur https://gitlab.com/france-titres/rendez-vous-mairie/interaction-avec-les-editeurs/-/issues pour ce genre de question. Je pense qu'il faut qu'on document ce lien quelque part (mais je sais pas où)
