### ISSUE TITLE
Une utilisatrice se fait spammer de sms en s'inscrivant pour recevoir les créneaux disponibles

### ISSUE THREAD

**Issue by mekaidmekaid** [betagouv/rdv-solidarites.fr#4172]
#### Contexte

Une utilisatrice a demandé à être informée par sms si un créneau se libère pour récupérer son passeport plus tôt à la mairie de Mennecy.
Elle a reçu une centaine de sms, non seulement avec un lien qui ne me permets pas reprendre rendez-vous, mais surtout sans possibilité pour elle d'arreter ces envois, meme en bloquant l’expediteur.

Plus de contexte ici : https://zammad10.ethibox.fr/#ticket/zoom/12153

L'historique des 136 sms est visible sur notification envoyées sur cette page : https://rdv.anct.gouv.fr/admin/organisations/165/rdvs/49861

**Comment by victormours** [comment]
On avait un bug qui faisait que les usagers qui ont désactivé les notifications par mail se faisaient spammer de sms par le mécanisme de file d'attente, c'est corrigé !
