### ISSUE TITLE
SaaS : N°ANTS demandé pour la prise de RDV d'un proche 

### ISSUE THREAD

**Issue by NesserineZarouri** [betagouv/rdv-solidarites.fr#4179]
## ℹ️ Contexte 

Source : retour d'une ComCom après l'utilisation en démo de RDVSP 

En tant qu'usager, lors de la prise de rendez-vous en ligne, au moment de l'identification de l’usager, si je souhaite prendre rendez-vous pour un proche, un champ « n° ANTS » est demandé. Ce champ est obligatoire et l'usager ne peut pas continuer l'identification du proche sans cette information. 

<img width="719" alt="Capture d’écran 2024-03-15 à 16 54 26" src="https://github.com/betagouv/rdv-service-public/assets/103633345/049103ff-bacc-4b56-9bc3-10a2bac8346c">

## ❓ Définition du problème

Nous souhaiterions ne plus faire apparaitre cette mention dans la prise de rendre-vous en ligne d'un proche car cette information n'est pas cohérente dans la prise de rendez-vous dans un domaine autre que celui des CNI / passeport.

**Comment by victormours** [comment]
c'est corrigé ! Le champs ne s'affichera que s'il est nécessaire pour le rdv (motif lié à une catégorie de motif branchée sur l'ants)
