### ISSUE TITLE
[RGPD] Mise en conformité des données de journalisation

### ISSUE THREAD

**Issue by victormours** [betagouv/rdv-solidarites.fr#4223]
## ℹ️ Contexte 

Dans le cadre des discussion sur la RGPD, Numéricité a attiré notre attention sur [cet article de la CNIL](https://www.cnil.fr/fr/la-cnil-publie-une-recommandation-relative-aux-mesures-de-journalisation) sur les mesures de journalisations.

Elle conseille de conserver les données de journalisation entre 6 mois et 1 an.

Nous avons au moins trois cas qui correspondent à la "journalisation" au sens de cet article de la CNIL :
- Les logs applicatifs sur Scalingo
- Les "historiques de changements" visible dans l'interface, et implémentés avec la table `versions`
- La liste de notifications envoyées pour un rdv, implémentée avec la table `receipts`

Les receipts servent aussi à savoir combien de sms chaque département a envoyé, ce qui est utilisé pour la facturation. Ils ont seulement 4 colonnes qui contiennent des infos personnelles (`sms_phone_number email_address content error_message`), et la référence au rdv.
Les receipts n'ont pas de versions (ouf).

### Tables avec des versions et des données personnelles
- user
- agent_service
- rdv
- file_attente
- agent_territorial_role
- agent_territorial_access_right
- super_admin
- referent_assignation
- agent_role
- agent_team
- agent
- absence
- user_profile

## Tables avec des versions mais sans données personnelles :
- webhook_endpoint
- service
- lieu
- organisation
- territory
- team
- motif_category
- motif
- plage_ouverture
- territory_service

## ❓ Définition du problème

Nos durées de conservations sont les suivantes :
- ✅ 1 an pour les logs scalingo (voir https://doc.scalingo.com/platform/app/logs#log-retention)
- 🟥 2 ans pour les versions
- 🟥 2 ans pour les receipts

## 💡 Solution envisagée

- Supprimer les versions au bout d'un an pour les tables avec des données personnelles (historique de changements des usagers, rdvs, agents)
  - Pour les rdv qui ont plus d'un an, ça veut dire que lors des exports, on ne pourra pas afficher qui a créé le rdv : on est ok avec ce changement de comportement, puisque c'est probablement pas un problème, et on peut le justifier auprès des référentes avec la rgpd.

- Garder la durée de conservation de 5 ans pour les versions sur des tables qui ne contiennent pas directement d'informations personnelles (historique de changements d'un territoire, d'un service, d'un motif, etc...)
  - mais on efface l'identité de la personne qui a fait la modification au bout d'un an (autrement dit la colonne `versions.whodunnit`)
  - explication de cette décision : ça permet de débugger sur du plus long terme, et vu qu'on n'a pas de problèmes de données personnelles ou de volume de données pour ça, on peut se le permettre (ça n'avait probablement pas été fait avant par soucis de simplicité en plus de ces deux contraintes)
 
- Indiquer en bas de l'historique des changements que les changements avant une certaine date ne sont pas disponibles (en fonction des règles ci-dessus) > texte à rédiger

- Supprimer les données personnelles des receipts de plus de six mois (c'est à dire garder le receipt, mais effacer le contenu des 4 colonnes qui ont des données personnelles)

**Comment by mekaidmekaid** [comment]
**Pour l'export** : Dans le cadre de la RGPD, cette information n'est plus conservée au delà d'un an.
**Pour l'interface** : Dans le cadre de la RGPD, ces informations ne sont plus conservées au delà d'un an.

**Comment by mekaidmekaid** [comment]
@victormours si tu penses que c'est good

**Comment by victormours** [comment]
@mekaidmekaid Pour l'export c'est nickel, pour l'interface j'ai l'impression c'est pas forcément très clair de quelles informations on parle. Est-ce que ça t'irait qu'on mette "Dans le cadre du RGPD, l'historique des changements n'est plus conservé au delà d'un an." ?
