### ISSUE TITLE
API ANTS - "Already exists in database" lors de la synchro

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#4318]
Nous pensions que #4198 allais régler le problème mais nous continuons à avoir entre 20 et 80 occurrences par jour (retries compris).

![image](https://github.com/betagouv/rdv-service-public/assets/6357692/a7d4d7f4-1865-4855-9e20-f5941c667ab7)

Il faudrait investiguer pour voir si il s'agit d'un bug gênant ou d'une race condition sans importance (nous déclenchons beaucoup de jobs de synchro, il faudrait peut-être en déclencher moins, ou empêcher qu'ils ne s'exécutent en même temps).

**Comment by adipasquale** [comment]
J’ai essayé de creuser un peu en regardant les jobs en base : 

```sh
scalingo --app production-rdv-mairie --region osc-secnum-fr1 run rails c --sandbox
```

```rb
GoodJob::Job.where(job_class: "Ants::SyncAppointmentJob").where("(serialized_p
arams->'arguments'->0->'rdv_attributes'->>'id')::int = ?", 68506).to_a
```

Où `68506` est un id vu dans Sentry.

De ma compréhension : 

- il ne s’agit pas d’enqueue quasi concommitants de 2 jobs identiques pour déclarer un nouveau RDV 
- il semble que ça se produise plutôt sur des appels d’updates de RDV que de création (c’est à dire que je vois des appels précédents pour le même id de rdv et n’ayant pas échoué)

Dans [le code](https://github.com/betagouv/rdv-service-public/blob/production/app/jobs/ants/sync_appointment_job.rb/#L61-L63) je vois qu’en fait on ne peut pas faire d’update donc on fait des delete + recreate

peut-être qu’on pourrait simplement introduire un petit sleep entre les delete et les create ? 
ou alors peut-être que les delete ne fonctionnent pas correctement

**Comment by francois-ferrandis** [comment]
C'était ma supposition aussi, peut-être que le delete est fait de façon asynchrone côté ANTS, et j'avoue que si on met un `sleep 2` juste pour voir si le volume d'erreur diminue, on pourra ensuite chercher une solution plus élégante. :+1:

**Comment by adipasquale** [comment]
le sleep(2) n’a pas arrangé significativement les choses !

Il semble qu’un peu plus de la moitié des jobs rencontrant cette erreur finissent par réussir à s’éxecuter tandis que l’autre moitié échoue 

```rb
GoodJob::DiscreteExecution
  .joins(:job)
  .where(good_jobs: { job_class: "Ants::SyncAppointmentJob", queue_name: "default"})
  .where("good_job_executions.error LIKE '%Already exists%'")
  .where("good_jobs.scheduled_at < ?", 2.days.ago)
  .group("CASE WHEN good_jobs.error IS NULL THEN 'still_in_error' ELSE 'succeeded' END")
  .count
  
# => {"still_in_error"=>305, "succeeded"=>399} sur production-rdv-mairie
```

**Comment by adipasquale** [comment]
Une nouvelle piste serait d’ajouter dans le contexte de l’erreur sentry l’info de savoir si un delete vient d’être fait ou non dans le job.
Cela permettrait de comprendre si notre suspicion de l’enchainement delete-recreate est valide ou si ça vient d’autre chose.

**Comment by adipasquale** [comment]
<img width="314" alt="image" src="https://github.com/betagouv/rdv-service-public/assets/883348/15783fd9-2617-4392-b99f-694e30a7c044">

ça ne semble pas venir du delete-recreate !

**Comment by francois-ferrandis** [comment]
Tu penses qu'il y a d'autres endroits dans le job où l'on peut ajouter des tags pour explorer des hypothèses ?

**Comment by adipasquale** [comment]
non, je commence à sécher là :/

j’essaie d’explorer d’autres usages ou trouver plus de doc

je suis tombé là dessus https://git.entrouvert.org/entrouvert/ants-hub/src/commit/0d4155ed3d25f12e461f2fb4e83ea0535ab3f6e2/src/ants_hub/api/ants.py

j’ai repéré qu’ils font un `.upper` sur l’ID du dossier mais ça ne semble pas être un problème chez nous

ou bien ça https://github.com/lutece-secteur-public/gru-module-workflow-appointmentants/blob/06c8a5b6018a83c543abb728fad46bb33007216e/src/java/fr/paris/lutece/plugins/workflow/modules/appointmentants/service/TaskAntsAppointmentService.java#L626 qui m’a rappelé ce que c’est que du java

mais rien d’intéressant non plus

**Comment by adipasquale** [comment]
après avoir vérifié à nouveau, il semble que dans certains cas il y a des jobs enqueued de manière quasi simultané pour le même RDV ce qui pourrait potentiellement expliquer le souci 🤷 

```
irb(main):002> GoodJob::Job.where(job_class: "Ants::SyncAppointmentJob").where("(serialized_params->'arguments'->0->'rdv_attributes'->>'id')::int = ?", 85397).to_a.pluck(:scheduled_at)
=> [Tue, 02 Jul 2024 15:24:01.558739000 CEST +02:00, Tue, 02 Jul 2024 15:24:04.992177000 CEST +02:00]
```

on pourrait tenter d’utiliser un lock `rdv-ants-#{rdv.id}` ?

**Comment by adipasquale** [comment]
cf https://github.com/betagouv/rdv-service-public/pull/4397/files @francois-ferrandis wdyt ?

**Comment by francois-ferrandis** [comment]
> cf https://github.com/betagouv/rdv-service-public/pull/4397/files @francois-ferrandis wdyt ?

Ça coûte rien d'essayer je pense.

Piste suivante : vérifier si les données distantes sont à mettre à jour avant de lancer des opérations d'écriture.

**Comment by adipasquale** [comment]
ça se produit toujours 🤯 

autre piste : pour les `application_ids` concernés par les issues sentry je trouve parfois plusieurs users avec ce même `ants_pre_demande_number`.
Ça n’a pas l’air d’être toujours le cas néanmoins: 

```rb
﻿obsolete_application_ids =
  GoodJob::DiscreteExecution
    .joins(:job)
    .where(good_jobs: { job_class: "Ants::SyncAppointmentJob", queue_name: "default"})
    .where("good_jobs.scheduled_at > ?", 4.days.ago)
    .where("good_job_executions.error LIKE '%Already exists%'")
    .to_a
    .map { _1.serialized_params.dig("arguments", 0, "rdv_attributes", "obsolete_application_id") }
    .compact
    .uniq

User.where(ants_pre_demande_number: obsolete_application_ids)
    .group(:ants_pre_demande_number)
    .count
    .group_by(&:last)
    .transform_values(&:count)
    
=> {1=>297, 2=>45, 20103=>1, 3=>2}
```

**Comment by adipasquale** [comment]
la suite trépidante de mes investigations 🔍 

Je viens de prendre un job qui avait échoué avec cette erreur et j’ai essayé de refaire les appel curl depuis mon PC en réutilisant la clé de prod

## 1. get status

me montre bien validated et aucun appointments

## 2. create appointment params identiques à ceux essayés dans le job

échec avec le même message `already exists`.

## 3. create appointment avec une `management_url` légèrement différente (en rajoutant une lettre à la fin) 
 
succès, magie, l’appointment est créé 🎉 .

## 4. delete appointment avec les params required (`application_id`, `meeting_point`, `appointment_date`)

succès, et 

> [!WARNING]
> `{"rowcount":2}`

Comme si la suppression avait supprimé deux appointments dont un précédemment invisible ! 

## 5. create appointment params identiques à ceux essayés dans le job (identique à 3.)

succès 🚀 

## donc maintenant 

pistes 

- soit essayer de comprendre pourquoi certains appointments sont "invisibles" à l’oeil nu dans le call status
- soit ne pas essayer de comprendre, catcher les erreurs already exists et tenter une suppression aveugle

ping @francois-ferrandis 


un apprentissage aussi : le `management_url` semble avoir une contrainte d’unicité, c’est lui qui bloque avec `already exists`

**Comment by adipasquale** [comment]
Je viens de réinvestiguer un peu. 
Je vois que la grande majorité des échecs avec cette erreur se produisent pour des RDVs avec plusieurs users.

```rb
# $ scalingo --region osc-secnum-fr1 --app production-rdv-mairie run rails c --sandbox

GoodJob::Execution.where(job_class: "Ants::SyncAppointmentJob").where("error LIKE '%Already exists%'").map { _1.serialized_p
arams["arguments"][0]["rdv_attributes"]["users_ids"] }
```

Je vois aussi qu’on essaie de créer un appointment par user https://github.com/betagouv/rdv-service-public/blob/production/app/jobs/ants/sync_appointment_job.rb#L77

Et je pense avoir compris que le `management_url` a une contrainte d’unicité côté ANTS - cf mon précédent commentaire.
Or cette URL est unique par RDV chez nous mais pas par user.

Je m’apprêtais à rajouter un hack pour faire une URL unique par user mais en fait je pense qu’on ne devrait créer qu’un appointment.

Les usagers d’un RDV ont tous l’air d’avoir le même ants_pre_demande_number

```rb
GoodJob::Execution.where(job_class: "Ants::SyncAppointmentJob").where("error LIKE '%Already exists%'").map { _1.serialized_params["arguments"][0]["rdv_attributes"]["users_ids"] }.map { User.where(id: _1).pluck(:ants_pre_demande_number) }
```

Je vais donc ouvrir une PR pour ne créer qu’un appointment même s’il y a plusieurs users.

**Comment by adipasquale** [comment]
J’ai encore creusé un peu, il semble en fait possible en tant qu’usager de prendre un RDV avec plusieurs users (des proches probablement) qui ont des numéros ANTS différents

```rb
Rdv.where(created_by_type: "User").joins(:motif).where.not(motifs: { motif_category_id: nil }).where("users_count > 1").to_a
.select { _1.users.map(&:ants_pre_demande_number).uniq.compact.count > 1 }.each { |rdv| puts "rdv #{rdv.id} - #{rdv.users.map(&:ants_pre_de
mande_number).compact.uniq.count}"; rdv.users.each { puts "user #{_1.id}: #{_1.ants_pre_demande_number}" }; puts; }
```

On ne peut donc pas simplement créer un seul appointment.
Il faudrait plutôt : 
- s’assurer de ne créer qu’un appointment par `ants_pre_demande_number` unique
- générer une `management_url` unique artificielle pour ces appointments. Par exemple en rajoutant un query param ignoré : `https://rdv.anct.gouv.fr/users/rdvs/123?ants_pre_demande_number=23456`

**Comment by adipasquale** [comment]
Le volume de ces erreurs semble avoir largement diminué depuis la mise en production de https://github.com/betagouv/rdv-service-public/pull/4734 le 30/10 à 14h

évènements sur les 30 derniers jours :
<img width="335" alt="image" src="https://github.com/user-attachments/assets/dd99f9a0-429e-41b3-bb67-0b802bde1f74">

**Comment by francois-ferrandis** [comment]
> Le volume de ces erreurs semble avoir largement diminué depuis la mise en production de #4734 le 30/10 à 14h

On voit aussi l'amélioration dans le mail que l'ANTS nous envoie chaque semaine sur notre adresse mail technique. :+1:

**Comment by adipasquale** [comment]
je ferme cette issue d’enquête pour une nouvelle issue de correction du problème avec les informations apprises ici : #4779
