### ISSUE TITLE
Erreur 500 en réponse webhooks dans la Drôme

### ISSUE THREAD

**Issue by francois-ferrandis** [betagouv/rdv-solidarites.fr#4320]
Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/82378
Entre 50 et 150 occurrences par jour

Le corps de la réponse : `{"message": "Internal Server Error"}`

Il faut à minima informer les responsables que nous avons ces erreurs, en attendant de trouver une solution plus automatisée (#4319).

**Comment by adipasquale** [comment]
j’ai informé par mail aujourd’hui et snooze l’erreur, je ferme cette issue tant que ce n’est plus dans nos mains

**Comment by adipasquale** [comment]
L’équipe technique de la Drome vient de nous répondre qu’ils sont sur le coup 👍

**Comment by adipasquale** [comment]
je leur ai réécrit à l’instant car ça se produit toujours. 
Je re-snooze l’erreur pour 2 semaines le temps qu’ils s’en occupent.
