### ISSUE TITLE
How to open two separate tabs in same google chrome window using webdriver and python?

### ISSUE THREAD

**Issue by armin1430** [betagouv/rdv-solidarites.fr#438]
i wrote a program which can open the first tab by webdriver and my problem is i wan't webdriver to open another tab in the same page of chrome ( like how Ctrl + t works ) and yes i'm going to interact with the second tab. you know like grab some information from the first page and put it on the second page and reverse.

**Comment by guillett** [comment]
Hi, are you sure you posted your question in the relevant repository?
