### ISSUE TITLE
Bug : Les agents ne sont pas notifiés quand l'usager déplace son rdv (et change d'agent)

### ISSUE THREAD

**Issue by Holist** [betagouv/rdv-solidarites.fr#4393]
## ℹ️ Contexte 

Ticket : https://github.com/betagouv/rdv-insertion/issues/2166

Lorsqu'un usager déplace son rdv il peut être affecté à un autre agent.
Si c'est le cas on notifie le nouvel agent que son rdv a été modifié (alors que pour lui il s'agit d'une création) mais surtout l'agent d'origine n'est pas notifié du changement (dans son cas une annulation)

## 💡 Solution envisagée

On s'attend à ce que les 2 agents soient notifiés correctement.
Question : Quel niveau d'information doit on transmettre à l'agent d'origine ?
(Est ce qu'on doit prévenir l'agent à l'origine du rdv que le rdv a été déplacé vers un autre agent....)

**Comment by victormours** [comment]
discuté en visio : on fait un fix autour de `Notifiers::RdvUpdated.new`, probablement en introduisant un nouveau template de mail pour indiquer à l'agent d'origine que le rdv a été réaffecté à un autre agent (plutôt qu'un mail d'annulation qui ne serait pas exact)
