### ISSUE TITLE
Problème avec la synchronisation automatique de l'agenda à cause de la messagerie MDeamon (besoin Ariège)

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-solidarites.fr#4426]
## ℹ️ Contexte 

* Comportement actuel : 
Dans RDV Solidarités, il est indiqué le lien pour la synchronisation 

https://www.rdv-solidarites.fr/agents/calendar_sync/webcal_sync 

Allez dans votre agenda externe et ajoutez un nouveau calendrier avec cette URL :

_webcal://www.rdv-solidarites.fr/calendrier/prenom-nom-c3eb0fa5-6593-47df-9276-351e566de7db.ics_

Tous vos rendez-vous de RDV Solidarités seront copiés automatiquement au fur et à mesure de leur création (ou modification).

## ❓ Définition du problème

L'import de ce lien donne une erreur pour une admin de l'Ariège : erreur d'importation du calendrier.

L'admin en question est user ID : [20441]

## 💡 Solution envisagée

Selon le service technique du département, pour palier à cette erreur, il faut remplacer webcal:// par http://  

Est-ce qu'il est possible demander une évolution de la page de synchronisation en ajoutant un 2e lien de synchronisation qui soit en http pour ceux qui se retrouvent en erreur avec le webcal. On verrait donc 2 liens possibles : 
- webcal en premier 
- http en-dessous avec la phrase "si vous rencontrez une erreur de synchronisation avec le lien ci-dessus, vous pouvez essayer avec celui-ci"

**Comment by francois-ferrandis** [comment]
Point assez important : c'est `https` au lieu de `http`, sinon le serveur refuse de répondre à ce que je vois.

Je propose de ne plus proposer de lien avec le protocol `webcal://` mais de plutôt indiquer `https://` pour tout le monde, sans en faire un lien mais plutôt une URL à copier / coller.

En effet, l'usage du préfixe `webcal://` permet à certains navigateurs d'ouvrir le flux dans le gestionnaire de calendrier par défaut sur le device, mais ce n'est pas forcément le comportement souhaité et ça peut troubler des agents non experts. Avec un lien à copier / coller, l'agent est en maîtrise de l'endroit où l'URL est ajoutée.

**Comment by francois-ferrandis** [comment]
Autre remarque sans dépendance sur le commentaire ci-dessus, la page indique : 

> Tous vos rendez-vous de RDV Solidarités seront copiés automatiquement au fur et à mesure de leur création (ou modification).

Je pense que cette phrase est trompeuse, car en réalité, l'abonnement au flux ICS permet de faire apparaître en lecture seul les RDVs de RDV-Solidarités sur un calendrier perso. Si je lis que mes RDVs sont "copiés", j'ai tendance à comprendre que je peux ensuite travailler sur une copie de ces RDVs. Je propose donc de remplacer "copiés" par "affichés", et éventuellement d'indiquer que c'est uniquement en lecture seule.

**Comment by SalmaBennani** [comment]
@francois-ferrandis J'ai une relance de la part de l'Ariège. Est-ce que tu sais quand ce ticket sera pris ? Merci
