### ISSUE TITLE
trier les territoires sur la page contact

### ISSUE THREAD

**Issue by adipasquale** [betagouv/rdv-solidarites.fr#4744]
## ℹ️ Contexte 

On cherche un petit ticket à faire pour l’arrivée d’Antoine

## ❓ Définition du problème

Sur la page contact par exemple https://rdv.anct.gouv.fr/contact , la liste des territoires n’est pas triée.

## 💡 Solution envisagée

Trier la liste !

**Comment by AntoineGirard** [comment]
Il semble également qu’historiquement, nous ne souhaitions pas afficher les départements qui n’ont pas de numéro de téléphone. 
https://github.com/betagouv/rdv-service-public/blob/2693798dd8cb52d5c526e67c8d62a2474b4d370c/app/views/static_pages/contact.html.slim#L5

En production, il semblerait qu’on ait des valeurs _empty_ 
<img width="658" alt="image" src="https://github.com/user-attachments/assets/0c6ec0a5-0849-4f57-9def-e635fd85a9ba">

J’envisage donc de changer le filtre pour retirer ces valeurs _empty_ et de faire un tri + affichage par département

**Comment by AntoineGirard** [comment]
Voici donc 2 propositions : 

**1️⃣ On affiche les territoires par département**

Sachant que nous avons des départements pour lesquels nous avons plusieurs entités (par exemple le 75), nous affichons et ordonnons par département (puis par nom) comme sur la capture d’écran ci-dessous. 

<img width="680" alt="image" src="https://github.com/user-attachments/assets/a87ef54a-e83e-4ca8-9b05-3e9e01a5f9fe">


**2️⃣ On affiche les territoires par ordre alphabétique**

Cela reste peut-être un peu étrange compte tenu du fait que le nom du territoire peut varier (parfois le nom d’une ville, parfois un ministère préfixé par « Ministère », parfois un tribunal, etc). 



Dans les deux cas, on corrige la requête en retirant les entités qui n’ont pas de numéro de téléphone (et qui par consèquent n’ont pas leur place sur une page de contact).

À vos avis !

**Comment by AntoineGirard** [comment]
Suite à une discussion avec @victormours nous partirions plutôt sur la proposition 1️⃣ en retirant le texte « Votre département » qui n’a plus beaucoup de sens maintenant que nous avons des organisations plutôt que des départements.

J’en profite pour renommer « Autres départements »

**Comment by francois-ferrandis** [comment]
> Il semble également qu’historiquement, nous ne souhaitions pas afficher les départements qui n’ont pas de numéro de téléphone.
> 
> https://github.com/betagouv/rdv-service-public/blob/2693798dd8cb52d5c526e67c8d62a2474b4d370c/app/views/static_pages/contact.html.slim#L5
> 
> J’envisage donc de changer le filtre pour retirer ces valeurs _empty_ et de faire un tri + affichage par département

Dans la requête tu peux utiliser la colonne `phone_number_formatted`, qui sera à `nil` si `phone_number` est à `""`. :wink: 

Et je plussoie la solution 1, bien plus pertinente (les français ont l'habitude de parser une liste de numéros de département) !

**Comment by adipasquale** [comment]
super @AntoineGirard merci 🙇 

ça me fait me souvenir de ce fichier chez Collectif Objets https://github.com/betagouv/collectif-objets/blob/47b92abbf54f9b9969ae3a907a0014155553d3da/db/migrate/noms_departements.csv#L4

**Comment by AntoineGirard** [comment]
@francois-ferrandis merci pour l’info sur la colonne `phone_number_formatted`

@adipasquale ta suggestion serait qu’on ait une table pour stocker les noms des départements et les afficher sur la page plutôt que d’avoir les codes de département ?
