### ISSUE TITLE
Remplacer les icones du menu par celles du DSFR

### ISSUE THREAD

**Issue by Teodora-Stanki** [betagouv/rdv-solidarites.fr#4915]
Dans le cadre du passage de l'interface agent au DSFR, nous souhaiterions remplacer les icones actuelles par celles du DSFR :

**Menu Agent Admin d'orga :** 
Planning :  `<span class="fr-icon-calendar-fill" aria-hidden="true"></span>`
Usagers : `<span class="fr-icon-group-fill" aria-hidden="true"></span>`
Liste des RDV : `<span class="fr-icon-survey-fill" aria-hidden="true"></span>`
Statistiques : `<span class="fr-icon-bar-chart-box-fill" aria-hidden="true"></span>`
Paramètres : `<span class="fr-icon-settings-5-fill" aria-hidden="true"></span>`
Support : `<span class="fr-icon-question-fill" aria-hidden="true"></span>`

**Menu Agent Basique :** 
Lieu : `<span class="fr-icon-map-pin-2-fill" aria-hidden="true"></span>`
Motifs : `<span class="fr-icon-draft-fill" aria-hidden="true"></span>`

Documentation : https://www.systeme-de-design.gouv.fr/fondamentaux/icone

On peut discuter de la cohérence de certains des pictos, il s'agit la que d'une première proposition.

**Comment by victormours** [comment]
Trop bien, voilà ce que ça donnerait pour un admin :

<img width="358" alt="Screenshot 2024-12-18 at 16 59 27" src="https://github.com/user-attachments/assets/e0bf2d8e-86c2-4401-8cc3-955107dddc3b" />

Et pour un agent basique : 

<img width="329" alt="Screenshot 2024-12-18 at 17 02 42" src="https://github.com/user-attachments/assets/8ad7083a-997a-4b40-9aea-ff8e8613182c" />

Pour le planning, l'icone de calendar basique du dsfr est un peu triste (et je trouve qu'elle ressemble à une valise). Qu'est-ce que tu penserais de `fr-icon-calendar-event-fill` <img width="30" alt="Screenshot 2024-12-18 at 17 07 10" src="https://github.com/user-attachments/assets/843f9c71-deb4-44f9-abdd-31b2a71ac747" /> ?



Pour les lieux, dans la mise à jour de la prise de rdv côté usager (https://github.com/betagouv/rdv-service-public/pull/4894/files) on utilise `fr-icon-building-fill` 
<img width="28" alt="Screenshot 2024-12-18 at 17 07 29" src="https://github.com/user-attachments/assets/61b65e8a-525e-48e9-a7e1-553e2c026e1e" />
pour les rdv sur place. Est-ce que ça vaudrait pas le coup d'harmoniser ça ici et d'utiliser la même icône ?

J'ai mis la taille par défaut des icônes, qui sont un peu plus grosses que celle d'avant, mais on peut complètement ajuster ça.
Idem pour la marge, j'ai mis un `1v` mais on peut changer ça

**Comment by Teodora-Stanki** [comment]
Je trouve le poids des icones un peu excessif. Peut-on les réduire pour du 20px ou 16px ? 
1w me semble ok en terme d'espacement

Ok pour l'icone calendar-event
Ok pour l'icone buildings pour les rdvs sur place.

Peut etre envisager de les passer en outlined si jamais malgré le changement de taille ils restent proéminents

**Comment by victormours** [comment]
Ça marche, je fais les mises à jour et j'ouvre la pr
